# Generated by tools/render_api_specs.py from tools/api_specs.yml.
# Do not edit by hand: the next render overwrites it.
#
# Enumeration specs for resource types inspec-aws does not ship. Read by
# libraries/aws_api_assets.rb; see tools/api_specs.yml for what each key means.
API_SPECS = {
  'aws_acm_certificate' => {
    'arn' => 'certificate_arn',
    'client' => 'Aws::ACM::Client',
    'collection' => 'certificate_summary_list',
    'fields' => {
      'in_use' => 'in_use',
      'key_algorithm' => 'key_algorithm'
    },
    'gem' => 'aws-sdk-acm',
    'id' => 'domain_name',
    'list' => 'list_certificates'
  },
  'aws_api_gateway_stage' => {
    'arg' => 'rest_api_id',
    'client' => 'Aws::APIGateway::Client',
    'collection' => 'item',
    'fields' => {
      'access_log_destination_arn' => 'access_log_settings.destination_arn',
      'cache_cluster_enabled' => 'cache_cluster_enabled',
      'client_certificate_id' => 'client_certificate_id',
      'tracing_enabled' => 'tracing_enabled',
      'web_acl_arn' => 'web_acl_arn'
    },
    'gem' => 'aws-sdk-apigateway',
    'id' => 'stage_name',
    'list' => 'get_stages',
    'parent' => {
      'collection' => 'items',
      'id' => 'id',
      'list' => 'get_rest_apis'
    },
    'scope' => 'regional'
  },
  'aws_apprunner_service' => {
    'arn' => 'service_arn',
    'client' => 'Aws::AppRunner::Client',
    'collection' => 'service_summary_list',
    'fields' => {},
    'gem' => 'aws-sdk-apprunner',
    'id' => 'service_name',
    'list' => 'list_services'
  },
  'aws_athena_workgroup' => {
    'client' => 'Aws::Athena::Client',
    'collection' => 'work_groups',
    'fields' => {
      'state' => 'state'
    },
    'gem' => 'aws-sdk-athena',
    'id' => 'name',
    'list' => 'list_work_groups'
  },
  'aws_backup_protected_resource' => {
    'arn' => 'resource_arn',
    'client' => 'Aws::Backup::Client',
    'collection' => 'results',
    'fields' => {
      'last_backup_time' => 'last_backup_time',
      'resource_name' => 'resource_name',
      'resource_type' => 'resource_type'
    },
    'gem' => 'aws-sdk-backup',
    'id' => 'resource_arn',
    'list' => 'list_protected_resources',
    'scope' => 'regional'
  },
  'aws_backup_vault' => {
    'arn' => 'backup_vault_arn',
    'client' => 'Aws::Backup::Client',
    'collection' => 'backup_vault_list',
    'fields' => {
      'encryption_key_arn' => 'encryption_key_arn'
    },
    'gem' => 'aws-sdk-backup',
    'id' => 'backup_vault_name',
    'list' => 'list_backup_vaults'
  },
  'aws_cloudfront_distribution' => {
    'arn' => 'arn',
    'client' => 'Aws::CloudFront::Client',
    'collection' => 'distribution_list.items',
    'fields' => {
      'response_headers_policy_id' => 'default_cache_behavior.response_headers_policy_id'
    },
    'gem' => 'aws-sdk-cloudfront',
    'id' => 'id',
    'list' => 'list_distributions',
    'scope' => 'global'
  },
  'aws_cloudtrail' => {
    'arn' => 'trail_arn',
    'client' => 'Aws::CloudTrail::Client',
    'collection' => 'trail_list',
    'fields' => {
      'is_multi_region_trail' => 'is_multi_region_trail',
      'kms_key_id' => 'kms_key_id',
      'log_file_validation_enabled' => 'log_file_validation_enabled',
      'sns_topic_arn' => 'sns_topic_arn'
    },
    'gem' => 'aws-sdk-cloudtrail',
    'id' => 'name',
    'list' => 'describe_trails',
    'scope' => 'regional'
  },
  'aws_cloudtrail_event_data_store' => {
    'arg' => 'event_data_store',
    'arn' => 'event_data_store_arn',
    'client' => 'Aws::CloudTrail::Client',
    'collection' => '_response',
    'fields' => {
      'kms_key_id' => 'kms_key_id',
      'multi_region_enabled' => 'multi_region_enabled',
      'retention_period' => 'retention_period',
      'status' => 'status',
      'termination_protection_enabled' => 'termination_protection_enabled'
    },
    'gem' => 'aws-sdk-cloudtrail',
    'id' => 'name',
    'list' => 'get_event_data_store',
    'parent' => {
      'collection' => 'event_data_stores',
      'id' => 'event_data_store_arn',
      'list' => 'list_event_data_stores'
    },
    'scope' => 'regional'
  },
  'aws_cloudwatch_log_group' => {
    'arn' => 'arn',
    'client' => 'Aws::CloudWatchLogs::Client',
    'collection' => 'log_groups',
    'fields' => {
      'kms_key_id' => 'kms_key_id',
      'retention_in_days' => 'retention_in_days'
    },
    'gem' => 'aws-sdk-cloudwatchlogs',
    'id' => 'log_group_name',
    'list' => 'describe_log_groups'
  },
  'aws_cloudwatch_metric_alarm' => {
    'arn' => 'alarm_arn',
    'client' => 'Aws::CloudWatch::Client',
    'collection' => 'metric_alarms',
    'fields' => {
      'actions_enabled' => 'actions_enabled',
      'alarm_actions' => 'alarm_actions'
    },
    'gem' => 'aws-sdk-cloudwatch',
    'id' => 'alarm_name',
    'list' => 'describe_alarms',
    'scope' => 'regional'
  },
  'aws_config_configuration_aggregator' => {
    'arn' => 'configuration_aggregator_arn',
    'client' => 'Aws::ConfigService::Client',
    'collection' => 'configuration_aggregators',
    'fields' => {
      'organization_all_aws_regions' => 'organization_aggregation_source.all_aws_regions',
      'organization_role_arn' => 'organization_aggregation_source.role_arn'
    },
    'gem' => 'aws-sdk-configservice',
    'id' => 'configuration_aggregator_name',
    'list' => 'describe_configuration_aggregators',
    'scope' => 'regional'
  },
  'aws_dms_replication_instance' => {
    'arn' => 'replication_instance_arn',
    'client' => 'Aws::DatabaseMigrationService::Client',
    'collection' => 'replication_instances',
    'fields' => {
      'auto_minor_version_upgrade' => 'auto_minor_version_upgrade',
      'multi_az' => 'multi_az',
      'publicly_accessible' => 'publicly_accessible'
    },
    'gem' => 'aws-sdk-databasemigrationservice',
    'id' => 'replication_instance_identifier',
    'list' => 'describe_replication_instances'
  },
  'aws_dms_s3_endpoint' => {
    'arn' => 'endpoint_arn',
    'client' => 'Aws::DatabaseMigrationService::Client',
    'collection' => 'endpoints',
    'fields' => {
      'endpoint_type' => 'endpoint_type',
      'engine_name' => 'engine_name',
      's3_encryption_mode' => 's3_settings.encryption_mode',
      's3_kms_key_arn' => 's3_settings.server_side_encryption_kms_key_id'
    },
    'gem' => 'aws-sdk-databasemigrationservice',
    'id' => 'endpoint_identifier',
    'list' => 'describe_endpoints',
    'scope' => 'regional'
  },
  'aws_ebs_volume' => {
    'client' => 'Aws::EC2::Client',
    'collection' => 'volumes',
    'fields' => {
      'encrypted' => 'encrypted',
      'state' => 'state'
    },
    'gem' => 'aws-sdk-ec2',
    'id' => 'volume_id',
    'list' => 'describe_volumes',
    'scope' => 'regional'
  },
  'aws_ec2_transit_gateway' => {
    'arn' => 'transit_gateway_arn',
    'client' => 'Aws::EC2::Client',
    'collection' => 'transit_gateways',
    'fields' => {
      'auto_accept_shared_attachments' => 'options.auto_accept_shared_attachments',
      'default_route_table_association' => 'options.default_route_table_association',
      'dns_support' => 'options.dns_support',
      'state' => 'state'
    },
    'gem' => 'aws-sdk-ec2',
    'id' => 'transit_gateway_id',
    'list' => 'describe_transit_gateways',
    'scope' => 'regional'
  },
  'aws_ecr_repository' => {
    'arn' => 'repository_arn',
    'client' => 'Aws::ECR::Client',
    'collection' => 'repositories',
    'fields' => {
      'encryption_type' => 'encryption_configuration.encryption_type',
      'image_tag_mutability' => 'image_tag_mutability',
      'kms_key' => 'encryption_configuration.kms_key',
      'scan_on_push' => 'image_scanning_configuration.scan_on_push'
    },
    'gem' => 'aws-sdk-ecr',
    'id' => 'repository_name',
    'list' => 'describe_repositories'
  },
  'aws_ecs_task_definition' => {
    'arg' => 'task_definition',
    'arn' => 'task_definition_arn',
    'client' => 'Aws::ECS::Client',
    'collection' => 'task_definition',
    'fields' => {
      'container_definitions' => 'container_definitions'
    },
    'gem' => 'aws-sdk-ecs',
    'id' => 'task_definition_arn',
    'list' => 'describe_task_definition',
    'parent' => {
      'collection' => 'families',
      'id' => '_self',
      'list' => 'list_task_definition_families'
    },
    'scope' => 'regional'
  },
  'aws_efs_access_point' => {
    'arn' => 'access_point_arn',
    'client' => 'Aws::EFS::Client',
    'collection' => 'access_points',
    'fields' => {
      'file_system_id' => 'file_system_id',
      'life_cycle_state' => 'life_cycle_state',
      'posix_user_gid' => 'posix_user.gid',
      'posix_user_uid' => 'posix_user.uid',
      'root_directory_path' => 'root_directory.path'
    },
    'gem' => 'aws-sdk-efs',
    'id' => 'access_point_id',
    'list' => 'describe_access_points',
    'scope' => 'regional'
  },
  'aws_efs_file_system' => {
    'arn' => 'file_system_arn',
    'client' => 'Aws::EFS::Client',
    'collection' => 'file_systems',
    'fields' => {
      'encrypted' => 'encrypted',
      'kms_key_id' => 'kms_key_id'
    },
    'gem' => 'aws-sdk-efs',
    'id' => 'file_system_id',
    'list' => 'describe_file_systems'
  },
  'aws_eks_cluster' => {
    'arg' => 'name',
    'arn' => 'arn',
    'client' => 'Aws::EKS::Client',
    'collection' => 'cluster',
    'fields' => {
      'encryption_config' => 'encryption_config',
      'endpoint_private_access' => 'resources_vpc_config.endpoint_private_access',
      'endpoint_public_access' => 'resources_vpc_config.endpoint_public_access',
      'public_access_cidrs' => 'resources_vpc_config.public_access_cidrs',
      'status' => 'status',
      'version' => 'version'
    },
    'gem' => 'aws-sdk-eks',
    'id' => 'name',
    'list' => 'describe_cluster',
    'parent' => {
      'collection' => 'clusters',
      'id' => '_self',
      'list' => 'list_clusters'
    },
    'scope' => 'regional'
  },
  'aws_elb' => {
    'client' => 'Aws::ElasticLoadBalancing::Client',
    'collection' => 'load_balancer_descriptions',
    'fields' => {
      'listener_descriptions' => 'listener_descriptions'
    },
    'gem' => 'aws-sdk-elasticloadbalancing',
    'id' => 'load_balancer_name',
    'list' => 'describe_load_balancers',
    'scope' => 'regional'
  },
  'aws_emr_cluster' => {
    'arn' => 'cluster_arn',
    'client' => 'Aws::EMR::Client',
    'collection' => 'clusters',
    'fields' => {
      'status' => 'status.state'
    },
    'gem' => 'aws-sdk-emr',
    'id' => 'id',
    'list' => 'list_clusters'
  },
  'aws_glue_crawler' => {
    'client' => 'Aws::Glue::Client',
    'collection' => 'crawlers',
    'fields' => {
      'security_configuration' => 'crawler_security_configuration'
    },
    'gem' => 'aws-sdk-glue',
    'id' => 'name',
    'list' => 'get_crawlers'
  },
  'aws_glue_security_configuration' => {
    'client' => 'Aws::Glue::Client',
    'collection' => 'security_configurations',
    'fields' => {
      'encryption_configuration' => 'encryption_configuration'
    },
    'gem' => 'aws-sdk-glue',
    'id' => 'name',
    'list' => 'get_security_configurations',
    'scope' => 'regional'
  },
  'aws_guardduty_detector' => {
    'arg' => 'detector_id',
    'client' => 'Aws::GuardDuty::Client',
    'collection' => '_response',
    'fields' => {
      'cloudtrail_status' => 'data_sources.cloud_trail.status',
      'finding_publishing_frequency' => 'finding_publishing_frequency',
      's3_logs_status' => 'data_sources.s3_logs.status',
      'status' => 'status'
    },
    'gem' => 'aws-sdk-guardduty',
    'id' => '_parent',
    'list' => 'get_detector',
    'parent' => {
      'collection' => 'detector_ids',
      'id' => '_self',
      'list' => 'list_detectors'
    },
    'scope' => 'regional'
  },
  'aws_iam_role_policy_attachment' => {
    'arg' => 'role_name',
    'arn' => 'policy_arn',
    'client' => 'Aws::IAM::Client',
    'collection' => 'attached_policies',
    'fields' => {
      'policy_arn' => 'policy_arn',
      'policy_name' => 'policy_name'
    },
    'gem' => 'aws-sdk-iam',
    'id' => '_parent',
    'list' => 'list_attached_role_policies',
    'parent' => {
      'collection' => 'roles',
      'id' => 'role_name',
      'list' => 'list_roles'
    },
    'scope' => 'global'
  },
  'aws_kinesis_stream' => {
    'arn' => 'stream_arn',
    'client' => 'Aws::Kinesis::Client',
    'collection' => 'stream_summaries',
    'fields' => {},
    'gem' => 'aws-sdk-kinesis',
    'id' => 'stream_name',
    'list' => 'list_streams'
  },
  'aws_lambda_function' => {
    'arn' => 'function_arn',
    'client' => 'Aws::Lambda::Client',
    'collection' => 'functions',
    'fields' => {
      'kms_key_arn' => 'kms_key_arn',
      'runtime' => 'runtime',
      'tracing_mode' => 'tracing_config.mode',
      'vpc_subnet_ids' => 'vpc_config.subnet_ids'
    },
    'gem' => 'aws-sdk-lambda',
    'id' => 'function_name',
    'list' => 'list_functions'
  },
  'aws_lambda_function_url' => {
    'arg' => 'function_name',
    'arn' => 'function_arn',
    'client' => 'Aws::Lambda::Client',
    'collection' => 'function_url_configs',
    'fields' => {
      'auth_type' => 'auth_type',
      'cors_allow_credentials' => 'cors.allow_credentials',
      'cors_allow_methods' => 'cors.allow_methods',
      'cors_allow_origins' => 'cors.allow_origins',
      'invoke_mode' => 'invoke_mode'
    },
    'gem' => 'aws-sdk-lambda',
    'id' => 'function_url',
    'list' => 'list_function_url_configs',
    'parent' => {
      'collection' => 'functions',
      'id' => 'function_name',
      'list' => 'list_functions'
    },
    'scope' => 'regional'
  },
  'aws_lb_listener' => {
    'arg' => 'load_balancer_arn',
    'arn' => 'listener_arn',
    'client' => 'Aws::ElasticLoadBalancingV2::Client',
    'collection' => 'listeners',
    'fields' => {
      'alpn_policy' => 'alpn_policy',
      'mutual_authentication_mode' => 'mutual_authentication.mode',
      'port' => 'port',
      'protocol' => 'protocol',
      'ssl_policy' => 'ssl_policy'
    },
    'gem' => 'aws-sdk-elasticloadbalancingv2',
    'id' => 'listener_arn',
    'list' => 'describe_listeners',
    'parent' => {
      'collection' => 'load_balancers',
      'id' => 'load_balancer_arn',
      'list' => 'describe_load_balancers'
    },
    'scope' => 'regional'
  },
  'aws_memorydb_cluster' => {
    'arn' => 'arn',
    'client' => 'Aws::MemoryDB::Client',
    'collection' => 'clusters',
    'fields' => {
      'kms_key_id' => 'kms_key_id',
      'snapshot_retention_limit' => 'snapshot_retention_limit',
      'tls_enabled' => 'tls_enabled'
    },
    'gem' => 'aws-sdk-memorydb',
    'id' => 'name',
    'list' => 'describe_clusters'
  },
  'aws_memorydb_snapshot' => {
    'arn' => 'arn',
    'client' => 'Aws::MemoryDB::Client',
    'collection' => 'snapshots',
    'fields' => {
      'kms_key_arn' => 'kms_key_id',
      'source' => 'source',
      'status' => 'status'
    },
    'gem' => 'aws-sdk-memorydb',
    'id' => 'name',
    'list' => 'describe_snapshots',
    'scope' => 'regional'
  },
  'aws_msk_cluster' => {
    'arn' => 'cluster_arn',
    'client' => 'Aws::Kafka::Client',
    'collection' => 'cluster_info_list',
    'fields' => {
      'encryption_at_rest_kms_key_id' => 'encryption_info.encryption_at_rest.data_volume_kms_key_id',
      'encryption_in_transit_client_broker' => 'encryption_info.encryption_in_transit.client_broker',
      'encryption_in_transit_in_cluster' => 'encryption_info.encryption_in_transit.in_cluster',
      'logging_cloudwatch_enabled' => 'logging_info.broker_logs.cloud_watch_logs.enabled',
      'logging_firehose_enabled' => 'logging_info.broker_logs.firehose.enabled',
      'logging_s3_enabled' => 'logging_info.broker_logs.s3.enabled',
      'public_access_type' => 'broker_node_group_info.connectivity_info.public_access.type'
    },
    'gem' => 'aws-sdk-kafka',
    'id' => 'cluster_name',
    'list' => 'list_clusters',
    'scope' => 'regional'
  },
  'aws_network_acl' => {
    'client' => 'Aws::EC2::Client',
    'collection' => 'network_acls',
    'fields' => {
      'entries' => 'entries',
      'is_default' => 'is_default',
      'vpc_id' => 'vpc_id'
    },
    'gem' => 'aws-sdk-ec2',
    'id' => 'network_acl_id',
    'list' => 'describe_network_acls',
    'scope' => 'regional'
  },
  'aws_networkfirewall_firewall' => {
    'arn' => 'firewall_arn',
    'client' => 'Aws::NetworkFirewall::Client',
    'collection' => 'firewalls',
    'fields' => {},
    'gem' => 'aws-sdk-networkfirewall',
    'id' => 'firewall_name',
    'list' => 'list_firewalls'
  },
  'aws_rds_cluster' => {
    'arn' => 'db_cluster_arn',
    'client' => 'Aws::RDS::Client',
    'collection' => 'db_clusters',
    'fields' => {
      'engine' => 'engine',
      'storage_encrypted' => 'storage_encrypted'
    },
    'gem' => 'aws-sdk-rds',
    'id' => 'db_cluster_identifier',
    'list' => 'describe_db_clusters',
    'scope' => 'regional'
  },
  'aws_rds_global_cluster' => {
    'arn' => 'global_cluster_arn',
    'client' => 'Aws::RDS::Client',
    'collection' => 'global_clusters',
    'fields' => {
      'deletion_protection' => 'deletion_protection',
      'engine' => 'engine',
      'storage_encrypted' => 'storage_encrypted'
    },
    'gem' => 'aws-sdk-rds',
    'id' => 'global_cluster_identifier',
    'list' => 'describe_global_clusters',
    'scope' => 'regional'
  },
  'aws_redshift_parameter_group' => {
    'arg' => 'parameter_group_name',
    'client' => 'Aws::Redshift::Client',
    'collection' => '_response',
    'fields' => {
      'parameters' => 'parameters'
    },
    'gem' => 'aws-sdk-redshift',
    'id' => '_parent',
    'list' => 'describe_cluster_parameters',
    'parent' => {
      'collection' => 'parameter_groups',
      'id' => 'parameter_group_name',
      'list' => 'describe_cluster_parameter_groups'
    },
    'scope' => 'regional'
  },
  'aws_route53domains_registered_domain' => {
    'client' => 'Aws::Route53Domains::Client',
    'collection' => 'domains',
    'fields' => {
      'auto_renew' => 'auto_renew',
      'transfer_lock' => 'transfer_lock'
    },
    'gem' => 'aws-sdk-route53domains',
    'id' => 'domain_name',
    'list' => 'list_domains',
    'scope' => 'global'
  },
  'aws_secretsmanager_secret' => {
    'arn' => 'arn',
    'client' => 'Aws::SecretsManager::Client',
    'collection' => 'secret_list',
    'fields' => {
      'kms_key_id' => 'kms_key_id',
      'rotation_enabled' => 'rotation_enabled'
    },
    'gem' => 'aws-sdk-secretsmanager',
    'id' => 'name',
    'list' => 'list_secrets'
  },
  'aws_secretsmanager_secret_rotation' => {
    'arn' => 'arn',
    'client' => 'Aws::SecretsManager::Client',
    'collection' => 'secret_list',
    'fields' => {
      'rotation_enabled' => 'rotation_enabled',
      'rotation_interval_days' => 'rotation_rules.automatically_after_days'
    },
    'gem' => 'aws-sdk-secretsmanager',
    'id' => 'name',
    'list' => 'list_secrets'
  },
  'aws_security_group' => {
    'arn' => 'security_group_arn',
    'client' => 'Aws::EC2::Client',
    'collection' => 'security_groups',
    'fields' => {
      'ip_permissions' => 'ip_permissions',
      'ip_permissions_egress' => 'ip_permissions_egress'
    },
    'gem' => 'aws-sdk-ec2',
    'id' => 'group_id',
    'list' => 'describe_security_groups',
    'scope' => 'regional'
  },
  'aws_security_group_rule' => {
    'arn' => 'security_group_rule_arn',
    'client' => 'Aws::EC2::Client',
    'collection' => 'security_group_rules',
    'fields' => {
      'cidr_ipv_4' => 'cidr_ipv_4',
      'cidr_ipv_6' => 'cidr_ipv_6',
      'description' => 'description',
      'from_port' => 'from_port',
      'group_id' => 'group_id',
      'ip_protocol' => 'ip_protocol',
      'is_egress' => 'is_egress',
      'to_port' => 'to_port'
    },
    'gem' => 'aws-sdk-ec2',
    'id' => 'security_group_rule_id',
    'list' => 'describe_security_group_rules',
    'scope' => 'regional'
  },
  'aws_sfn_state_machine' => {
    'arn' => 'state_machine_arn',
    'client' => 'Aws::States::Client',
    'collection' => 'state_machines',
    'fields' => {
      'state_machine_type' => 'type'
    },
    'gem' => 'aws-sdk-states',
    'id' => 'name',
    'list' => 'list_state_machines'
  },
  'aws_sns_topic' => {
    'arn' => 'topic_arn',
    'client' => 'Aws::SNS::Client',
    'collection' => 'topics',
    'fields' => {},
    'gem' => 'aws-sdk-sns',
    'id' => 'topic_arn',
    'list' => 'list_topics'
  },
  'aws_transfer_server' => {
    'arn' => 'arn',
    'client' => 'Aws::Transfer::Client',
    'collection' => 'servers',
    'fields' => {
      'endpoint_type' => 'endpoint_type',
      'identity_provider_type' => 'identity_provider_type'
    },
    'gem' => 'aws-sdk-transfer',
    'id' => 'server_id',
    'list' => 'list_servers'
  },
  'aws_vpc_endpoint_service' => {
    'client' => 'Aws::EC2::Client',
    'collection' => 'service_configurations',
    'fields' => {
      'acceptance_required' => 'acceptance_required',
      'service_name' => 'service_name',
      'service_state' => 'service_state'
    },
    'gem' => 'aws-sdk-ec2',
    'id' => 'service_id',
    'list' => 'describe_vpc_endpoint_service_configurations'
  },
  'aws_workspaces_workspace' => {
    'client' => 'Aws::WorkSpaces::Client',
    'collection' => 'workspaces',
    'fields' => {
      'root_volume_encryption_enabled' => 'root_volume_encryption_enabled',
      'user_volume_encryption_enabled' => 'user_volume_encryption_enabled'
    },
    'gem' => 'aws-sdk-workspaces',
    'id' => 'workspace_id',
    'list' => 'describe_workspaces'
  },
}.freeze
