# Generated by tools/render_api_specs.py from tools/api_specs.yml.
# Do not edit by hand: the next render overwrites it.
#
# Enumeration specs for resource types inspec-aws does not ship. Read by
# libraries/aws_api_assets.rb; see tools/api_specs.yml for what each key means.
API_SPECS = {
  'aws_acm_certificate' => {
    'gem' => 'aws-sdk-acm',
    'client' => 'Aws::ACM::Client',
    'list' => 'list_certificates',
    'collection' => 'certificate_summary_list',
    'id' => 'domain_name',
    'arn' => 'certificate_arn',
    'fields' => {
      'key_algorithm' => 'key_algorithm',
      'in_use' => 'in_use'
    }
  },
  'aws_apprunner_service' => {
    'gem' => 'aws-sdk-apprunner',
    'client' => 'Aws::AppRunner::Client',
    'list' => 'list_services',
    'collection' => 'service_summary_list',
    'id' => 'service_name',
    'arn' => 'service_arn',
    'fields' => {}
  },
  'aws_athena_workgroup' => {
    'gem' => 'aws-sdk-athena',
    'client' => 'Aws::Athena::Client',
    'list' => 'list_work_groups',
    'collection' => 'work_groups',
    'id' => 'name',
    'fields' => {
      'state' => 'state'
    }
  },
  'aws_backup_vault' => {
    'gem' => 'aws-sdk-backup',
    'client' => 'Aws::Backup::Client',
    'list' => 'list_backup_vaults',
    'collection' => 'backup_vault_list',
    'id' => 'backup_vault_name',
    'arn' => 'backup_vault_arn',
    'fields' => {
      'encryption_key_arn' => 'encryption_key_arn'
    }
  },
  'aws_cloudwatch_log_group' => {
    'gem' => 'aws-sdk-cloudwatchlogs',
    'client' => 'Aws::CloudWatchLogs::Client',
    'list' => 'describe_log_groups',
    'collection' => 'log_groups',
    'id' => 'log_group_name',
    'arn' => 'arn',
    'fields' => {
      'kms_key_id' => 'kms_key_id',
      'retention_in_days' => 'retention_in_days'
    }
  },
  'aws_dms_replication_instance' => {
    'gem' => 'aws-sdk-databasemigrationservice',
    'client' => 'Aws::DatabaseMigrationService::Client',
    'list' => 'describe_replication_instances',
    'collection' => 'replication_instances',
    'id' => 'replication_instance_identifier',
    'arn' => 'replication_instance_arn',
    'fields' => {
      'publicly_accessible' => 'publicly_accessible',
      'auto_minor_version_upgrade' => 'auto_minor_version_upgrade',
      'multi_az' => 'multi_az'
    }
  },
  'aws_ecr_repository' => {
    'gem' => 'aws-sdk-ecr',
    'client' => 'Aws::ECR::Client',
    'list' => 'describe_repositories',
    'collection' => 'repositories',
    'id' => 'repository_name',
    'arn' => 'repository_arn',
    'fields' => {
      'scan_on_push' => 'image_scanning_configuration.scan_on_push',
      'image_tag_mutability' => 'image_tag_mutability',
      'encryption_type' => 'encryption_configuration.encryption_type',
      'kms_key' => 'encryption_configuration.kms_key'
    }
  },
  'aws_efs_file_system' => {
    'gem' => 'aws-sdk-efs',
    'client' => 'Aws::EFS::Client',
    'list' => 'describe_file_systems',
    'collection' => 'file_systems',
    'id' => 'file_system_id',
    'arn' => 'file_system_arn',
    'fields' => {
      'encrypted' => 'encrypted',
      'kms_key_id' => 'kms_key_id'
    }
  },
  'aws_elasticsearch_domain' => {
    'gem' => 'aws-sdk-elasticsearchservice',
    'client' => 'Aws::ElasticsearchService::Client',
    'list' => 'list_domain_names',
    'collection' => 'domain_names',
    'id' => 'domain_name',
    'fields' => {}
  },
  'aws_emr_cluster' => {
    'gem' => 'aws-sdk-emr',
    'client' => 'Aws::EMR::Client',
    'list' => 'list_clusters',
    'collection' => 'clusters',
    'id' => 'id',
    'arn' => 'cluster_arn',
    'fields' => {
      'status' => 'status.state'
    }
  },
  'aws_glue_crawler' => {
    'gem' => 'aws-sdk-glue',
    'client' => 'Aws::Glue::Client',
    'list' => 'get_crawlers',
    'collection' => 'crawlers',
    'id' => 'name',
    'fields' => {
      'security_configuration' => 'crawler_security_configuration'
    }
  },
  'aws_guardduty_detector' => {
    'gem' => 'aws-sdk-guardduty',
    'client' => 'Aws::GuardDuty::Client',
    'list' => 'list_detectors',
    'collection' => 'detector_ids',
    'id' => 'detector_ids',
    'fields' => {}
  },
  'aws_kinesis_stream' => {
    'gem' => 'aws-sdk-kinesis',
    'client' => 'Aws::Kinesis::Client',
    'list' => 'list_streams',
    'collection' => 'stream_summaries',
    'id' => 'stream_name',
    'arn' => 'stream_arn',
    'fields' => {
      'encryption_type' => 'stream_mode_details.stream_mode'
    }
  },
  'aws_lambda_function' => {
    'gem' => 'aws-sdk-lambda',
    'client' => 'Aws::Lambda::Client',
    'list' => 'list_functions',
    'collection' => 'functions',
    'id' => 'function_name',
    'arn' => 'function_arn',
    'fields' => {
      'tracing_mode' => 'tracing_config.mode',
      'kms_key_arn' => 'kms_key_arn',
      'runtime' => 'runtime',
      'vpc_subnet_ids' => 'vpc_config.subnet_ids',
      'code_signing_config_arn' => 'code_signing_config_arn'
    }
  },
  'aws_memorydb_cluster' => {
    'gem' => 'aws-sdk-memorydb',
    'client' => 'Aws::MemoryDB::Client',
    'list' => 'describe_clusters',
    'collection' => 'clusters',
    'id' => 'name',
    'arn' => 'arn',
    'fields' => {
      'tls_enabled' => 'tls_enabled',
      'kms_key_id' => 'kms_key_id',
      'snapshot_retention_limit' => 'snapshot_retention_limit'
    }
  },
  'aws_networkfirewall_firewall' => {
    'gem' => 'aws-sdk-networkfirewall',
    'client' => 'Aws::NetworkFirewall::Client',
    'list' => 'list_firewalls',
    'collection' => 'firewalls',
    'id' => 'firewall_name',
    'arn' => 'firewall_arn',
    'fields' => {}
  },
  'aws_secretsmanager_secret' => {
    'gem' => 'aws-sdk-secretsmanager',
    'client' => 'Aws::SecretsManager::Client',
    'list' => 'list_secrets',
    'collection' => 'secret_list',
    'id' => 'name',
    'arn' => 'arn',
    'fields' => {
      'kms_key_id' => 'kms_key_id',
      'rotation_enabled' => 'rotation_enabled'
    }
  },
  'aws_sfn_state_machine' => {
    'gem' => 'aws-sdk-states',
    'client' => 'Aws::States::Client',
    'list' => 'list_state_machines',
    'collection' => 'state_machines',
    'id' => 'name',
    'arn' => 'state_machine_arn',
    'fields' => {
      'type' => 'type'
    }
  },
  'aws_sns_topic' => {
    'gem' => 'aws-sdk-sns',
    'client' => 'Aws::SNS::Client',
    'list' => 'list_topics',
    'collection' => 'topics',
    'id' => 'topic_arn',
    'arn' => 'topic_arn',
    'fields' => {}
  },
  'aws_sqs_queue' => {
    'gem' => 'aws-sdk-sqs',
    'client' => 'Aws::SQS::Client',
    'list' => 'list_queues',
    'collection' => 'queue_urls',
    'id' => 'queue_urls',
    'fields' => {}
  },
  'aws_transfer_server' => {
    'gem' => 'aws-sdk-transfer',
    'client' => 'Aws::Transfer::Client',
    'list' => 'list_servers',
    'collection' => 'servers',
    'id' => 'server_id',
    'arn' => 'arn',
    'fields' => {
      'endpoint_type' => 'endpoint_type',
      'identity_provider_type' => 'identity_provider_type'
    }
  },
  'aws_workspaces_workspace' => {
    'gem' => 'aws-sdk-workspaces',
    'client' => 'Aws::WorkSpaces::Client',
    'list' => 'describe_workspaces',
    'collection' => 'workspaces',
    'id' => 'workspace_id',
    'fields' => {
      'root_volume_encryption_enabled' => 'root_volume_encryption_enabled',
      'user_volume_encryption_enabled' => 'user_volume_encryption_enabled'
    }
  },
}.freeze
