# Roll a conjunction of element conditions up over a collection-valued field.
#
# Why this exists
# ---------------
# The mapping schema extracts ONE scalar by dotted path and compares it once.
# That answers "is this asset's setting X", and it cannot answer "does this
# asset have an ELEMENT that looks like this" -- a security group rule opening
# 0.0.0.0/0 to 22, an ELB listener with no certificate, a task-definition volume
# with transit encryption off. A dotted path that crosses an array returns the
# array, and no matcher in tools/render_controls.py's matcher_for means anything
# against an array, so those checks were not merely unmapped: a mapping that
# tried would have compared an Array to a scalar and passed silently.
#
# What a control hands this
# -------------------------
# `conditions` is generated by tools/render_controls.py, never authored here.
# Each condition is:
#
#   { paths:       ['from_port'],            # where to look, inside the element
#     test:        ->(v) { v <= 22 },        # the comparison, one per satisfies verb
#     when_absent: true }                    # the verdict when nothing is reachable
#
# The verb vocabulary lives in Python, in render_controls.py, and arrives here
# already compiled to a lambda. That is deliberate: a Ruby-side table of the same
# thirteen verbs would be a second authority on what `at_most` means, and this
# repository has already been bitten once by exactly that duplication (see the
# note in render_stock about matcher_for drifting from its copy).
#
# Semantics, stated once
# ----------------------
#   * An ELEMENT matches when EVERY condition holds -- conditions are a
#     conjunction. A disjunction between two different comparisons is not
#     expressible and is not faked; use `paths` for the "same test, several
#     places" case, which is what the security-group v4/v6 pair and the MSK
#     three-log-destinations case both need.
#   * A CONDITION holds when SOME value reachable at ANY of its paths satisfies
#     the test. An array met PART-WAY through a path is fanned out by the next
#     segment, so `ip_ranges.cidr_ip` means "any of this rule's ranges", which is
#     the reading the checks want. There is no universal quantifier over a
#     sub-path. An array at the END of a path is delivered whole, so `empty` and
#     `not_empty` still mean what they say about the collection itself.
#   * A path that reaches NOTHING -- a member the API response omitted -- takes
#     the condition's `when_absent` verdict, default false. This is how an
#     omission is given its documented meaning: an EC2 IpPermission with
#     IpProtocol "-1" carries no FromPort or ToPort at all, and AWS means "every
#     port" by that, which is `when_absent: true` on both port conditions.
#
# Failure posture
# ---------------
# `none_of` and `all_of` are both vacuously TRUE over an empty collection. That
# is correct for one asset that genuinely has no elements and catastrophic when
# it is EVERY asset, because a field name this API does not return then produces
# a control that is structurally unable to fail -- which reads as 100% compliant.
# This module does NOT paper over that: it reports what it was given. The
# generated control carries a separate, control-scope expectation that at least
# one in-scope asset exposed the field, so the mapping bug is a visible failure
# rather than a clean pass.
#
# Reached by CONSTANT, never included into ::Inspec::Rule. A module included into
# Rule is available on the control and NOT inside a `subject`/`it` block, and the
# roll-up is called from inside a `satisfy` block, which is deferred into the
# example. `::CheckovCollection.none_of?` resolves in any scope; a bare helper
# would raise NameError at exec, which is the defect tools/lint_resource_scope.py
# exists to catch.
#
# `module ::CheckovCollection`, with the leading `::`, and every call site
# likewise. InSpec loads a library file through instance_eval on an anonymous
# eval context, so a bare `module CheckovCollection` defines the constant UNDER
# that anonymous class -- and the control, evaluated in a different one, then
# fails with
#
#     uninitialized constant #<Class:#<Inspec::ControlEvalContext>>::CheckovCollection
#
# at exec. `check` and `json` load control files without evaluating a body, so
# both pass on it; this was caught by running the rendered shape against
# `-t local://` with stubbed rows, and is the same hazard as the one that forces
# `::Inspec::Rule.include` in _checkov_exemptions.rb.
module ::CheckovCollection
  module_function

  # At least one element matches every condition.
  def any_of?(collection, conditions)
    elements(collection).any? { |element| matches?(element, conditions) }
  end

  # Every element matches every condition. Vacuously true over an empty
  # collection -- see the failure-posture note above.
  def all_of?(collection, conditions)
    elements(collection).all? { |element| matches?(element, conditions) }
  end

  # No element matches every condition. Vacuously true over an empty collection.
  def none_of?(collection, conditions)
    elements(collection).none? { |element| matches?(element, conditions) }
  end

  # The elements to roll up.
  #
  # nil is zero elements, not an error: an asset that does not express the field
  # is a real state. A scalar is one element, so a mapping that names a
  # non-collection field still judges it rather than silently walking nothing.
  # A Hash is ONE element, not its pairs -- `to_a` on a Hash yields [k, v]
  # arrays, which would turn a single object into a pile of two-element arrays
  # that match nothing and make `none_of` pass no matter what the object holds.
  def elements(collection)
    return [] if collection.nil?
    return collection if collection.is_a?(Array)

    [collection]
  end

  def matches?(element, conditions)
    Array(conditions).all? { |condition| condition_matches?(element, condition) }
  end

  def condition_matches?(element, condition)
    values = Array(condition[:paths]).flat_map { |path| dig_all(element, path) }
    return condition[:when_absent] == true if values.empty?

    values.any? { |value| condition[:test].call(value) }
  end

  # Every value reachable at a dotted path, fanning out across arrays.
  #
  # `[node]` is the seed rather than `node` so the first segment is applied
  # uniformly. An array reached by one segment sits in the frontier as a single
  # item; the NEXT segment's `step` recurses into it, which is what turns
  # `ip_ranges.cidr_ip` into every range's cidr. An array reached by the LAST
  # segment is never stepped into, so it arrives at the test whole.
  def dig_all(node, path)
    frontier = [node]
    path.to_s.split(".").each do |key|
      frontier = frontier.flat_map { |item| step(item, key) }
    end
    frontier.reject(&:nil?)
  end

  # One path segment. `false` is a value and must survive, so nil is tested for
  # explicitly rather than leaning on truthiness or on Array#compact ordering.
  def step(node, key)
    return node.flat_map { |item| step(item, key) } if node.is_a?(Array)
    return [] unless node.is_a?(Hash)

    value = node[key.to_sym]
    value = node[key] if value.nil?
    value.nil? ? [] : [value]
  end
end
