#!/usr/bin/env python3
"""Render controls/CKV_*.rb from the committed data files.

Why generated
-------------
There are 362 AWS checks. Hand-writing 362 control files means 362 chances to
drift from the rule each one claims to implement, and no way to tell which ones
did. Generating them means the drift is impossible by construction and the
review surface is four data files instead of 362 Ruby files.

    tools/checkov_catalog.yml    derived   what Checkov asserts, per resource type
    tools/resource_map.yml       authored  which deployed field answers it
    tools/control_metadata.yml   authored  compliance anchors, severity, rationale
    tools/fix_examples.yml       authored  remediation, per resource type

The generated file is committed so a reader of the repository sees the controls
without running anything, and `--check` fails when the two disagree.

Remediation is Terraform-first
------------------------------
An organisation that manages its estate through Terraform cannot act on an
`aws ec2 modify-...` command: running it either fails a policy gate or is
reverted by the next apply. So every control carries a complete Terraform block
for each resource type it applies to, and the CLI is the secondary path -- for an
estate not under Terraform, or for closing an exposure before the next apply.
Where there is no in-place fix at all, the control says so rather than implying
one exists.

Usage:
    python3 tools/render_controls.py            # rewrite controls/CKV_*.rb
    python3 tools/render_controls.py --check    # exit 1 if any is stale
"""
import argparse
import pathlib
import sys

import yaml

PROVIDER_DOCS = "https://registry.terraform.io/providers/hashicorp/aws/latest/docs"

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
CONTROLS = ROOT / "controls"

CATALOG = HERE / "checkov_catalog.yml"
RESOURCE_MAP = HERE / "resource_map.yml"
METADATA = HERE / "control_metadata.yml"
FIXES = HERE / "fix_examples.yml"

PROSE = {
    "aws_instance": "instances",
    "aws_launch_template": "launch templates",
    "aws_launch_configuration": "launch configurations",
}


PLANNED_TEMPLATE = """# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        {cid} (checkov {version})
# Applies to:  {types}
# Status:      PLANNED — no deployed-asset reader exists for {needs} yet.
#
# This control is present so the rule is accounted for. It asserts nothing, and
# it carries no NIST/CCI/KSI tags, because a compliance claim it cannot evaluate
# would be worse than an absent one.

control '{cid}' do
  impact 0.0
  title '{title}'

  desc <<~DESC
    Catalogued from Checkov {version}, not yet assessed here: no reader
    enumerates {needs} in this profile, so there is nothing to assert against.

    This is a gap, not a pass, and not a Not Applicable. tools/lint_catalog_drift.py
    counts it every run.
  DESC

  desc 'check', <<~CHECK
    Checkov looks for: {what}
  CHECK

  desc 'fix', <<~'FIX'
    See {docs}
  FIX

  tag checkov_id:            '{cid}'
  tag checkov_category:      '{cat}'
  tag checkov_version:       '{version}'
  tag checkov_kind:          '{kind}'
  tag tf_resources:          {types_rb}
  tag tf_docs:               '{docs}'
  tag implementation_status: 'planned'

  describe "{cid} — no deployed-asset reader for {needs}" do
    skip 'catalogued from Checkov, not yet implemented in this profile'
  end
end
"""


STOCK_TEMPLATE = """# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        {cid} (checkov {version})
# Applies to:  {tf_type}
# Read with:   {plural} -> {singular} (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {{}})['{cid}'] || []

control '{cid}' do
  title '{title}'

  desc <<~DESC
{desc}
  DESC

  desc 'rationale', <<~RATIONALE
{rationale}
  RATIONALE

  desc 'check', <<~CHECK
{what}
  CHECK

  desc 'fix', <<~'FIX'
{fix}
  FIX

  tag checkov_id:            '{cid}'
  tag checkov_category:      '{cat}'
  tag checkov_version:       '{version}'
  tag checkov_kind:          '{kind}'
  tag tf_resources:          {types_rb}
  tag tf_docs:               '{docs}'
  tag nist:                  {nist}
  tag nist_r4:               {nist_r4}
  tag cci:                   {cci}
  tag ksi:                   {ksi}
  tag severity:              '{sev}'
  tag severity_source:       'assessed'
  tag nist_source:           '{nist_source}'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  #
  # Every call carries aws_region: a stock resource otherwise reads only the
  # region the connection was built with, and every other region's resources
  # report as absent, which renders Not Applicable rather than unexamined.
{enumeration}

  # A plural resource whose table is built from the API response returns nil for
  # a column that does not exist, rather than raising. Passing that on gives
  # "`[:x]` must be provided" and kills the control. Blank ids are separated out
  # and asserted on below, so a wrong `ids` column is a visible failure rather
  # than a crash or a silent Not Applicable.
  unusable = found.count {{ |id, _r| "#{{id}}".strip.empty? }}
  found = found.reject {{ |id, _r| "#{{id}}".strip.empty? }}
  in_scope = found.reject {{ |id, _r| checkov_exempt?(id: id, type: '{tf_type}', rules: exempt) }}

  if unusable.positive?
    describe "{tf_type} enumeration" do
      it 'produced usable identifiers' do
        expect(unusable).to eq(0),
          "#{{unusable}} row(s) had a blank id — the `ids` column in resource_map.yml "\
          'likely names a field this resource does not expose'
      end
    end
  end

  # `unusable.positive?` keeps the control APPLICABLE when every id came back
  # blank. Without it only_if skips the control, and the wrong-column case this
  # guard exists to catch is exactly the case it would suppress — a Not
  # Applicable that means "the enumeration is broken".
  applicable = !in_scope.empty? || unusable.positive?
  impact {impact}
  impact 0.0 unless applicable
  only_if('no {tf_type} in scope') {{ applicable }}

  in_scope.each do |id, region|
    describe {singular}({arg_expr}) do
      its('{prop}') {{ {matcher} }}
    end
  end
end
"""


API_TEMPLATE = """# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        {cid} (checkov {version})
# Applies to:  {tf_type}
# Read with:   aws_api_assets (declarative spec, tools/api_specs.yml)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {{}})['{cid}'] || []

control '{cid}' do
  title '{title}'

  desc <<~DESC
{desc}
  DESC

  desc 'rationale', <<~RATIONALE
{rationale}
  RATIONALE

  desc 'check', <<~CHECK
{what}
  CHECK

  desc 'fix', <<~'FIX'
{fix}
  FIX

  tag checkov_id:            '{cid}'
  tag checkov_category:      '{cat}'
  tag checkov_version:       '{version}'
  tag checkov_kind:          '{kind}'
  tag tf_resources:          {types_rb}
  tag tf_docs:               '{docs}'
  tag nist:                  {nist}
  tag nist_r4:               {nist_r4}
  tag cci:                   {cci}
  tag ksi:                   {ksi}
  tag severity:              '{sev}'
  tag severity_source:       'assessed'
  tag nist_source:           '{nist_source}'
  tag implementation_status: 'implemented'

  assets = aws_api_assets(type: '{tf_type}', regions: scan_regions)

  # A region — or a whole service — that could not be READ is not the same as
  # one with nothing in it. A missing SDK gem, a denied call or an unreachable
  # endpoint all end up here, and without this assertion they render as "no
  # assets" and the control reports Not Applicable: the worst case reported as
  # "does not apply here".
  unreadable = assets.unreadable_regions
  unless unreadable.empty?
    describe "{tf_type} enumeration" do
      it 'read every region it attempted' do
        expect(unreadable.map {{ |r| "#{{r[:region]}}: #{{r[:error]}}" }}).to be_empty
      end
    end
  end

{nil_filter_comment}
  in_scope = assets.assets(exempt: exempt){nil_filter}

  # `!unreadable.empty?` keeps the control APPLICABLE when the enumeration could
  # not be read. Without it, the single case the guard above exists for — every
  # region denied, so ZERO rows AND an error — makes `in_scope` empty, only_if
  # skips the whole control, and the guard is skipped along with it: impact 0.0
  # and one skipped result, which HDF rolls up as Not Applicable. A guard that
  # only_if suppresses is not a guard, and this one was suppressed in exactly
  # the state it was written to catch.
  applicable = !in_scope.empty? || !unreadable.empty?
  impact {impact}
  impact 0.0 unless applicable
  only_if('no {tf_type} in scope expressing this setting') {{ applicable }}

  in_scope.each do |asset|
    describe "{tf_type} #{{asset[:id]}} (#{{asset[:account_id]}}/#{{asset[:region]}})" do
      subject {{ asset[:{field}] }}
      it {{ {matcher} }}
    end
  end
end
"""


MEMBERSHIP_TEMPLATE = '''# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        {cid} (checkov {version})
# Applies to:  {tf_type}
# Read with:   a MEMBERSHIP join — two independent enumerations matched by key
#                left  {left_type}  keyed on {left_key} ({left_key_form})
#                right {right_type} keyed on {right_key} ({right_key_form})
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {{}})['{cid}'] || []

control '{cid}' do
  title '{title}'

  desc <<~DESC
{desc}
  DESC

  desc 'rationale', <<~RATIONALE
{rationale}
  RATIONALE

  desc 'check', <<~CHECK
{what}
  CHECK

  desc 'fix', <<~'FIX'
{fix}
  FIX

  tag checkov_id:            '{cid}'
  tag checkov_category:      '{cat}'
  tag checkov_version:       '{version}'
  tag checkov_kind:          '{kind}'
  tag tf_resources:          {types_rb}
  tag tf_docs:               '{docs}'
  tag nist:                  {nist}
  tag nist_r4:               {nist_r4}
  tag cci:                   {cci}
  tag ksi:                   {ksi}
  tag severity:              '{sev}'
  tag severity_source:       'assessed'
  tag nist_source:           '{nist_source}'
  tag implementation_status: 'implemented'

  # Two independent enumerations, both resolved at CONTROL scope. What makes
  # this a join rather than the per-id lookup the stock shape already does is
  # that the right side cannot be fetched BY a left asset's id: it has to be
  # enumerated wholesale and matched.
  left_side  = aws_api_assets(type: '{left_type}', regions: scan_regions)
  right_side = aws_api_assets(type: '{right_type}', regions: scan_regions)

  # A region that could not be READ is not a region with nothing in it, and here
  # that cuts both ways. An unread RIGHT side makes every left asset look
  # uncovered — a 100% finding manufactured out of an API error — so both sides
  # are asserted, and `applicable` below keeps this visible even when the left
  # side came back empty because it was the side that failed.
  unreadable = left_side.unreadable_regions.map {{ |r| "{left_type} #{{r[:region]}}: #{{r[:error]}}" }} +
               right_side.unreadable_regions.map {{ |r| "{right_type} #{{r[:region]}}: #{{r[:error]}}" }}

  unless unreadable.empty?
    describe '{cid} join enumeration' do
      it 'read every region it attempted, on both sides of the join' do
        expect(unreadable).to be_empty
      end
    end
  end

  left_rows = left_side.assets(exempt: exempt)
  right_all = right_side.assets
{right_filter}
  # Keys are built through one shared reducer for both sides, so the two cannot
  # drift into disagreeing about what a key is. A row that cannot be keyed is
  # COUNTED, not dropped: dropping it would remove exactly the population that
  # would have failed and render the control Not Applicable.
  keyed     = left_rows.map do |row|
    [row, checkov_membership_key(row, field: :{left_key}, key_form: '{left_key_form}', match_region: {match_region})]
  end
  unkeyable = keyed.count {{ |_row, key| key.nil? }}
  in_scope  = keyed.reject {{ |_row, key| key.nil? }}

  right_keys   = checkov_membership_keys(right_rows, field: :{right_key},
                                         key_form: '{right_key_form}', match_region: {match_region})
  matched      = in_scope.map {{ |row, key| [row, right_keys.key?(key)] }}
  covered      = matched.count {{ |_row, hit| hit }}
  left_sample  = checkov_membership_sample(in_scope.map {{ |_row, key| key }})
  right_sample = checkov_membership_sample(right_keys.keys)

  if unkeyable.positive?
    describe '{left_type} enumeration' do
      it 'produced a usable key for every row' do
        expect(unkeyable).to eq(0),
          "#{{unkeyable}} of #{{left_rows.length}} row(s) had no usable `{left_key}` — the key "\\
          'named in resource_map.yml is likely a field this spec does not carry, and every '\\
          'such row is unjudgeable rather than compliant'
      end
    end
  end
{filter_guard}
  # The join is only as good as the two key spaces lining up. Zero matches has
  # two readings and they are NOT equally likely: a broken join reports every
  # asset as uncovered, which is indistinguishable in the results from a real
  # total finding. So it is called out as its own failing example, with a sample
  # of each side's keys, rather than left to be inferred from {left_noun_plural}
  # all failing at once.
  if !in_scope.empty? && !right_rows.empty? && covered.zero?
    describe '{cid} join key spaces' do
      it 'matched at least one {left_noun} to the {right_noun} population' do
        expect(covered).to be > 0,
          "none of the #{{in_scope.length}} {left_noun_plural} matched any of the "\\
          "#{{right_keys.length}} {right_noun} key(s). Either nothing here is covered, or the "\\
          'two sides are keyed in different identifier spaces and this join is broken. '\\
          "left keys look like #{{left_sample.inspect}}; right keys look like "\\
          "#{{right_sample.inspect}}, as region/key. If those are not the same kind "\\
          'of string, the join is broken.'{region_reading}
      end
    end
  end

  # Not Applicable only when there are genuinely no {left_noun_plural} to cover.
  # An EMPTY RIGHT SIDE is deliberately NOT part of this test:
{empty_right_comment}
  # `unkeyable` and `unreadable` are in here for the same reason as in the stock
  # shape — a guard that only_if suppresses is not a guard.
  applicable = !in_scope.empty? || unkeyable.positive? || !unreadable.empty?
  impact {impact}
  impact 0.0 unless applicable
  only_if('no {left_noun_plural} in scope') {{ applicable }}

  matched.each do |row, hit|
    describe "{left_type} #{{row[:id]}} (#{{row[:account_id]}}/#{{row[:region]}})" do
      it 'is covered by {right_article} {right_noun}' do
        expect(hit).to eq(true), '{uncovered_message}'
      end
    end
  end
end
'''


SINGLETON_TEMPLATE = """# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        {cid} (checkov {version})
# Applies to:  {tf_type}
# Read with:   {resource} — an account-level singleton, so there is nothing to enumerate
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

control '{cid}' do
  title '{title}'

  desc <<~DESC
{desc}
  DESC

  desc 'rationale', <<~RATIONALE
{rationale}
  RATIONALE

  desc 'check', <<~CHECK
{what}
  CHECK

  desc 'fix', <<~'FIX'
{fix}
  FIX

  tag checkov_id:            '{cid}'
  tag checkov_category:      '{cat}'
  tag checkov_version:       '{version}'
  tag checkov_kind:          '{kind}'
  tag tf_resources:          {types_rb}
  tag tf_docs:               '{docs}'
  tag nist:                  {nist}
  tag nist_r4:               {nist_r4}
  tag cci:                   {cci}
  tag ksi:                   {ksi}
  tag severity:              '{sev}'
  tag severity_source:       'assessed'
  tag nist_source:           '{nist_source}'
  tag implementation_status: 'implemented'

  subject_resource = {resource}

  # Always applicable. An account with no policy at all is the NON-COMPLIANT
  # state for this rule, not an inapplicable one — rendering it Not Applicable
  # would report the worst case as "does not apply here".
  impact {impact}

  describe '{tf_type}' do
    it 'is configured for this account' do
      expect(subject_resource.exists?).to eq(true),
        'no account-level policy is set, so nothing constrains this'
    end
  end
{guard_block}
  if {guard_condition}
    describe subject_resource do
      its('{prop}') {{ {matcher} }}
    end
  end
end
"""


def load():
    """Reviewed data first, derived data second — and an authored entry always wins.

    The two are separate files on purpose. A derived mapping asserts on a property
    name taken from the Terraform argument, and a derived anchor is a family-level
    claim from the check's category. Merging them into the authored files would
    erase the only signal a reader has for which is which.
    """
    catalog = yaml.safe_load(CATALOG.read_text())
    resource_map = yaml.safe_load(RESOURCE_MAP.read_text())["checks"]
    metadata = yaml.safe_load(METADATA.read_text())

    derived_map = HERE / "resource_map_derived.yml"
    if derived_map.is_file():
        for cid, spec in (yaml.safe_load(derived_map.read_text()) or {}).get("checks", {}).items():
            resource_map.setdefault(cid, spec)
    derived_meta = HERE / "control_metadata_derived.yml"
    if derived_meta.is_file():
        for cid, meta in (yaml.safe_load(derived_meta.read_text()) or {}).items():
            metadata.setdefault(cid, meta)

    return (catalog["_source"]["version"], catalog["checks"], resource_map, metadata,
            yaml.safe_load(FIXES.read_text()))


def block(text, indent):
    """Re-indent an authored block for the heredoc it lands in."""
    pad = " " * indent
    lines = [l.rstrip() for l in str(text).strip("\n").split("\n")]
    return "\n".join(pad + l if l else "" for l in lines)


def wrap(text, indent, width=76):
    pad = " " * indent
    words, lines, cur = str(text).split(), [], pad
    for w in words:
        if len(cur) + len(w) + 1 > width and cur.strip():
            lines.append(cur.rstrip())
            cur = pad + w
        else:
            cur = f"{cur}{'' if cur == pad else ' '}{w}"
    if cur.strip():
        lines.append(cur.rstrip())
    return "\n".join(lines)


def check_prose(entry, meta):
    """What Checkov looks for, derived where the catalogue can say it."""
    if meta.get("what"):
        return meta["what"]
    kinds = []
    for res in entry["resources"]:
        key = entry["inspected_key"].get(res) or ""
        if not key:
            continue
        if entry.get("expected"):
            kinds.append(f"{res}: {key} is {' or '.join(entry['expected'])}")
        elif entry.get("forbidden"):
            kinds.append(f"{res}: {key} is not {' or '.join(entry['forbidden'])}")
    return "; ".join(kinds) or entry["name"]


def render_fix(cid, entry, fixes):
    """Terraform per resource type, then the out-of-band path, then caveats."""
    out = []
    per_type = fixes.get(cid, {})
    for res in entry["resources"]:
        example = per_type.get(res)
        if not example:
            continue
        out.append(f"Terraform — {res}:")
        out.append("")
        out.append(block(example["terraform"], 2))
        out.append("")
        if example.get("cli"):
            out.append(f"Out of band — {res}:")
            out.append("")
            out.append(block(example["cli"], 2))
            out.append("")
        if example.get("note"):
            out.append(wrap(f"Note ({res}): {example['note']}", 0))
            out.append("")
    if not out:
        out = [f"See {list(entry['tf_docs'].values())[0]}"]
    return "\n".join(l for l in out).rstrip()


def render(cid, version, entry, mapping, meta, fixes):
    types = [r for r in entry["resources"] if r in mapping]
    fields = {mapping[r]["field"] for r in types}
    if len(fields) != 1:
        raise SystemExit(f"{cid}: resource_map must use one field per check, got {fields}")
    field = fields.pop()
    satisfies = {mapping[r]["satisfies"] for r in types}.pop()
    assertion = {"empty": "be_empty", "equals": None}[satisfies]
    if assertion is None:
        value = mapping[types[0]].get("value")
        assertion = f"be {str(value).lower()}"

    names = [PROSE.get(t, t) for t in types]
    prose = names[0] if len(names) == 1 else ", ".join(names[:-1]) + " and " + names[-1]
    types_rb = "%w[" + " ".join(types) + "]"

    # f-string template below, so these must be locals rather than format args.
    nist_source = meta.get("nist_source", "reviewed")
    nil_filter, nil_filter_comment = nil_filter_for(satisfies, field)

    stronger = ""
    if meta.get("stronger"):
        stronger = "\n\n" + wrap(meta["stronger"], 4)

    return f'''# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        {cid} (checkov {version})
# Applies to:  {", ".join(types)}
# Answered by: aws_compute_assets#{field}
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {{}})['{cid}'] || []
applies_to   = {types_rb}

control '{cid}' do
  title '{ruby_quoted_body(entry["name"].rstrip("."))}'

  desc <<~DESC
{wrap(f"Checkov asserts this against Terraform. This profile asserts it against the {prose} that actually exist.", 4)}{stronger}
  DESC

  desc 'rationale', <<~RATIONALE
{wrap(meta["rationale"], 4)}
  RATIONALE

  desc 'check', <<~CHECK
{wrap("Checkov looks for: " + check_prose(entry, meta), 4)}
  CHECK

  desc 'fix', <<~'FIX'
{block(render_fix(cid, entry, fixes), 4)}
  FIX

  tag checkov_id:       '{cid}'
  tag checkov_category: '{"/".join(entry["categories"])}'
  tag checkov_version:  '{version}'
  tag checkov_kind:     '{entry["kind"]}'
  tag tf_resources:     {types_rb}
  tag tf_argument:      '{entry["inspected_key"].get(types[0]) or "(custom check logic)"}'
  tag tf_docs:          '{entry["tf_docs"][types[0]]}'
  tag nist:             {meta["nist"]}
  tag nist_r4:          {meta["nist_r4"]}
  tag cci:              {meta["cci"]}
  tag ksi:              {meta["ksi"]}
  tag severity:         '{meta["severity"]}'
  tag severity_source:  'assessed'
  tag nist_source:      '{nist_source}'
  tag implementation_status: 'implemented'

  assets = aws_compute_assets(regions: scan_regions)

  # Only the asset types this check declares, only what the boundary has, and
  # only those that express the setting at all — a launch template has no
  # ebs_optimized, and nil must not read as a passing false.
{nil_filter_comment}
  in_scope = assets.assets_of(applies_to, exempt: exempt){nil_filter}

  applicable = !in_scope.empty?

  # Two statements, not a ternary: InSpec's AST impact collector calls `.value`
  # on the argument node, and a ternary is an IfNode with none — it aborts
  # `check` for the whole profile before a single control runs.
  impact {meta["impact"]}
  impact 0.0 unless applicable

  only_if("no #{{applies_to.join(', ')}} in scope expressing this setting") {{ applicable }}

  in_scope.each do |asset|
    describe "#{{asset[:type]}} #{{asset[:id]}} (#{{asset[:account_id]}}/#{{asset[:region]}})" do
      subject {{ asset[:{field}] }}
      it {{ should {assertion} }}
    end
  end
end
'''


def render_stock(cid, version, entry, mapping, meta, fixes):
    """A control that reads a stock inspec-aws resource, with no custom library.

    Roughly a third of Checkov's AWS checks land on a resource type inspec-aws
    already enumerates. Writing a bespoke reader for those would be duplicating
    a maintained resource pack in order to answer the same question slightly
    differently.
    """
    tf_type = next(iter(mapping))
    spec = mapping[tf_type]
    enum, assertion = spec["enumerate"], spec["assert"]
    # One matcher implementation, shared with render_api. This block used to be a
    # duplicate of it and drifted: the shared one learned to quote strings, this
    # one did not, so a stock mapping with a string value would still render a
    # bare lowercased identifier — a NameError that reads as a finding.
    satisfies = assertion.get("satisfies", "equals")
    matcher = matcher_for(cid, satisfies, assertion.get("value"))

    return STOCK_TEMPLATE.format(
        cid=cid, version=version, tf_type=tf_type,
        title=ruby_quoted_body(entry["name"].rstrip(".")),
        desc=wrap(f"Checkov asserts this against Terraform. This profile asserts it against "
                  f"the {tf_type} resources that actually exist, read through the stock "
                  f"inspec-aws {assertion['resource']} resource.", 4),
        rationale=wrap(meta["rationale"], 4),
        what=wrap("Checkov looks for: " + check_prose(entry, meta), 4),
        fix=block(render_fix(cid, entry, fixes), 4),
        cat="/".join(entry["categories"]) or "GRAPH",
        kind=entry["kind"],
        types_rb="%w[" + " ".join(t for t in entry["resources"] if t.startswith("aws_")) + "]",
        docs=entry["tf_docs"].get(tf_type, PROVIDER_DOCS),
        nist=meta["nist"], nist_r4=meta["nist_r4"], cci=meta["cci"], ksi=meta["ksi"],
        sev=meta["severity"], impact=meta["impact"],
        nist_source=meta.get("nist_source", "reviewed"),
        plural=enum["resource"], ids_column=enum["ids"],
        enumeration=enumeration_for(spec, enum),
        singular=assertion["resource"],
        arg_expr=(("id, aws_region: region" if spec.get("scope") != "global" else "id")
                  if assertion.get("arg") in (None, "", "positional")
                  else (f"{assertion['arg']}: id, aws_region: region"
                        if spec.get("scope") != "global"
                        else f"{assertion['arg']}: id")),
        prop=assertion["property"], matcher=matcher)


def ruby_single_quoted(text):
    """A Python string as a Ruby single-quoted literal, escaped correctly.

    `"'" + s.replace("'", "''")` is the SQL escape, and Ruby does not read it.
    Ruby juxtaposes adjacent string literals, so `'a''b'` lexes as `'a'` `'b'`
    and evaluates to "ab" — the apostrophe is DELETED, silently, with no syntax
    error to notice. Eleven control titles were rendering that way:
    "a statement''s actions" reached HDF as "a statements actions", and
    "has ''restrict_public_buckets'' enabled" lost both quotes.

    Cosmetic in a title; not cosmetic in a comparison value, where a silently
    different string is compared against the API and the control passes or fails
    on the wrong answer with nothing to show for it.

    Backslash first, or it would then escape the backslashes this adds.
    tools/render_api_specs.py already escapes this way; this is the same rule.
    """
    return "'" + ruby_quoted_body(text) + "'"


def ruby_quoted_body(text):
    """The inside of a Ruby single-quoted string, for the templates that already
    write the surrounding quotes themselves. Same escaping rule as
    ruby_single_quoted; see the note there for why `''` is not it."""
    return str(text).replace("\\", "\\\\").replace("'", "\\'")


def ruby_literal(value):
    """A value as Ruby source.

    `str(value).lower()` was wrong for anything but a boolean: an expected value
    of "IMMUTABLE" rendered as the bare word `immutable`, which is a NameError at
    exec and reports as a FAILED control rather than an errored one — a broken
    control that reads as a finding.
    """
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return ruby_single_quoted(value)


def enumeration_for(spec, enum):
    """How a stock control enumerates its assets.

    Global services — S3, IAM, CloudFront, Route 53 — return the same objects
    from any region, so walking regions would assess every bucket once per
    region and multiply both the API calls and the results. They are enumerated
    once, with no `aws_region:` at all: passing a placeholder would hand the SDK
    a region that does not exist.
    """
    if spec.get("scope") == "global":
        return (f"  # Global service: the same objects come back from any region, so this is\n"
                f"  # enumerated once rather than once per region.\n"
                f"  found = {enum['resource']}.{enum['ids']}.to_a.map {{ |id| [id, nil] }}")
    return (f"  found = checkov_scan_regions(scan_regions).flat_map do |region|\n"
            f"    {enum['resource']}(aws_region: region).{enum['ids']}.to_a"
            f".map {{ |id| [id, region] }}\n"
            f"  end")


def nil_filter_for(satisfies, field):
    """Whether a nil field means "out of scope" or "this is the failure".

    For a value comparison, a field the API did not return means the asset does
    not express the setting: out of scope, not in breach. For a PRESENCE check
    (`not_empty`), nil is precisely the failing state, and filtering it first
    made the control structurally unfailable — it silently rendered Not
    Applicable for every asset that should have failed.
    """
    if satisfies in ("not_empty", "empty"):
        return ("", "  # A nil field is the FAILING state for a presence check, so it is\n"
                    "  # deliberately not filtered out here.")
    return (f"\n                   .reject {{ |a| a[:{field}].nil? }}",
            "  # A field the API did not return is nil, and nil is not a failing value:\n"
            "  # the asset does not express this setting, so it is out of scope for this\n"
            "  # check rather than in breach of it.")


def matcher_for(cid, satisfies, value):
    """The RSpec matcher a `satisfies` maps to, shared by the stock and API shapes."""
    if satisfies == "equals":
        return f"should eq {ruby_literal(value)}"
    if satisfies == "not_empty":
        # "is set" — nil and an empty string/array all fail. `should_not be_empty`
        # alone raises on nil, and filtering nil out beforehand removes exactly the
        # population that fails.
        return ("should satisfy('be set') { |v| "
                "!v.nil? && !(v.respond_to?(:empty?) && v.empty?) }")
    if satisfies == "empty":
        return ("should satisfy('be unset or empty') { |v| "
                "v.nil? || (v.respond_to?(:empty?) && v.empty?) }")
    if satisfies == "greater_than":
        return f"should be > {value}"
    if satisfies == "in_list":
        return "should be_in [" + ", ".join(ruby_literal(v) for v in value) + "]"
    if satisfies == "not_equals":
        return f"should_not eq {ruby_literal(value)}"
    if satisfies == "not_in_list":
        return "should_not be_in [" + ", ".join(ruby_literal(v) for v in value) + "]"
    if satisfies == "at_least":
        # `greater_than` is strict, so a policy demanding "at least 14" failed on
        # exactly 14 — the boundary the requirement names.
        return f"should be >= {value}"
    if satisfies == "at_most":
        return f"should be <= {value}"
    if satisfies == "less_than":
        return f"should be < {value}"
    if satisfies == "includes":
        return f"should include {ruby_literal(value)}"
    if satisfies == "excludes":
        return f"should_not include {ruby_literal(value)}"
    if satisfies == "matches":
        return f"should match(/{value}/)"
    raise SystemExit(f"{cid}: unknown satisfies '{satisfies}'")


def render_api(cid, version, entry, mapping, meta, fixes):
    """A control reading a type described in tools/api_specs.yml."""
    tf_type = next(iter(mapping))
    spec = mapping[tf_type]
    return API_TEMPLATE.format(
        cid=cid, version=version, tf_type=tf_type,
        title=ruby_quoted_body(entry["name"].rstrip(".")),
        desc=wrap(f"Checkov asserts this against Terraform. This profile asserts it against "
                  f"the {tf_type} resources that actually exist, enumerated through the "
                  f"declarative API spec.", 4),
        rationale=wrap(meta["rationale"], 4),
        what=wrap("Checkov looks for: " + check_prose(entry, meta), 4),
        fix=block(render_fix(cid, entry, fixes), 4),
        cat="/".join(entry["categories"]) or "GRAPH", kind=entry["kind"],
        types_rb="%w[" + " ".join(t for t in entry["resources"] if t.startswith("aws_")) + "]",
        docs=entry["tf_docs"].get(tf_type, PROVIDER_DOCS),
        nist=meta["nist"], nist_r4=meta["nist_r4"], cci=meta["cci"], ksi=meta["ksi"],
        sev=meta["severity"], impact=meta["impact"],
        nist_source=meta.get("nist_source", "reviewed"),
        field=spec["field"],
        nil_filter=nil_filter_for(spec.get("satisfies", "equals"), spec["field"])[0],
        nil_filter_comment=nil_filter_for(spec.get("satisfies", "equals"), spec["field"])[1],
        matcher=matcher_for(cid, spec.get("satisfies", "equals"), spec.get("value")))


MEMBERSHIP_KEY_FORMS = ("verbatim", "terminal_segment")
MEMBERSHIP_ASSERTIONS = ("every_left_covered",)


def comment_block(text, indent=2, width=76):
    """Prose as a wrapped Ruby comment."""
    pad = " " * indent
    return "\n".join(f"{pad}# {line.strip()}"
                     for line in wrap(text, 0, width - indent - 2).split("\n"))


def membership_side(cid, side, spec):
    """One declared side of a join, validated.

    Every field is validated here rather than at exec, because every way of
    getting one wrong produces the same silent result: no key matches, every
    left asset reports uncovered, and the control renders a 100% finding that
    nobody can tell from a real one.
    """
    for required in ("type", "key", "key_form", "noun"):
        if not spec.get(required):
            raise SystemExit(f"{cid}: membership {side} side must declare `{required}`")
    if spec["key_form"] not in MEMBERSHIP_KEY_FORMS:
        raise SystemExit(f"{cid}: membership {side} key_form '{spec['key_form']}' is not one of "
                         f"{', '.join(MEMBERSHIP_KEY_FORMS)}")
    # Whether `key` actually EXISTS on that api spec is checked against
    # tools/api_specs.yml by tools/lint_resource_map.py: `id` and `arn` are the
    # two columns aws_api_assets writes on every row, anything else must be a
    # declared field. Getting it wrong yields nil keys and therefore no matches,
    # which is the failure this whole shape is built to make visible.
    return spec


def render_membership(cid, version, entry, mapping, meta, fixes):
    """A control that asks "is every X covered by some Y".

    The shape the other four readers cannot express. `stock` and `api` both
    answer a question about ONE asset -- read a field, compare it to a value --
    and `enumerate`/`assert` being independent already covers "look Y up BY X's
    id". Coverage is different: AWS Backup has no per-volume call that says
    whether a volume is protected. The answer only exists as a second
    enumeration that has to be matched against the first.

    What makes this dangerous enough to need its own validation is that the two
    sides usually speak different identifier spaces -- a bare `vol-0abc` on one
    side and `arn:aws:ec2:...:volume/vol-0abc` on the other. Matching those
    without a declared reduction matches nothing, and "nothing matched" renders
    as every asset failing: a total finding indistinguishable from a real one,
    and invisible to `check` and to `json`, neither of which evaluates a body.

    So the mapping DECLARES how each side is keyed, the rendered control reduces
    both sides through one shared helper, and it carries a guard that fails when
    the two key spaces do not intersect at all.
    """
    tf_type = next(iter(mapping))
    spec = mapping[tf_type]

    assertion = spec.get("assert")
    if assertion not in MEMBERSHIP_ASSERTIONS:
        raise SystemExit(f"{cid}: membership `assert` must be one of "
                         f"{', '.join(MEMBERSHIP_ASSERTIONS)}, got {assertion!r}")

    left = membership_side(cid, "left", spec.get("left") or {})
    right = membership_side(cid, "right", spec.get("right") or {})

    # Required, not optional. An empty right side is the one reading a data
    # author is most likely to get wrong -- "no backup plans at all" is the
    # WORST case, not an absence of evidence -- so the mapping has to say what
    # it means before the control will render.
    if not spec.get("empty_right_means"):
        raise SystemExit(
            f"{cid}: membership mapping must declare `empty_right_means`. An empty right side "
            f"is a real finding, not a Not Applicable, and the control has to say so in words.")

    where = right.get("where") or {}
    if len(where) > 1:
        raise SystemExit(f"{cid}: membership right.where takes exactly one field; "
                         f"got {sorted(where)}. More than one and the guard below cannot say "
                         f"which of them selected nothing.")

    match_region = "true" if spec.get("match_region", True) else "false"
    # A third reading of "nothing matched" that only exists when the join pairs
    # on region, and one the key samples alone do not reveal: the identifiers
    # can be identical and still not match because they were read in different
    # regions. Named in the message rather than left for a reader to rediscover.
    region_reading = ""
    if match_region == "true":
        region_reading = (
            "\\\n          ' If they ARE the same kind of string, compare the region "
            "halves: '\\\n          'this join pairs on region, so an asset covered from "
            "a different region '\\\n          'reads as uncovered here.'")

    left_noun = left["noun"]
    left_noun_plural = left.get("noun_plural") or f"{left_noun}s"
    right_noun = right["noun"]
    right_article = "an" if right_noun[:1].lower() in "aeiou" else "a"

    if where:
        field, values = next(iter(where.items()))
        values_rb = "[" + ", ".join(ruby_literal(v) for v in (
            values if isinstance(values, list) else [values])) + "]"
        right_filter = (
            f"\n  # The right side answers for every resource type in the account at once, so\n"
            f"  # it is narrowed BEFORE any key is built: a coverage question about "
            f"{left_noun_plural}\n"
            f"  # must not be satisfied by some other resource type that happens to reduce to\n"
            f"  # the same key.\n"
            f"  right_rows = checkov_membership_where(right_all, {{ {field}: {values_rb} }})\n"
            f"  observed   = checkov_membership_observed(right_all, :{field})\n")
        filter_guard = (
            f"\n  # `{field}` is a service string, and the SDK declares it as a plain string\n"
            f"  # rather than an enum, so a mis-spelled filter value cannot be caught\n"
            f"  # statically. A wrong one empties the right side, which then reads as \"nothing\n"
            f"  # is covered\" — the same result as the genuine finding. This example does not\n"
            f"  # decide which of the two it is; it prints what the API actually returned so a\n"
            f"  # reader can, and it fails either way, because both readings are failures.\n"
            f"  if right_rows.empty? && !right_all.empty?\n"
            f"    describe '{right['type']} filter' do\n"
            f"      it 'selected at least one row of the declared {field}' do\n"
            f"        expect(right_rows.length).to be > 0,\n"
            f"          \"the mapping filters {right['type']} to {field} {values_rb}, and none of \"\\\n"
            f"          \"the #{{right_all.length}} row(s) returned matched. The API returned \"\\\n"
            f"          \"{field}: #{{observed.inspect}}. If that list plainly contains the same \"\\\n"
            f"          'value in a different spelling, the mapping is wrong; if it does not, '\\\n"
            f"          'nothing of this type is covered, which is the finding.'\n"
            f"      end\n"
            f"    end\n"
            f"  end\n")
    else:
        right_filter = (
            f"\n  # No filter declared: every row the right side returns is a candidate.\n"
            f"  right_rows = right_all\n")
        filter_guard = ""

    divergence = spec.get("divergence")
    desc_parts = [
        f"Checkov asserts this against Terraform. This profile asserts it against the "
        f"{left_noun_plural} that actually exist, by enumerating them and the "
        f"{right_noun} population separately and matching the two by key.",
        f"How the join is keyed, because a join whose keys never match reports every "
        f"asset as uncovered and looks exactly like a real total finding: the left side "
        f"is keyed on {left['type']}.{left['key']} ({left['key_form']}), the right side on "
        f"{right['type']}.{right['key']} ({right['key_form']}), and "
        + ("both keys carry the region they were read from, so a resource in one region "
           "cannot be covered by an entry in another."
           if match_region == "true" else
           "region is not part of the key."),
        f"An empty right side is a FINDING, not an absence of evidence: "
        f"{spec['empty_right_means']}",
        "A region that could not be read on either side is asserted as its own failing "
        "example rather than being flattened into \"found nothing\" — an unread right side "
        "would otherwise report every asset here as uncovered.",
    ]
    if divergence:
        desc_parts.insert(1, f"DIVERGENCE from Checkov: {divergence}")
    if meta.get("stronger"):
        desc_parts.append(meta["stronger"])
    desc = "\n\n".join(wrap(p, 4) for p in desc_parts)

    uncovered = spec.get("uncovered_message") or (
        f"no {right_noun} matches this {left_noun}")

    return MEMBERSHIP_TEMPLATE.format(
        cid=cid, version=version, tf_type=tf_type,
        title=ruby_quoted_body(entry["name"].rstrip(".")),
        desc=desc,
        rationale=wrap(meta["rationale"], 4),
        what=wrap("Checkov looks for: " + check_prose(entry, meta), 4),
        fix=block(render_fix(cid, entry, fixes), 4),
        cat="/".join(entry["categories"]) or "GRAPH", kind=entry["kind"],
        types_rb="%w[" + " ".join(t for t in entry["resources"] if t.startswith("aws_")) + "]",
        docs=entry["tf_docs"].get(tf_type, PROVIDER_DOCS),
        nist=meta["nist"], nist_r4=meta["nist_r4"], cci=meta["cci"], ksi=meta["ksi"],
        sev=meta["severity"], impact=meta["impact"],
        nist_source=meta.get("nist_source", "reviewed"),
        left_type=left["type"], left_key=left["key"], left_key_form=left["key_form"],
        right_type=right["type"], right_key=right["key"], right_key_form=right["key_form"],
        left_noun=left_noun, left_noun_plural=left_noun_plural,
        right_noun=right_noun, right_article=right_article,
        match_region=match_region, region_reading=region_reading,
        right_filter=right_filter, filter_guard=filter_guard,
        empty_right_comment=comment_block(spec["empty_right_means"]),
        uncovered_message=ruby_quoted_body(uncovered))


def render_singleton(cid, version, entry, mapping, meta, fixes):
    """A control for an account-level singleton: one object, nothing to enumerate.

    The IAM account password policy is the case that forced this. It has no
    plural because the API returns one object per account, and two of its
    readers RAISE rather than return nil when the corresponding feature is off:
    `max_password_age_in_days` raises unless `expire_passwords?`. So a guard is
    declared, asserted as its own expectation — because "passwords never expire"
    is itself the finding — and the guarded property is only read when it is
    safe to read.
    """
    tf_type = next(iter(mapping))
    spec = mapping[tf_type]
    guard = spec.get("guard")
    guard_block = ""
    condition = "subject_resource.exists?"
    if guard:
        guard_block = (f"\n  describe '{tf_type} — {guard.rstrip('?').replace('_', ' ')}' do\n"
                       f"    it 'is enabled, so the value below is meaningful' do\n"
                       f"      expect(subject_resource.exists? && subject_resource.{guard}).to eq(true),\n"
                       f"        'the policy does not enable this, so the threshold it should "
                       f"satisfy is unenforced'\n"
                       f"    end\n  end\n")
        condition = f"subject_resource.exists? && subject_resource.{guard}"
    return SINGLETON_TEMPLATE.format(
        cid=cid, version=version, tf_type=tf_type, resource=spec["resource"],
        title=ruby_quoted_body(entry["name"].rstrip(".")),
        desc=wrap(f"Checkov asserts this against Terraform. This profile asserts it against "
                  f"the account's own {tf_type}, which is a single object rather than a "
                  f"collection.", 4),
        rationale=wrap(meta["rationale"], 4),
        what=wrap("Checkov looks for: " + check_prose(entry, meta), 4),
        fix=block(render_fix(cid, entry, fixes), 4),
        cat="/".join(entry["categories"]) or "IAM", kind=entry["kind"],
        types_rb="%w[" + " ".join(t for t in entry["resources"] if t.startswith("aws_")) + "]",
        docs=entry["tf_docs"].get(tf_type, PROVIDER_DOCS),
        nist=meta["nist"], nist_r4=meta["nist_r4"], cci=meta["cci"], ksi=meta["ksi"],
        sev=meta["severity"], impact=meta["impact"],
        nist_source=meta.get("nist_source", "reviewed"),
        guard_block=guard_block, guard_condition=condition,
        prop=spec["property"],
        matcher=matcher_for(cid, spec.get("satisfies", "equals"), spec.get("value")))


def render_planned(cid, version, entry, meta):
    """A rule that is catalogued but has no reader.

    It asserts nothing and claims nothing: no NIST, CCI or KSI tags, because a
    compliance anchor on a control that cannot evaluate is a claim the profile
    has not earned. Those arrive with the reader.
    """
    types = [r for r in entry["resources"] if r.startswith("aws_")]
    # A graph check's resource types are inferred from its definition, and 29 of
    # them name none it can reach -- they match on attributes or on connections
    # whose ends are not declared as resource_types. An empty list is a real
    # state, not a parse failure, and it must not index off the end.
    needs = ", ".join(types) if types else "the resources this graph check connects"
    docs = entry["tf_docs"][types[0]] if types else PROVIDER_DOCS
    return PLANNED_TEMPLATE.format(
        cid=cid, version=version,
        title=ruby_quoted_body(entry["name"].rstrip(".")),
        types=", ".join(types) or "(not derivable from the graph definition)",
        types_rb="%w[" + " ".join(types) + "]",
        needs=needs,
        what=check_prose(entry, meta).replace('"', "'"),
        cat="/".join(entry["categories"]) or "GRAPH",
        kind=entry["kind"],
        docs=docs)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if any generated control is stale; write nothing")
    args = ap.parse_args()

    version, checks, resource_map, metadata, fixes = load()

    stale, written = [], 0
    for cid in sorted(checks):
        if cid in resource_map:
            if cid not in metadata:
                raise SystemExit(f"{cid}: mapped but has no entry in control_metadata.yml")
            mapping = resource_map[cid]
            if any(v.get("reader") == "membership" for v in mapping.values()):
                body = render_membership(cid, version, checks[cid], mapping, metadata[cid], fixes)
            elif any(v.get("reader") == "singleton" for v in mapping.values()):
                body = render_singleton(cid, version, checks[cid], mapping, metadata[cid], fixes)
            elif any(v.get("reader") == "api" for v in mapping.values()):
                body = render_api(cid, version, checks[cid], mapping, metadata[cid], fixes)
            elif any(v.get("reader") == "stock" for v in mapping.values()):
                body = render_stock(cid, version, checks[cid], mapping, metadata[cid], fixes)
            else:
                body = render(cid, version, checks[cid], mapping, metadata[cid], fixes)
        else:
            body = render_planned(cid, version, checks[cid], metadata.get(cid, {}))
        target = CONTROLS / f"{cid}.rb"
        if args.check:
            if not target.is_file() or target.read_text() != body:
                stale.append(target.name)
            continue
        if not target.is_file() or target.read_text() != body:
            target.write_text(body)
            written += 1

    if args.check:
        if stale:
            print("::error::generated controls are stale — run "
                  "`python3 tools/render_controls.py` and commit the result.")
            for s in stale:
                print(f"  {s}")
            return 1
        print(f"{len(checks)} generated control(s) are in sync with the data files "
                  f"({len(resource_map)} implemented, {len(checks) - len(resource_map)} planned).")
        return 0

    print(f"rendered {len(checks)} control(s) "
              f"({len(resource_map)} implemented, {len(checks) - len(resource_map)} planned); "
              f"{written} changed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
