#!/usr/bin/env python3
"""Render controls/CKV_*.rb from the committed data files.

Why generated
-------------
There are 362 AWS checks. Hand-writing 362 control files means 362 chances to
drift from the rule each one claims to implement, and no way to tell which ones
did. Generating them means the drift is impossible by construction and the
review surface is four data files instead of 362 Ruby files.

    tools/checkov_catalog.yml    derived   what Checkov asserts, per resource type
    tools/resource_map.yml       authored  which deployed field answers it
    tools/control_metadata.yml   authored  compliance anchors, severity, rationale
    tools/fix_examples.yml       authored  remediation, per resource type

The generated file is committed so a reader of the repository sees the controls
without running anything, and `--check` fails when the two disagree.

Remediation is Terraform-first
------------------------------
An organisation that manages its estate through Terraform cannot act on an
`aws ec2 modify-...` command: running it either fails a policy gate or is
reverted by the next apply. So every control carries a complete Terraform block
for each resource type it applies to, and the CLI is the secondary path -- for an
estate not under Terraform, or for closing an exposure before the next apply.
Where there is no in-place fix at all, the control says so rather than implying
one exists.

Usage:
    python3 tools/render_controls.py            # rewrite controls/CKV_*.rb
    python3 tools/render_controls.py --check    # exit 1 if any is stale
"""
import argparse
import pathlib
import sys

import yaml

PROVIDER_DOCS = "https://registry.terraform.io/providers/hashicorp/aws/latest/docs"

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
CONTROLS = ROOT / "controls"

CATALOG = HERE / "checkov_catalog.yml"
RESOURCE_MAP = HERE / "resource_map.yml"
METADATA = HERE / "control_metadata.yml"
FIXES = HERE / "fix_examples.yml"

PROSE = {
    "aws_instance": "instances",
    "aws_launch_template": "launch templates",
    "aws_launch_configuration": "launch configurations",
}


PLANNED_TEMPLATE = """# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        {cid} (checkov {version})
# Applies to:  {types}
# Status:      PLANNED — no deployed-asset reader exists for {needs} yet.
#
# This control is present so the rule is accounted for. It asserts nothing, and
# it carries no NIST/CCI/KSI tags, because a compliance claim it cannot evaluate
# would be worse than an absent one.

control '{cid}' do
  impact 0.0
  title '{title}'

  desc <<~DESC
    Catalogued from Checkov {version}, not yet assessed here: no reader
    enumerates {needs} in this profile, so there is nothing to assert against.

    This is a gap, not a pass, and not a Not Applicable. tools/lint_catalog_drift.py
    counts it every run.
  DESC

  desc 'check', <<~CHECK
    Checkov looks for: {what}
  CHECK

  desc 'fix', <<~'FIX'
    See {docs}
  FIX

  tag checkov_id:            '{cid}'
  tag checkov_category:      '{cat}'
  tag checkov_version:       '{version}'
  tag checkov_kind:          '{kind}'
  tag tf_resources:          {types_rb}
  tag tf_docs:               '{docs}'
  tag implementation_status: 'planned'

  describe "{cid} — no deployed-asset reader for {needs}" do
    skip 'catalogued from Checkov, not yet implemented in this profile'
  end
end
"""


STOCK_TEMPLATE = """# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        {cid} (checkov {version})
# Applies to:  {tf_type}
# Read with:   {plural} -> {singular} (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

exempt = (input('exempt_assets') || {{}})['{cid}'] || []

control '{cid}' do
  title '{title}'

  desc <<~DESC
{desc}
  DESC

  desc 'rationale', <<~RATIONALE
{rationale}
  RATIONALE

  desc 'check', <<~CHECK
{what}
  CHECK

  desc 'fix', <<~'FIX'
{fix}
  FIX

  tag checkov_id:            '{cid}'
  tag checkov_category:      '{cat}'
  tag checkov_version:       '{version}'
  tag checkov_kind:          '{kind}'
  tag tf_resources:          {types_rb}
  tag tf_docs:               '{docs}'
  tag nist:                  {nist}
  tag nist_r4:               {nist_r4}
  tag cci:                   {cci}
  tag ksi:                   {ksi}
  tag severity:              '{sev}'
  tag severity_source:       'assessed'
  tag nist_source:           '{nist_source}'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  ids = {plural}.{ids_column}
  in_scope = ids.reject {{ |id| checkov_exempt?(id: id, type: '{tf_type}', rules: exempt) }}

  applicable = !in_scope.empty?
  impact {impact}
  impact 0.0 unless applicable
  only_if('no {tf_type} in scope') {{ applicable }}

  in_scope.each do |id|
    describe {singular}({arg_expr}) do
      its('{prop}') {{ {matcher} }}
    end
  end
end
"""


API_TEMPLATE = """# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        {cid} (checkov {version})
# Applies to:  {tf_type}
# Read with:   aws_api_assets (declarative spec, tools/api_specs.yml)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {{}})['{cid}'] || []

control '{cid}' do
  title '{title}'

  desc <<~DESC
{desc}
  DESC

  desc 'rationale', <<~RATIONALE
{rationale}
  RATIONALE

  desc 'check', <<~CHECK
{what}
  CHECK

  desc 'fix', <<~'FIX'
{fix}
  FIX

  tag checkov_id:            '{cid}'
  tag checkov_category:      '{cat}'
  tag checkov_version:       '{version}'
  tag checkov_kind:          '{kind}'
  tag tf_resources:          {types_rb}
  tag tf_docs:               '{docs}'
  tag nist:                  {nist}
  tag nist_r4:               {nist_r4}
  tag cci:                   {cci}
  tag ksi:                   {ksi}
  tag severity:              '{sev}'
  tag severity_source:       'assessed'
  tag nist_source:           '{nist_source}'
  tag implementation_status: 'implemented'

  assets = aws_api_assets(type: '{tf_type}', regions: scan_regions)

{nil_filter_comment}
  in_scope = assets.assets(exempt: exempt){nil_filter}

  applicable = !in_scope.empty?
  impact {impact}
  impact 0.0 unless applicable
  only_if('no {tf_type} in scope expressing this setting') {{ applicable }}

  in_scope.each do |asset|
    describe "{tf_type} #{{asset[:id]}} (#{{asset[:account_id]}}/#{{asset[:region]}})" do
      subject {{ asset[:{field}] }}
      it {{ {matcher} }}
    end
  end
end
"""


def load():
    """Reviewed data first, derived data second — and an authored entry always wins.

    The two are separate files on purpose. A derived mapping asserts on a property
    name taken from the Terraform argument, and a derived anchor is a family-level
    claim from the check's category. Merging them into the authored files would
    erase the only signal a reader has for which is which.
    """
    catalog = yaml.safe_load(CATALOG.read_text())
    resource_map = yaml.safe_load(RESOURCE_MAP.read_text())["checks"]
    metadata = yaml.safe_load(METADATA.read_text())

    derived_map = HERE / "resource_map_derived.yml"
    if derived_map.is_file():
        for cid, spec in (yaml.safe_load(derived_map.read_text()) or {}).get("checks", {}).items():
            resource_map.setdefault(cid, spec)
    derived_meta = HERE / "control_metadata_derived.yml"
    if derived_meta.is_file():
        for cid, meta in (yaml.safe_load(derived_meta.read_text()) or {}).items():
            metadata.setdefault(cid, meta)

    return (catalog["_source"]["version"], catalog["checks"], resource_map, metadata,
            yaml.safe_load(FIXES.read_text()))


def block(text, indent):
    """Re-indent an authored block for the heredoc it lands in."""
    pad = " " * indent
    lines = [l.rstrip() for l in str(text).strip("\n").split("\n")]
    return "\n".join(pad + l if l else "" for l in lines)


def wrap(text, indent, width=76):
    pad = " " * indent
    words, lines, cur = str(text).split(), [], pad
    for w in words:
        if len(cur) + len(w) + 1 > width and cur.strip():
            lines.append(cur.rstrip())
            cur = pad + w
        else:
            cur = f"{cur}{'' if cur == pad else ' '}{w}"
    if cur.strip():
        lines.append(cur.rstrip())
    return "\n".join(lines)


def check_prose(entry, meta):
    """What Checkov looks for, derived where the catalogue can say it."""
    if meta.get("what"):
        return meta["what"]
    kinds = []
    for res in entry["resources"]:
        key = entry["inspected_key"].get(res) or ""
        if not key:
            continue
        if entry.get("expected"):
            kinds.append(f"{res}: {key} is {' or '.join(entry['expected'])}")
        elif entry.get("forbidden"):
            kinds.append(f"{res}: {key} is not {' or '.join(entry['forbidden'])}")
    return "; ".join(kinds) or entry["name"]


def render_fix(cid, entry, fixes):
    """Terraform per resource type, then the out-of-band path, then caveats."""
    out = []
    per_type = fixes.get(cid, {})
    for res in entry["resources"]:
        example = per_type.get(res)
        if not example:
            continue
        out.append(f"Terraform — {res}:")
        out.append("")
        out.append(block(example["terraform"], 2))
        out.append("")
        if example.get("cli"):
            out.append(f"Out of band — {res}:")
            out.append("")
            out.append(block(example["cli"], 2))
            out.append("")
        if example.get("note"):
            out.append(wrap(f"Note ({res}): {example['note']}", 0))
            out.append("")
    if not out:
        out = [f"See {list(entry['tf_docs'].values())[0]}"]
    return "\n".join(l for l in out).rstrip()


def render(cid, version, entry, mapping, meta, fixes):
    types = [r for r in entry["resources"] if r in mapping]
    fields = {mapping[r]["field"] for r in types}
    if len(fields) != 1:
        raise SystemExit(f"{cid}: resource_map must use one field per check, got {fields}")
    field = fields.pop()
    satisfies = {mapping[r]["satisfies"] for r in types}.pop()
    assertion = {"empty": "be_empty", "equals": None}[satisfies]
    if assertion is None:
        value = mapping[types[0]].get("value")
        assertion = f"be {str(value).lower()}"

    names = [PROSE.get(t, t) for t in types]
    prose = names[0] if len(names) == 1 else ", ".join(names[:-1]) + " and " + names[-1]
    types_rb = "%w[" + " ".join(types) + "]"

    # f-string template below, so these must be locals rather than format args.
    nist_source = meta.get("nist_source", "reviewed")
    nil_filter, nil_filter_comment = nil_filter_for(satisfies, field)

    stronger = ""
    if meta.get("stronger"):
        stronger = "\n\n" + wrap(meta["stronger"], 4)

    return f'''# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        {cid} (checkov {version})
# Applies to:  {", ".join(types)}
# Answered by: aws_compute_assets#{field}
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {{}})['{cid}'] || []
applies_to   = {types_rb}

control '{cid}' do
  title '{entry["name"].rstrip(".").replace("'", "''")}'

  desc <<~DESC
{wrap(f"Checkov asserts this against Terraform. This profile asserts it against the {prose} that actually exist.", 4)}{stronger}
  DESC

  desc 'rationale', <<~RATIONALE
{wrap(meta["rationale"], 4)}
  RATIONALE

  desc 'check', <<~CHECK
{wrap("Checkov looks for: " + check_prose(entry, meta), 4)}
  CHECK

  desc 'fix', <<~'FIX'
{block(render_fix(cid, entry, fixes), 4)}
  FIX

  tag checkov_id:       '{cid}'
  tag checkov_category: '{"/".join(entry["categories"])}'
  tag checkov_version:  '{version}'
  tag checkov_kind:     '{entry["kind"]}'
  tag tf_resources:     {types_rb}
  tag tf_argument:      '{entry["inspected_key"].get(types[0]) or "(custom check logic)"}'
  tag tf_docs:          '{entry["tf_docs"][types[0]]}'
  tag nist:             {meta["nist"]}
  tag nist_r4:          {meta["nist_r4"]}
  tag cci:              {meta["cci"]}
  tag ksi:              {meta["ksi"]}
  tag severity:         '{meta["severity"]}'
  tag severity_source:  'assessed'
  tag nist_source:      '{nist_source}'
  tag implementation_status: 'implemented'

  assets = aws_compute_assets(regions: scan_regions)

  # Only the asset types this check declares, only what the boundary has, and
  # only those that express the setting at all — a launch template has no
  # ebs_optimized, and nil must not read as a passing false.
{nil_filter_comment}
  in_scope = assets.assets_of(applies_to, exempt: exempt){nil_filter}

  applicable = !in_scope.empty?

  # Two statements, not a ternary: InSpec's AST impact collector calls `.value`
  # on the argument node, and a ternary is an IfNode with none — it aborts
  # `check` for the whole profile before a single control runs.
  impact {meta["impact"]}
  impact 0.0 unless applicable

  only_if("no #{{applies_to.join(', ')}} in scope expressing this setting") {{ applicable }}

  in_scope.each do |asset|
    describe "#{{asset[:type]}} #{{asset[:id]}} (#{{asset[:account_id]}}/#{{asset[:region]}})" do
      subject {{ asset[:{field}] }}
      it {{ should {assertion} }}
    end
  end
end
'''


def render_stock(cid, version, entry, mapping, meta, fixes):
    """A control that reads a stock inspec-aws resource, with no custom library.

    Roughly a third of Checkov's AWS checks land on a resource type inspec-aws
    already enumerates. Writing a bespoke reader for those would be duplicating
    a maintained resource pack in order to answer the same question slightly
    differently.
    """
    tf_type = next(iter(mapping))
    spec = mapping[tf_type]
    enum, assertion = spec["enumerate"], spec["assert"]
    # One matcher implementation, shared with render_api. This block used to be a
    # duplicate of it and drifted: the shared one learned to quote strings, this
    # one did not, so a stock mapping with a string value would still render a
    # bare lowercased identifier — a NameError that reads as a finding.
    satisfies = assertion.get("satisfies", "equals")
    matcher = matcher_for(cid, satisfies, assertion.get("value"))

    return STOCK_TEMPLATE.format(
        cid=cid, version=version, tf_type=tf_type,
        title=entry["name"].rstrip(".").replace("'", "''"),
        desc=wrap(f"Checkov asserts this against Terraform. This profile asserts it against "
                  f"the {tf_type} resources that actually exist, read through the stock "
                  f"inspec-aws {assertion['resource']} resource.", 4),
        rationale=wrap(meta["rationale"], 4),
        what=wrap("Checkov looks for: " + check_prose(entry, meta), 4),
        fix=block(render_fix(cid, entry, fixes), 4),
        cat="/".join(entry["categories"]) or "GRAPH",
        kind=entry["kind"],
        types_rb="%w[" + " ".join(t for t in entry["resources"] if t.startswith("aws_")) + "]",
        docs=entry["tf_docs"].get(tf_type, PROVIDER_DOCS),
        nist=meta["nist"], nist_r4=meta["nist_r4"], cci=meta["cci"], ksi=meta["ksi"],
        sev=meta["severity"], impact=meta["impact"],
        nist_source=meta.get("nist_source", "reviewed"),
        plural=enum["resource"], ids_column=enum["ids"],
        singular=assertion["resource"],
        arg_expr=("id" if assertion.get("arg") in (None, "", "positional")
                  else f"{assertion['arg']}: id"),
        prop=assertion["property"], matcher=matcher)


def ruby_literal(value):
    """A value as Ruby source.

    `str(value).lower()` was wrong for anything but a boolean: an expected value
    of "IMMUTABLE" rendered as the bare word `immutable`, which is a NameError at
    exec and reports as a FAILED control rather than an errored one — a broken
    control that reads as a finding.
    """
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def nil_filter_for(satisfies, field):
    """Whether a nil field means "out of scope" or "this is the failure".

    For a value comparison, a field the API did not return means the asset does
    not express the setting: out of scope, not in breach. For a PRESENCE check
    (`not_empty`), nil is precisely the failing state, and filtering it first
    made the control structurally unfailable — it silently rendered Not
    Applicable for every asset that should have failed.
    """
    if satisfies in ("not_empty", "empty"):
        return ("", "  # A nil field is the FAILING state for a presence check, so it is\n"
                    "  # deliberately not filtered out here.")
    return (f"\n                   .reject {{ |a| a[:{field}].nil? }}",
            "  # A field the API did not return is nil, and nil is not a failing value:\n"
            "  # the asset does not express this setting, so it is out of scope for this\n"
            "  # check rather than in breach of it.")


def matcher_for(cid, satisfies, value):
    """The RSpec matcher a `satisfies` maps to, shared by the stock and API shapes."""
    if satisfies == "equals":
        return f"should eq {ruby_literal(value)}"
    if satisfies == "not_empty":
        # "is set" — nil and an empty string/array all fail. `should_not be_empty`
        # alone raises on nil, and filtering nil out beforehand removes exactly the
        # population that fails.
        return ("should satisfy('be set') { |v| "
                "!v.nil? && !(v.respond_to?(:empty?) && v.empty?) }")
    if satisfies == "empty":
        return ("should satisfy('be unset or empty') { |v| "
                "v.nil? || (v.respond_to?(:empty?) && v.empty?) }")
    if satisfies == "greater_than":
        return f"should be > {value}"
    if satisfies == "in_list":
        return "should be_in [" + ", ".join(ruby_literal(v) for v in value) + "]"
    raise SystemExit(f"{cid}: unknown satisfies '{satisfies}'")


def render_api(cid, version, entry, mapping, meta, fixes):
    """A control reading a type described in tools/api_specs.yml."""
    tf_type = next(iter(mapping))
    spec = mapping[tf_type]
    return API_TEMPLATE.format(
        cid=cid, version=version, tf_type=tf_type,
        title=entry["name"].rstrip(".").replace("'", "''"),
        desc=wrap(f"Checkov asserts this against Terraform. This profile asserts it against "
                  f"the {tf_type} resources that actually exist, enumerated through the "
                  f"declarative API spec.", 4),
        rationale=wrap(meta["rationale"], 4),
        what=wrap("Checkov looks for: " + check_prose(entry, meta), 4),
        fix=block(render_fix(cid, entry, fixes), 4),
        cat="/".join(entry["categories"]) or "GRAPH", kind=entry["kind"],
        types_rb="%w[" + " ".join(t for t in entry["resources"] if t.startswith("aws_")) + "]",
        docs=entry["tf_docs"].get(tf_type, PROVIDER_DOCS),
        nist=meta["nist"], nist_r4=meta["nist_r4"], cci=meta["cci"], ksi=meta["ksi"],
        sev=meta["severity"], impact=meta["impact"],
        nist_source=meta.get("nist_source", "reviewed"),
        field=spec["field"],
        nil_filter=nil_filter_for(spec.get("satisfies", "equals"), spec["field"])[0],
        nil_filter_comment=nil_filter_for(spec.get("satisfies", "equals"), spec["field"])[1],
        matcher=matcher_for(cid, spec.get("satisfies", "equals"), spec.get("value")))


def render_planned(cid, version, entry, meta):
    """A rule that is catalogued but has no reader.

    It asserts nothing and claims nothing: no NIST, CCI or KSI tags, because a
    compliance anchor on a control that cannot evaluate is a claim the profile
    has not earned. Those arrive with the reader.
    """
    types = [r for r in entry["resources"] if r.startswith("aws_")]
    # A graph check's resource types are inferred from its definition, and 29 of
    # them name none it can reach -- they match on attributes or on connections
    # whose ends are not declared as resource_types. An empty list is a real
    # state, not a parse failure, and it must not index off the end.
    needs = ", ".join(types) if types else "the resources this graph check connects"
    docs = entry["tf_docs"][types[0]] if types else PROVIDER_DOCS
    return PLANNED_TEMPLATE.format(
        cid=cid, version=version,
        title=entry["name"].rstrip(".").replace("'", "''"),
        types=", ".join(types) or "(not derivable from the graph definition)",
        types_rb="%w[" + " ".join(types) + "]",
        needs=needs,
        what=check_prose(entry, meta).replace('"', "'"),
        cat="/".join(entry["categories"]) or "GRAPH",
        kind=entry["kind"],
        docs=docs)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if any generated control is stale; write nothing")
    args = ap.parse_args()

    version, checks, resource_map, metadata, fixes = load()

    stale, written = [], 0
    for cid in sorted(checks):
        if cid in resource_map:
            if cid not in metadata:
                raise SystemExit(f"{cid}: mapped but has no entry in control_metadata.yml")
            mapping = resource_map[cid]
            if any(v.get("reader") == "api" for v in mapping.values()):
                body = render_api(cid, version, checks[cid], mapping, metadata[cid], fixes)
            elif any(v.get("reader") == "stock" for v in mapping.values()):
                body = render_stock(cid, version, checks[cid], mapping, metadata[cid], fixes)
            else:
                body = render(cid, version, checks[cid], mapping, metadata[cid], fixes)
        else:
            body = render_planned(cid, version, checks[cid], metadata.get(cid, {}))
        target = CONTROLS / f"{cid}.rb"
        if args.check:
            if not target.is_file() or target.read_text() != body:
                stale.append(target.name)
            continue
        if not target.is_file() or target.read_text() != body:
            target.write_text(body)
            written += 1

    if args.check:
        if stale:
            print("::error::generated controls are stale — run "
                  "`python3 tools/render_controls.py` and commit the result.")
            for s in stale:
                print(f"  {s}")
            return 1
        print(f"{len(checks)} generated control(s) are in sync with the data files "
                  f"({len(resource_map)} implemented, {len(checks) - len(resource_map)} planned).")
        return 0

    print(f"rendered {len(checks)} control(s) "
              f"({len(resource_map)} implemented, {len(checks) - len(resource_map)} planned); "
              f"{written} changed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
