#!/usr/bin/env python3
"""Bake tools/api_specs.yml into libraries/_api_specs.rb.

The specs are data, and the reader needs them at runtime. A profile cannot read
a file from its own directory reliably -- InSpec evaluates library files through
instance_eval with a profile-relative source path, so __dir__ and Dir.pwd are
both wrong -- so the table is generated into Ruby and loaded like any other
library. Same reason tools/ksi bakes its result into the profiles rather than
shipping the catalogue.

The leading underscore keeps it first in InSpec's alphabetical library load
order, so aws_api_assets.rb can reference the constant.
"""
import pathlib
import sys

import yaml

HERE = pathlib.Path(__file__).resolve().parent
SPECS = HERE / "api_specs.yml"
OUT = HERE.parent / "libraries" / "_api_specs.rb"


def ruby(value, indent=0):
    pad = " " * indent
    if isinstance(value, dict):
        if not value:
            return "{}"
        inner = ",\n".join(f"{pad}  {ruby(k)} => {ruby(v, indent + 2)}" for k, v in value.items())
        return "{\n" + inner + f"\n{pad}}}"
    if isinstance(value, list):
        return "[" + ", ".join(ruby(v) for v in value) + "]"
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "nil"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("\\", "\\\\").replace("'", "\\'") + "'"


def main() -> int:
    specs = yaml.safe_load(SPECS.read_text())
    body = ",\n".join(f"  {ruby(k)} => {ruby(v, 2)}" for k, v in sorted(specs.items()))
    OUT.write_text(
        "# Generated by tools/render_api_specs.py from tools/api_specs.yml.\n"
        "# Do not edit by hand: the next render overwrites it.\n"
        "#\n"
        "# Enumeration specs for resource types inspec-aws does not ship. Read by\n"
        "# libraries/aws_api_assets.rb; see tools/api_specs.yml for what each key means.\n"
        f"API_SPECS = {{\n{body},\n}}.freeze\n")
    print(f"wrote {OUT.relative_to(HERE.parent)} — {len(specs)} type(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
