#!/usr/bin/env python3
"""Bake tools/api_specs.yml into libraries/_api_specs.rb.

The specs are data, and the reader needs them at runtime. A profile cannot read
a file from its own directory reliably -- InSpec evaluates library files through
instance_eval with a profile-relative source path, so __dir__ and Dir.pwd are
both wrong -- so the table is generated into Ruby and loaded like any other
library. Same reason tools/ksi bakes its result into the profiles rather than
shipping the catalogue.

The leading underscore keeps it first in InSpec's alphabetical library load
order, so aws_api_assets.rb can reference the constant.
"""
import pathlib
import sys

import yaml

HERE = pathlib.Path(__file__).resolve().parent
SPECS = HERE / "api_specs.yml"
OUT = HERE.parent / "libraries" / "_api_specs.rb"


def ruby(value, indent=0):
    pad = " " * indent
    if isinstance(value, dict):
        if not value:
            return "{}"
        inner = ",\n".join(f"{pad}  {ruby(k)} => {ruby(v, indent + 2)}" for k, v in value.items())
        return "{\n" + inner + f"\n{pad}}}"
    if isinstance(value, list):
        return "[" + ", ".join(ruby(v) for v in value) + "]"
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "nil"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("\\", "\\\\").replace("'", "\\'") + "'"


def render(specs) -> str:
    """The exact text libraries/_api_specs.rb must contain for these specs.

    Factored out of main so tools/lint_api_specs.py can assert the committed bake
    matches tools/api_specs.yml. Nothing else did, and the bake is what the reader
    actually reads: an edit to the YAML that was never re-baked leaves the
    generator rendering one shape (render_controls.py reads the YAML) and the
    reader enumerating another. Rename a `fields:` key and forget this step and
    every control asserts on a key the reader never writes — nil, filtered out by
    the control's nil filter, rendered Not Applicable. All five linters pass.
    """
    body = ",\n".join(f"  {ruby(k)} => {ruby(v, 2)}" for k, v in sorted(specs.items()))
    return ("# Generated by tools/render_api_specs.py from tools/api_specs.yml.\n"
            "# Do not edit by hand: the next render overwrites it.\n"
            "#\n"
            "# Enumeration specs for resource types inspec-aws does not ship. Read by\n"
            "# libraries/aws_api_assets.rb; see tools/api_specs.yml for what each key means.\n"
            f"API_SPECS = {{\n{body},\n}}.freeze\n")


def main() -> int:
    import argparse
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--include-pending", action="store_true",
                    help="also bake tools/api_specs_pending_gems.yml — for LOCAL validation "
                         "against a runtime with those gems installed. Never commit the result: "
                         "the image does not have them, and a missing gem is a profile error.")
    args = ap.parse_args()

    specs = yaml.safe_load(SPECS.read_text())
    if args.include_pending:
        pending = HERE / "api_specs_pending_gems.yml"
        if pending.is_file():
            extra = yaml.safe_load(pending.read_text()) or {}
            specs.update(extra)
            print(f"including {len(extra)} pending spec(s) — LOCAL ONLY, do not commit this bake")
    OUT.write_text(render(specs))
    print(f"wrote {OUT.relative_to(HERE.parent)} — {len(specs)} type(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
