#!/usr/bin/env python3
"""Bake tools/policy_specs.yml into libraries/_policy_specs.rb.

Same reason as tools/render_api_specs.py: the specs are data and the reader
needs them at runtime, but a profile cannot read a file from its own directory
reliably -- InSpec evaluates library files through instance_eval with a
profile-relative source path, so __dir__ and Dir.pwd are both wrong. The table
is generated into Ruby and loaded like any other library.

The leading underscore keeps it first in InSpec's alphabetical library load
order, so aws_policy_documents.rb can reference the constant.
"""
import pathlib
import sys

import yaml

HERE = pathlib.Path(__file__).resolve().parent
SPECS = HERE / "policy_specs.yml"
OUT = HERE.parent / "libraries" / "_policy_specs.rb"


def ruby(value, indent=0):
    pad = " " * indent
    if isinstance(value, dict):
        if not value:
            return "{}"
        inner = ",\n".join(f"{pad}  {ruby(k)} => {ruby(v, indent + 2)}" for k, v in value.items())
        return "{\n" + inner + f"\n{pad}}}"
    if isinstance(value, list):
        return "[" + ", ".join(ruby(v) for v in value) + "]"
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "nil"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("\\", "\\\\").replace("'", "\\'") + "'"


def main() -> int:
    specs = yaml.safe_load(SPECS.read_text()) or {}
    body = ",\n".join(f"  {ruby(k)} => {ruby(v, 2)}" for k, v in sorted(specs.items()))
    OUT.write_text(
        "# Generated by tools/render_policy_specs.py from tools/policy_specs.yml.\n"
        "# Do not edit by hand: the next render overwrites it.\n"
        "#\n"
        "# How to get a policy document out of AWS, per source. Read by\n"
        "# libraries/aws_policy_documents.rb; see tools/policy_specs.yml for what each\n"
        "# key means.\n"
        f"POLICY_SPECS = {{\n{body},\n}}.freeze\n")
    print(f"wrote {OUT.relative_to(HERE.parent)} — {len(specs)} source(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
