# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV2_AWS_3 (checkov 3.3.16)
# Applies to:  aws_guardduty_detector, aws_guardduty_organization_configuration
# Status:      PLANNED — no deployed-asset reader exists for aws_guardduty_detector, aws_guardduty_organization_configuration yet.
#
# This control is present so the rule is accounted for. It asserts nothing, and
# it carries no NIST/CCI/KSI tags, because a compliance claim it cannot evaluate
# would be worse than an absent one.

control 'CKV2_AWS_3' do
  impact 0.0
  title 'Ensure GuardDuty is enabled to specific org/region'

  desc <<~DESC
    Catalogued from Checkov 3.3.16, not yet assessed here: no reader
    enumerates aws_guardduty_detector, aws_guardduty_organization_configuration in this profile, so there is nothing to assert against.

    This is a gap, not a pass, and not a Not Applicable. tools/lint_catalog_drift.py
    counts it every run.
  DESC

  desc 'check', <<~CHECK
    Checkov looks for: Ensure GuardDuty is enabled to specific org/region
  CHECK

  desc 'fix', <<~'FIX'
    See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/guardduty_detector
  FIX

  tag checkov_id:            'CKV2_AWS_3'
  tag checkov_category:      'GENERAL_SECURITY'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'graph'
  tag tf_resources:          %w[aws_guardduty_detector aws_guardduty_organization_configuration]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/guardduty_detector'
  tag implementation_status: 'planned'

  describe "CKV2_AWS_3 — no deployed-asset reader for aws_guardduty_detector, aws_guardduty_organization_configuration" do
    skip 'catalogued from Checkov, not yet implemented in this profile'
  end
end
