# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV2_AWS_52 (checkov 3.3.16)
# Applies to:  aws_opensearch_domain
# Read with:   aws_elasticsearchservice_domains -> aws_elasticsearchservice_domain (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV2_AWS_52'] || []

control 'CKV2_AWS_52' do
  title 'Ensure AWS ElasticSearch/OpenSearch Fine-grained access control is enabled'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_opensearch_domain resources that actually exist, read through
    the stock inspec-aws aws_elasticsearchservice_domain resource.
  DESC

  desc 'rationale', <<~RATIONALE
    Without fine-grained access control the only thing standing between a
    caller and every index in the domain is the resource-based access policy
    and the network path. Enabling it puts authentication and per-index,
    per-document authorisation inside the engine, so a caller that reaches
    the endpoint is still not automatically a reader of everything in it.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: Ensure AWS ElasticSearch/OpenSearch Fine-grained
    access control is enabled
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_elasticsearch_domain:

      resource "aws_elasticsearch_domain" "example" {
        domain_name = "example"

        advanced_security_options {
          enabled                        = true
          internal_user_database_enabled = false
        }

        encrypt_at_rest { enabled = true }
        node_to_node_encryption { enabled = true }
        domain_endpoint_options { enforce_https = true }
      }

    Terraform — aws_opensearch_domain:

      resource "aws_opensearch_domain" "example" {
        domain_name = "example"

        advanced_security_options {
          enabled                        = true
          internal_user_database_enabled = false
        }

        # FGAC requires all three of these
        encrypt_at_rest { enabled = true }
        node_to_node_encryption { enabled = true }
        domain_endpoint_options { enforce_https = true }
      }

    Out of band — aws_opensearch_domain:

      aws opensearch update-domain-config --domain-name <name> --advanced-security-options Enabled=true

    Note (aws_opensearch_domain): Fine-grained access control cannot be enabled
    on an existing domain in place on older engine versions — check the engine
    version first; where it cannot, the domain must be recreated from a
    snapshot.
  FIX

  tag checkov_id:            'CKV2_AWS_52'
  tag checkov_category:      'IAM'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'graph'
  tag tf_resources:          %w[aws_elasticsearch_domain aws_opensearch_domain]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opensearch_domain'
  tag nist:                  ['AC-3', 'IA-2']
  tag nist_r4:               ['AC-3', 'IA-2']
  tag cci:                   ['CCI-000213', 'CCI-000764']
  tag ksi:                   ['KSI-IAM-CTL']
  tag severity:              'high'
  tag severity_source:       'assessed'
  tag nist_source:           'agent-drafted'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  #
  # Every call carries aws_region: a stock resource otherwise reads only the
  # region the connection was built with, and every other region's resources
  # report as absent, which renders Not Applicable rather than unexamined.
  #
  # checkov_enumerate does the reading. It flattens a nested id column, tells an
  # unregistered column apart from an account that simply has none of this
  # resource, and hands back anything that stopped it as `problems` rather than
  # as an empty list -- see libraries/_checkov_enumeration.rb.
  problems = []
  found = checkov_scan_regions(scan_regions).flat_map do |region|
    ids, found_problems = checkov_enumerate(
      aws_elasticsearchservice_domains(aws_region: region), :domain_names
    )
    problems.concat(found_problems.map { |p| "#{region}: #{p}" })
    ids.map { |id| [id, region] }
  end

  # The region LIST is upstream of every enumeration above, and its failure
  # is the one that hides best: no regions means no rows, no rows means no
  # problems, and the control renders Not Applicable across the whole account
  # while a denied ec2:DescribeRegions goes unreported. checkov_scan_regions
  # falls back to the connection's own region and records that here, so a
  # partial scan fails loudly instead of passing quietly.
  problems.concat(checkov_region_problems)

  # Blank ids are separated out and asserted on below rather than filtered away,
  # so a wrong `ids` column is a visible failure and not a silent Not Applicable.
  # `id.nil?` before the interpolation on purpose: a NullResponse answers true to
  # nil? but interpolates to "#<NullResponse:0x...>", which is not blank. The
  # survivors are interpolated rather than `.to_s`'d, because to_s on a
  # NullResponse returns nil and the singular then rejects the argument.
  unusable = found.count { |id, _r| id.nil? || "#{id}".strip.empty? }
  found = found.reject { |id, _r| id.nil? || "#{id}".strip.empty? }
               .map { |id, region| ["#{id}", region] }
  in_scope = found.reject { |id, _r| checkov_exempt?(id: id, type: 'aws_opensearch_domain', rules: exempt) }

  if unusable.positive? || problems.any?
    describe "aws_opensearch_domain enumeration" do
      it 'produced usable identifiers' do
        expect(unusable).to eq(0),
          "#{unusable} row(s) had a blank id — the `ids` column in resource_map.yml "\
          'likely names a field this resource does not expose'
      end

      it 'read the assets it set out to read' do
        expect(problems).to be_empty
      end
    end
  end

  # `unusable.positive? || problems.any?` keeps the control APPLICABLE when the
  # enumeration broke. Without it only_if skips the control, and the broken cases
  # these guards exist to catch are exactly the ones it would suppress — a Not
  # Applicable that means "nobody looked".
  applicable = !in_scope.empty? || unusable.positive? || problems.any?
  impact 0.7
  impact 0.0 unless applicable
  only_if('no aws_opensearch_domain in scope') { applicable }

  in_scope.each do |id, region|
    describe aws_elasticsearchservice_domain(domain_name: id, aws_region: region) do
      its('advanced_security_options.enabled') { should eq true }
    end
  end
end
