# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV2_AWS_19 (checkov 3.3.16)
# Applies to:  aws_eip
# Read with:   aws_ec2_eips -> aws_ec2_eip (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV2_AWS_19'] || []

control 'CKV2_AWS_19' do
  title 'Ensure that all EIP addresses allocated to a VPC are attached to EC2 instances'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_eip resources that actually exist, read through the stock
    inspec-aws aws_ec2_eip resource.
  DESC

  desc 'rationale', <<~RATIONALE
    An allocated but unassociated Elastic IP is an address the account owns
    and nothing answers on. It is billed continuously, it is still present
    in any allow-list or DNS record that was written against it, and
    whatever is associated with it next inherits that reachability without
    anyone revisiting the decision.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: an Elastic IP that is associated with something — an
    instance, a NAT gateway or a network interface — rather than allocated
    and dangling
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_eip_association:

      resource "aws_eip_association" "app" {
        allocation_id        = aws_eip.app.id
        network_interface_id = aws_network_interface.app.id
      }

    Out of band — aws_eip_association:

      aws ec2 release-address --allocation-id <alloc-id>

    Note (aws_eip_association): The CLI shown is the release, not the
    association, because a dangling Elastic IP is far more often garbage than a
    missing wiring. Releasing is irreversible — the address returns to the pool
    and cannot be reclaimed — so confirm no DNS record or partner allow-list
    still names it. To keep it, associate it with `aws ec2 associate-address`
    instead.
  FIX

  tag checkov_id:            'CKV2_AWS_19'
  tag checkov_category:      'NETWORKING'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'graph'
  tag tf_resources:          %w[aws_eip aws_eip_association]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eip'
  tag nist:                  ['CM-8', 'SC-7']
  tag nist_r4:               ['CM-8', 'SC-7']
  tag cci:                   ['CCI-000366', 'CCI-001097']
  tag ksi:                   ['KSI-CMT-INV']
  tag severity:              'low'
  tag severity_source:       'assessed'
  tag nist_source:           'agent-drafted'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  #
  # Every call carries aws_region: a stock resource otherwise reads only the
  # region the connection was built with, and every other region's resources
  # report as absent, which renders Not Applicable rather than unexamined.
  found = checkov_scan_regions(scan_regions).flat_map do |region|
    aws_ec2_eips(aws_region: region).public_ips.to_a.map { |id| [id, region] }
  end

  # A plural resource whose table is built from the API response returns nil for
  # a column that does not exist, rather than raising. Passing that on gives
  # "`[:x]` must be provided" and kills the control. Blank ids are separated out
  # and asserted on below, so a wrong `ids` column is a visible failure rather
  # than a crash or a silent Not Applicable.
  unusable = found.count { |id, _r| "#{id}".strip.empty? }
  found = found.reject { |id, _r| "#{id}".strip.empty? }
  in_scope = found.reject { |id, _r| checkov_exempt?(id: id, type: 'aws_eip', rules: exempt) }

  if unusable.positive?
    describe "aws_eip enumeration" do
      it 'produced usable identifiers' do
        expect(unusable).to eq(0),
          "#{unusable} row(s) had a blank id — the `ids` column in resource_map.yml "          'likely names a field this resource does not expose'
      end
    end
  end

  # `unusable.positive?` keeps the control APPLICABLE when every id came back
  # blank. Without it only_if skips the control, and the wrong-column case this
  # guard exists to catch is exactly the case it would suppress — a Not
  # Applicable that means "the enumeration is broken".
  applicable = !in_scope.empty? || unusable.positive?
  impact 0.3
  impact 0.0 unless applicable
  only_if('no aws_eip in scope') { applicable }

  in_scope.each do |id, region|
    describe aws_ec2_eip(public_ip: id, aws_region: region) do
      its('association_id') { should satisfy('be set') { |v| !v.nil? && !(v.respond_to?(:empty?) && v.empty?) } }
    end
  end
end
