# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV2_AWS_47 (checkov 3.3.16)
# Applies to:  aws_cloudfront_distribution, aws_wafv2_web_acl
# Status:      PLANNED — no deployed-asset reader exists for aws_cloudfront_distribution, aws_wafv2_web_acl yet.
#
# This control is present so the rule is accounted for. It asserts nothing, and
# it carries no NIST/CCI/KSI tags, because a compliance claim it cannot evaluate
# would be worse than an absent one.

control 'CKV2_AWS_47' do
  impact 0.0
  title 'Ensure AWS CloudFront attached WAFv2 WebACL is configured with AMR for Log4j Vulnerability'

  desc <<~DESC
    Catalogued from Checkov 3.3.16, not yet assessed here: no reader
    enumerates aws_cloudfront_distribution, aws_wafv2_web_acl in this profile, so there is nothing to assert against.

    This is a gap, not a pass, and not a Not Applicable. tools/lint_catalog_drift.py
    counts it every run.
  DESC

  desc 'check', <<~CHECK
    Checkov looks for: Ensure AWS CloudFront attached WAFv2 WebACL is configured with AMR for Log4j Vulnerability
  CHECK

  desc 'fix', <<~'FIX'
    See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution
  FIX

  tag checkov_id:            'CKV2_AWS_47'
  tag checkov_category:      'APPLICATION_SECURITY'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'graph'
  tag tf_resources:          %w[aws_cloudfront_distribution aws_wafv2_web_acl]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution'
  tag implementation_status: 'planned'

  describe "CKV2_AWS_47 — no deployed-asset reader for aws_cloudfront_distribution, aws_wafv2_web_acl" do
    skip 'catalogued from Checkov, not yet implemented in this profile'
  end
end
