# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV2_AWS_30 (checkov 3.3.16)
# Applies to:  aws_db_instance, aws_db_parameter_group
# Status:      PLANNED — no deployed-asset reader exists for aws_db_instance, aws_db_parameter_group yet.
#
# This control is present so the rule is accounted for. It asserts nothing, and
# it carries no NIST/CCI/KSI tags, because a compliance claim it cannot evaluate
# would be worse than an absent one.

control 'CKV2_AWS_30' do
  impact 0.0
  title 'Ensure Postgres RDS as aws_db_instance has Query Logging enabled'

  desc <<~DESC
    Catalogued from Checkov 3.3.16, not yet assessed here: no reader
    enumerates aws_db_instance, aws_db_parameter_group in this profile, so there is nothing to assert against.

    This is a gap, not a pass, and not a Not Applicable. tools/lint_catalog_drift.py
    counts it every run.
  DESC

  desc 'check', <<~CHECK
    Checkov looks for: Ensure Postgres RDS as aws_db_instance has Query Logging enabled
  CHECK

  desc 'fix', <<~'FIX'
    See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance
  FIX

  tag checkov_id:            'CKV2_AWS_30'
  tag checkov_category:      'LOGGING'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'graph'
  tag tf_resources:          %w[aws_db_instance aws_db_parameter_group]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance'
  tag implementation_status: 'planned'

  describe "CKV2_AWS_30 — no deployed-asset reader for aws_db_instance, aws_db_parameter_group" do
    skip 'catalogued from Checkov, not yet implemented in this profile'
  end
end
