# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV2_AWS_19 (checkov 3.3.16)
# Applies to:  aws_eip
# Read with:   aws_ec2_eips -> aws_ec2_eip (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV2_AWS_19'] || []

control 'CKV2_AWS_19' do
  title 'Ensure that all EIP addresses allocated to a VPC are attached to EC2 instances'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_eip resources that actually exist, read through the stock
    inspec-aws aws_ec2_eip resource.
  DESC

  desc 'rationale', <<~RATIONALE
    An allocated but unassociated Elastic IP is an address the account owns
    and nothing answers on. It is billed continuously, it is still present
    in any allow-list or DNS record that was written against it, and
    whatever is associated with it next inherits that reachability without
    anyone revisiting the decision.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: an Elastic IP that is associated with something — an
    instance, a NAT gateway or a network interface — rather than allocated
    and dangling
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_eip_association:

      resource "aws_eip_association" "app" {
        allocation_id        = aws_eip.app.id
        network_interface_id = aws_network_interface.app.id
      }

    Out of band — aws_eip_association:

      aws ec2 release-address --allocation-id <alloc-id>

    Note (aws_eip_association): The CLI shown is the release, not the
    association, because a dangling Elastic IP is far more often garbage than a
    missing wiring. Releasing is irreversible — the address returns to the pool
    and cannot be reclaimed — so confirm no DNS record or partner allow-list
    still names it. To keep it, associate it with `aws ec2 associate-address`
    instead.
  FIX

  tag checkov_id:            'CKV2_AWS_19'
  tag checkov_category:      'NETWORKING'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'graph'
  tag tf_resources:          %w[aws_eip aws_eip_association]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eip'
  tag nist:                  ['CM-8', 'SC-7']
  tag nist_r4:               ['CM-8', 'SC-7']
  tag cci:                   ['CCI-000366', 'CCI-001097']
  tag ksi:                   ['KSI-CMT-INV']
  tag severity:              'low'
  tag severity_source:       'assessed'
  tag nist_source:           'agent-drafted'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  #
  # Every call carries aws_region: a stock resource otherwise reads only the
  # region the connection was built with, and every other region's resources
  # report as absent, which renders Not Applicable rather than unexamined.
  #
  # checkov_enumerate does the reading. It flattens a nested id column, tells an
  # unregistered column apart from an account that simply has none of this
  # resource, and hands back anything that stopped it as `problems` rather than
  # as an empty list -- see libraries/_checkov_enumeration.rb.
  problems = []
  found = checkov_scan_regions(scan_regions).flat_map do |region|
    ids, found_problems = checkov_enumerate(
      aws_ec2_eips(aws_region: region), :public_ips
    )
    problems.concat(found_problems.map { |p| "#{region}: #{p}" })
    ids.map { |id| [id, region] }
  end

  # The region LIST is upstream of every enumeration above, and its failure
  # is the one that hides best: no regions means no rows, no rows means no
  # problems, and the control renders Not Applicable across the whole account
  # while a denied ec2:DescribeRegions goes unreported. checkov_scan_regions
  # falls back to the connection's own region and records that here, so a
  # partial scan fails loudly instead of passing quietly.
  problems.concat(checkov_region_problems)

  # Blank ids are separated out and asserted on below rather than filtered away,
  # so a wrong `ids` column is a visible failure and not a silent Not Applicable.
  # `id.nil?` before the interpolation on purpose: a NullResponse answers true to
  # nil? but interpolates to "#<NullResponse:0x...>", which is not blank. The
  # survivors are interpolated rather than `.to_s`'d, because to_s on a
  # NullResponse returns nil and the singular then rejects the argument.
  unusable = found.count { |id, _r| id.nil? || "#{id}".strip.empty? }
  found = found.reject { |id, _r| id.nil? || "#{id}".strip.empty? }
               .map { |id, region| ["#{id}", region] }
  in_scope = found.reject { |id, _r| checkov_exempt?(id: id, type: 'aws_eip', rules: exempt) }

  if unusable.positive? || problems.any?
    describe "aws_eip enumeration" do
      it 'produced usable identifiers' do
        expect(unusable).to eq(0),
          "#{unusable} row(s) had a blank id — the `ids` column in resource_map.yml "\
          'likely names a field this resource does not expose'
      end

      it 'read the assets it set out to read' do
        expect(problems).to be_empty
      end
    end
  end

  # `unusable.positive? || problems.any?` keeps the control APPLICABLE when the
  # enumeration broke. Without it only_if skips the control, and the broken cases
  # these guards exist to catch are exactly the ones it would suppress — a Not
  # Applicable that means "nobody looked".
  applicable = !in_scope.empty? || unusable.positive? || problems.any?
  impact 0.3
  impact 0.0 unless applicable
  only_if('no aws_eip in scope') { applicable }

  in_scope.each do |id, region|
    describe aws_ec2_eip(public_ip: id, aws_region: region) do
      its('association_id') { should satisfy('be set') { |v| !v.nil? && !(v.respond_to?(:empty?) && v.empty?) } }
    end
  end
end
