# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV2_AWS_14 (checkov 3.3.16)
# Applies to:  aws_iam_group
# Read with:   aws_iam_groups -> aws_iam_group (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV2_AWS_14'] || []

control 'CKV2_AWS_14' do
  title 'Ensure that IAM groups includes at least one IAM user'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_iam_group resources that actually exist, read through the stock
    inspec-aws aws_iam_group resource.
  DESC

  desc 'rationale', <<~RATIONALE
    An empty IAM group is a set of permissions with no members and therefore
    no owner and no review. It accumulates policy over time because nobody
    notices it, and it grants everything it holds the moment a user is added
    to it — which is a one-call change nobody treats as a privilege grant.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: an IAM group that contains at least one user, rather
    than a group carrying permissions that nobody holds
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_iam_group_membership:

      resource "aws_iam_group_membership" "engineers" {
        name  = "engineers-membership"
        group = aws_iam_group.engineers.name
        users = [aws_iam_user.alice.name]
      }

    Out of band — aws_iam_group_membership:

      aws iam add-user-to-group --group-name <group> --user-name <user>

    Note (aws_iam_group_membership): Deleting the group is the other valid
    remediation and usually the right one. Note that aws_iam_group_membership is
    authoritative — it removes any user it does not list — whereas
    aws_iam_user_group_membership is not; mixing the two silently drops members
    on the next apply.
  FIX

  tag checkov_id:            'CKV2_AWS_14'
  tag checkov_category:      'IAM'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'graph'
  tag tf_resources:          %w[aws_iam_group aws_iam_group_membership]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_group'
  tag nist:                  ['AC-2', 'CM-6']
  tag nist_r4:               ['AC-2', 'CM-6']
  tag cci:                   ['CCI-000366']
  tag ksi:                   ['KSI-IAM-CTL']
  tag severity:              'low'
  tag severity_source:       'assessed'
  tag nist_source:           'agent-drafted'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  #
  # Every call carries aws_region: a stock resource otherwise reads only the
  # region the connection was built with, and every other region's resources
  # report as absent, which renders Not Applicable rather than unexamined.
  # Global service: the same objects come back from any region, so this is
  # enumerated once rather than once per region.
  found = aws_iam_groups.group_names.to_a.map { |id| [id, nil] }

  # A plural resource whose table is built from the API response returns nil for
  # a column that does not exist, rather than raising. Passing that on gives
  # "`[:x]` must be provided" and kills the control. Blank ids are separated out
  # and asserted on below, so a wrong `ids` column is a visible failure rather
  # than a crash or a silent Not Applicable.
  unusable = found.count { |id, _r| "#{id}".strip.empty? }
  found = found.reject { |id, _r| "#{id}".strip.empty? }
  in_scope = found.reject { |id, _r| checkov_exempt?(id: id, type: 'aws_iam_group', rules: exempt) }

  if unusable.positive?
    describe "aws_iam_group enumeration" do
      it 'produced usable identifiers' do
        expect(unusable).to eq(0),
          "#{unusable} row(s) had a blank id — the `ids` column in resource_map.yml "          'likely names a field this resource does not expose'
      end
    end
  end

  # `unusable.positive?` keeps the control APPLICABLE when every id came back
  # blank. Without it only_if skips the control, and the wrong-column case this
  # guard exists to catch is exactly the case it would suppress — a Not
  # Applicable that means "the enumeration is broken".
  applicable = !in_scope.empty? || unusable.positive?
  impact 0.3
  impact 0.0 unless applicable
  only_if('no aws_iam_group in scope') { applicable }

  in_scope.each do |id, region|
    describe aws_iam_group(group_name: id) do
      its('users') { should satisfy('be set') { |v| !v.nil? && !(v.respond_to?(:empty?) && v.empty?) } }
    end
  end
end
