# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV2_AWS_3 (checkov 3.3.16)
# Applies to:  aws_guardduty_detector
# Read with:   aws_api_assets (two-step parent -> child spec, tools/api_specs.yml)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV2_AWS_3'] || []

control 'CKV2_AWS_3' do
  title 'Ensure GuardDuty is enabled to specific org/region'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_guardduty_detector resources that actually exist, enumerated
    through the two-step (parent -> child) declarative API spec.
  DESC

  desc 'rationale', <<~RATIONALE
    GuardDuty is the account's continuous threat detection. A region without
    an enabled detector produces no findings at all, which reads as "no
    threats" and is in fact "no looking".
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: Ensure GuardDuty is enabled to specific org/region
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_guardduty_detector:

      resource "aws_guardduty_detector" "example" {
        enable                       = true
        finding_publishing_frequency = "FIFTEEN_MINUTES"

        datasources {
          s3_logs { enable = true }
          kubernetes { audit_logs { enable = true } }
          malware_protection {
            scan_ec2_instance_with_findings { ebs_volumes { enable = true } }
          }
        }
      }

    Out of band — aws_guardduty_detector:

      aws guardduty create-detector --enable --finding-publishing-frequency FIFTEEN_MINUTES

    Note (aws_guardduty_detector): GuardDuty is per-region; enable it in every
    region in use, not only the primary.
  FIX

  tag checkov_id:            'CKV2_AWS_3'
  tag checkov_category:      'GENERAL_SECURITY'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'graph'
  tag tf_resources:          %w[aws_guardduty_detector aws_guardduty_organization_configuration]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/guardduty_detector'
  tag nist:                  ['SI-4', 'SI-4 (4)', 'AU-6']
  tag nist_r4:               ['SI-4', 'SI-4 (4)', 'AU-6']
  tag cci:                   ['CCI-001253', 'CCI-002656']
  tag ksi:                   ['KSI-MLA-OSM']
  tag severity:              'high'
  tag severity_source:       'assessed'
  tag nist_source:           'agent-drafted'
  tag implementation_status: 'implemented'

  assets = aws_api_assets(type: 'aws_guardduty_detector', regions: scan_regions)

  # A region — or a whole service — that could not be READ is not the same as
  # one with nothing in it. A missing SDK gem, a denied call or an unreachable
  # endpoint all end up here, and without this assertion they render as "no
  # assets" and the control reports Not Applicable: the worst case reported as
  # "does not apply here".
  unreadable = assets.unreadable_regions
  unless unreadable.empty?
    describe "aws_guardduty_detector enumeration" do
      it 'read every region it attempted' do
        expect(unreadable.map { |r| "#{r[:region]}: #{r[:error]}" }).to be_empty
      end
    end
  end

  # A child list call that failed took a whole SUBTREE with it. That is not
  # "this parent had nothing", and it must never render as one: it is reported
  # per parent here, and it keeps the control APPLICABLE below so that only_if
  # cannot turn a broken enumeration into "does not apply here".
  parent_failures = assets.parent_failures
  unless parent_failures.empty?
    describe "aws_guardduty_detector enumeration" do
      it 'read the children of every parent it enumerated' do
        expect(parent_failures.map { |f| "#{f[:region]}/#{f[:parent_id]}: #{f[:error]}" }).to be_empty
      end
    end
  end

  # A blank id means the spec's `id` column names a member this response does
  # not carry. tools/lint_resource_map.py cannot see that statically, and the
  # damage is silent: every describe is titled with a blank where the identity
  # belongs, and `exempt_assets` entries keyed by id stop matching. Asserted,
  # not filtered — filtering renders Not Applicable, which is the same silence.
  enumerated = assets.assets(exempt: exempt)
  unusable = enumerated.count { |a| "#{a[:id]}".strip.empty? }
  if unusable.positive?
    describe "aws_guardduty_detector enumeration" do
      it 'produced usable identifiers' do
        expect(unusable).to eq(0),
          "#{unusable} row(s) had a blank id — the `id` for aws_guardduty_detector in "\
          'tools/api_specs.yml likely names a member this API does not return'
      end
    end
  end

  # A field the API did not return is nil, and nil is not a failing value:
  # the asset does not express this setting, so it is out of scope for this
  # check rather than in breach of it.
  in_scope = enumerated
                        .reject { |a| a[:status].nil? }

  # `applicable` is a CLAIM that this rule does not apply to this boundary, and
  # only an enumeration that succeeded can earn it. An unreadable region or a
  # blank id column keeps the control applicable so the assertions above are
  # reported; without that, only_if skips the whole control — the two guards
  # included — and the worst case, "every region denied", renders as Not
  # Applicable. The stock template already carries the `unusable` half of this.
  applicable = !in_scope.empty? || !unreadable.empty? || unusable.positive? || !parent_failures.empty?
  impact 0.7
  impact 0.0 unless applicable
  only_if("no aws_guardduty_detector in scope expressing this setting "\
          "(#{assets.parents_seen} parent(s) enumerated by list_detectors)") { applicable }

  in_scope.each do |asset|
    describe "aws_guardduty_detector #{asset[:id]} (#{asset[:account_id]}/#{asset[:region]})" do
      subject { asset[:status] }
      it { should eq 'ENABLED' }
    end
  end
end
