# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV2_AWS_59 (checkov 3.3.16)
# Applies to:  aws_opensearch_domain
# Read with:   aws_elasticsearchservice_domains -> aws_elasticsearchservice_domain (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV2_AWS_59'] || []

control 'CKV2_AWS_59' do
  title 'Ensure ElasticSearch/OpenSearch has dedicated master node enabled'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_opensearch_domain resources that actually exist, read through
    the stock inspec-aws aws_elasticsearchservice_domain resource.
  DESC

  desc 'rationale', <<~RATIONALE
    Without dedicated master nodes the cluster-management workload runs on
    the same nodes serving queries, so one expensive search can cost the
    cluster its quorum and take the domain — and anything logging to it —
    offline. Dedicated masters isolate cluster state from data-plane load.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: Ensure ElasticSearch/OpenSearch has dedicated master
    node enabled
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_elasticsearch_domain:

      resource "aws_elasticsearch_domain" "example" {
        domain_name = "example"

        cluster_config {
          instance_count           = 3
          dedicated_master_enabled = true
          dedicated_master_type    = "m5.large.elasticsearch"
          dedicated_master_count   = 3
          zone_awareness_enabled   = true
        }
      }

    Terraform — aws_opensearch_domain:

      resource "aws_opensearch_domain" "example" {
        domain_name = "example"

        cluster_config {
          instance_type            = "r6g.large.search"
          instance_count           = 3
          dedicated_master_enabled = true
          dedicated_master_type    = "m6g.large.search"
          dedicated_master_count   = 3
          zone_awareness_enabled   = true
        }
      }

    Out of band — aws_opensearch_domain:

      aws opensearch update-domain-config --domain-name <name> --cluster-config DedicatedMasterEnabled=true,DedicatedMasterType=m6g.large.search,DedicatedMasterCount=3

    Note (aws_opensearch_domain): Use three dedicated masters, not two — two
    cannot form a quorum, so a single master loss takes the cluster down anyway.
    The change is a blue/green deployment and the domain stays available but is
    briefly degraded.
  FIX

  tag checkov_id:            'CKV2_AWS_59'
  tag checkov_category:      'GENERAL_SECURITY'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'graph'
  tag tf_resources:          %w[aws_elasticsearch_domain aws_opensearch_domain]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opensearch_domain'
  tag nist:                  ['CP-10', 'SC-5']
  tag nist_r4:               ['CP-10', 'SC-5']
  tag cci:                   ['CCI-000553', 'CCI-002385']
  tag ksi:                   ['KSI-RPL-RCY']
  tag severity:              'low'
  tag severity_source:       'assessed'
  tag nist_source:           'agent-drafted'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  #
  # Every call carries aws_region: a stock resource otherwise reads only the
  # region the connection was built with, and every other region's resources
  # report as absent, which renders Not Applicable rather than unexamined.
  found = checkov_scan_regions(scan_regions).flat_map do |region|
    aws_elasticsearchservice_domains(aws_region: region).domain_names.to_a.map { |id| [id, region] }
  end

  # A plural resource whose table is built from the API response returns nil for
  # a column that does not exist, rather than raising. Passing that on gives
  # "`[:x]` must be provided" and kills the control. Blank ids are separated out
  # and asserted on below, so a wrong `ids` column is a visible failure rather
  # than a crash or a silent Not Applicable.
  unusable = found.count { |id, _r| "#{id}".strip.empty? }
  found = found.reject { |id, _r| "#{id}".strip.empty? }
  in_scope = found.reject { |id, _r| checkov_exempt?(id: id, type: 'aws_opensearch_domain', rules: exempt) }

  if unusable.positive?
    describe "aws_opensearch_domain enumeration" do
      it 'produced usable identifiers' do
        expect(unusable).to eq(0),
          "#{unusable} row(s) had a blank id — the `ids` column in resource_map.yml "          'likely names a field this resource does not expose'
      end
    end
  end

  # `unusable.positive?` keeps the control APPLICABLE when every id came back
  # blank. Without it only_if skips the control, and the wrong-column case this
  # guard exists to catch is exactly the case it would suppress — a Not
  # Applicable that means "the enumeration is broken".
  applicable = !in_scope.empty? || unusable.positive?
  impact 0.3
  impact 0.0 unless applicable
  only_if('no aws_opensearch_domain in scope') { applicable }

  in_scope.each do |id, region|
    describe aws_elasticsearchservice_domain(domain_name: id, aws_region: region) do
      its('elasticsearch_cluster_config.dedicated_master_enabled') { should eq true }
    end
  end
end
