# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV2_AWS_61 (checkov 3.3.16)
# Applies to:  aws_s3_bucket
# Read with:   aws_s3_buckets -> aws_s3_bucket (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV2_AWS_61'] || []

control 'CKV2_AWS_61' do
  title 'Ensure that an S3 bucket has a lifecycle configuration'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_s3_bucket resources that actually exist, read through the stock
    inspec-aws aws_s3_bucket resource.
  DESC

  desc 'rationale', <<~RATIONALE
    With no lifecycle configuration, objects accumulate indefinitely:
    retention becomes whatever nobody got around to deleting.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: Ensure that an S3 bucket has a lifecycle
    configuration
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_s3_bucket:

      resource "aws_s3_bucket_lifecycle_configuration" "example" {
        bucket = aws_s3_bucket.example.id

        rule {
          id     = "expire-noncurrent"
          status = "Enabled"

          noncurrent_version_expiration {
            noncurrent_days = 90
          }

          abort_incomplete_multipart_upload {
            days_after_initiation = 7
          }
        }
      }

    Out of band — aws_s3_bucket:

      aws s3api put-bucket-lifecycle-configuration --bucket <name> \
        --lifecycle-configuration file://lifecycle.json
  FIX

  tag checkov_id:            'CKV2_AWS_61'
  tag checkov_category:      'LOGGING'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'graph'
  tag tf_resources:          %w[aws_s3_bucket]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket'
  tag nist:                  ['AU-11', 'SI-12']
  tag nist_r4:               ['AU-11', 'SI-12']
  tag cci:                   ['CCI-000167', 'CCI-001678']
  tag ksi:                   ['KSI-MLA-OSM']
  tag severity:              'low'
  tag severity_source:       'assessed'
  tag nist_source:           'reviewed'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  #
  # Every call carries aws_region: a stock resource otherwise reads only the
  # region the connection was built with, and every other region's resources
  # report as absent, which renders Not Applicable rather than unexamined.
  found = checkov_scan_regions(scan_regions).flat_map do |region|
    aws_s3_buckets(aws_region: region).bucket_names.to_a.map { |id| [id, region] }
  end

  # A plural resource whose table is built from the API response returns nil for
  # a column that does not exist, rather than raising. Passing that on gives
  # "`[:x]` must be provided" and kills the control. Blank ids are separated out
  # and asserted on below, so a wrong `ids` column is a visible failure rather
  # than a crash or a silent Not Applicable.
  unusable = found.count { |id, _r| "#{id}".strip.empty? }
  found = found.reject { |id, _r| "#{id}".strip.empty? }
  in_scope = found.reject { |id, _r| checkov_exempt?(id: id, type: 'aws_s3_bucket', rules: exempt) }

  if unusable.positive?
    describe "aws_s3_bucket enumeration" do
      it 'produced usable identifiers' do
        expect(unusable).to eq(0),
          "#{unusable} row(s) had a blank id — the `ids` column in resource_map.yml "          'likely names a field this resource does not expose'
      end
    end
  end

  applicable = !in_scope.empty?
  impact 0.3
  impact 0.0 unless applicable
  only_if('no aws_s3_bucket in scope') { applicable }

  in_scope.each do |id, region|
    describe aws_s3_bucket(bucket_name: id, aws_region: region) do
      its('bucket_lifecycle_rules') { should satisfy('be set') { |v| !v.nil? && !(v.respond_to?(:empty?) && v.empty?) } }
    end
  end
end
