# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV2_AWS_52 (checkov 3.3.16)
# Applies to:  aws_opensearch_domain
# Read with:   aws_elasticsearchservice_domains -> aws_elasticsearchservice_domain (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV2_AWS_52'] || []

control 'CKV2_AWS_52' do
  title 'Ensure AWS ElasticSearch/OpenSearch Fine-grained access control is enabled'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_opensearch_domain resources that actually exist, read through
    the stock inspec-aws aws_elasticsearchservice_domain resource.
  DESC

  desc 'rationale', <<~RATIONALE
    Without fine-grained access control the only thing standing between a
    caller and every index in the domain is the resource-based access policy
    and the network path. Enabling it puts authentication and per-index,
    per-document authorisation inside the engine, so a caller that reaches
    the endpoint is still not automatically a reader of everything in it.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: Ensure AWS ElasticSearch/OpenSearch Fine-grained
    access control is enabled
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_elasticsearch_domain:

      resource "aws_elasticsearch_domain" "example" {
        domain_name = "example"

        advanced_security_options {
          enabled                        = true
          internal_user_database_enabled = false
        }

        encrypt_at_rest { enabled = true }
        node_to_node_encryption { enabled = true }
        domain_endpoint_options { enforce_https = true }
      }

    Terraform — aws_opensearch_domain:

      resource "aws_opensearch_domain" "example" {
        domain_name = "example"

        advanced_security_options {
          enabled                        = true
          internal_user_database_enabled = false
        }

        # FGAC requires all three of these
        encrypt_at_rest { enabled = true }
        node_to_node_encryption { enabled = true }
        domain_endpoint_options { enforce_https = true }
      }

    Out of band — aws_opensearch_domain:

      aws opensearch update-domain-config --domain-name <name> --advanced-security-options Enabled=true

    Note (aws_opensearch_domain): Fine-grained access control cannot be enabled
    on an existing domain in place on older engine versions — check the engine
    version first; where it cannot, the domain must be recreated from a
    snapshot.
  FIX

  tag checkov_id:            'CKV2_AWS_52'
  tag checkov_category:      'IAM'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'graph'
  tag tf_resources:          %w[aws_elasticsearch_domain aws_opensearch_domain]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opensearch_domain'
  tag nist:                  ['AC-3', 'IA-2']
  tag nist_r4:               ['AC-3', 'IA-2']
  tag cci:                   ['CCI-000213', 'CCI-000764']
  tag ksi:                   ['KSI-IAM-CTL']
  tag severity:              'high'
  tag severity_source:       'assessed'
  tag nist_source:           'agent-drafted'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  #
  # Every call carries aws_region: a stock resource otherwise reads only the
  # region the connection was built with, and every other region's resources
  # report as absent, which renders Not Applicable rather than unexamined.
  found = checkov_scan_regions(scan_regions).flat_map do |region|
    aws_elasticsearchservice_domains(aws_region: region).domain_names.to_a.map { |id| [id, region] }
  end

  # A plural resource whose table is built from the API response returns nil for
  # a column that does not exist, rather than raising. Passing that on gives
  # "`[:x]` must be provided" and kills the control. Blank ids are separated out
  # and asserted on below, so a wrong `ids` column is a visible failure rather
  # than a crash or a silent Not Applicable.
  unusable = found.count { |id, _r| "#{id}".strip.empty? }
  found = found.reject { |id, _r| "#{id}".strip.empty? }
  in_scope = found.reject { |id, _r| checkov_exempt?(id: id, type: 'aws_opensearch_domain', rules: exempt) }

  if unusable.positive?
    describe "aws_opensearch_domain enumeration" do
      it 'produced usable identifiers' do
        expect(unusable).to eq(0),
          "#{unusable} row(s) had a blank id — the `ids` column in resource_map.yml "          'likely names a field this resource does not expose'
      end
    end
  end

  # `unusable.positive?` keeps the control APPLICABLE when every id came back
  # blank. Without it only_if skips the control, and the wrong-column case this
  # guard exists to catch is exactly the case it would suppress — a Not
  # Applicable that means "the enumeration is broken".
  applicable = !in_scope.empty? || unusable.positive?
  impact 0.7
  impact 0.0 unless applicable
  only_if('no aws_opensearch_domain in scope') { applicable }

  in_scope.each do |id, region|
    describe aws_elasticsearchservice_domain(domain_name: id, aws_region: region) do
      its('advanced_security_options.enabled') { should eq true }
    end
  end
end
