# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV2_AWS_57 (checkov 3.3.16)
# Applies to:  aws_secretsmanager_secret
# Read with:   aws_secretsmanager_secrets -> aws_secretsmanager_secret (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV2_AWS_57'] || []

control 'CKV2_AWS_57' do
  title 'Ensure Secrets Manager secrets should have automatic rotation enabled'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_secretsmanager_secret resources that actually exist, read
    through the stock inspec-aws aws_secretsmanager_secret resource.
  DESC

  desc 'rationale', <<~RATIONALE
    A secret that is never rotated stays valid for as long as it exists, so
    the window between a leak and its expiry is unbounded. Automatic
    rotation caps that window without depending on anyone noticing the leak,
    which is the only form of credential hygiene that survives contact with
    a real estate.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: Ensure Secrets Manager secrets should have automatic
    rotation enabled
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_secretsmanager_secret:

      resource "aws_secretsmanager_secret" "example" {
        name = "example"
      }

      resource "aws_secretsmanager_secret_rotation" "example" {
        secret_id           = aws_secretsmanager_secret.example.id
        rotation_lambda_arn = aws_lambda_function.rotator.arn

        rotation_rules {
          automatically_after_days = 30
        }
      }

    Out of band — aws_secretsmanager_secret:

      aws secretsmanager rotate-secret --secret-id <name> --rotation-lambda-arn <arn> --rotation-rules AutomaticallyAfterDays=30

    Note (aws_secretsmanager_secret): Rotation needs a rotation Lambda that can
    reach both Secrets Manager and the credential's own service; AWS publishes
    templates per engine. Secrets owned by another service (OwningService set,
    e.g. RDS-managed master passwords) rotate under that service's control and
    should be exempted rather than given a second rotator.
  FIX

  tag checkov_id:            'CKV2_AWS_57'
  tag checkov_category:      'GENERAL_SECURITY'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'graph'
  tag tf_resources:          %w[aws_secretsmanager_secret]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/secretsmanager_secret'
  tag nist:                  ['IA-5', 'SC-12']
  tag nist_r4:               ['IA-5', 'SC-12']
  tag cci:                   ['CCI-000196', 'CCI-002450']
  tag ksi:                   ['KSI-IAM-CTL', 'KSI-SVC-KMG']
  tag severity:              'medium'
  tag severity_source:       'assessed'
  tag nist_source:           'agent-drafted'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  #
  # Every call carries aws_region: a stock resource otherwise reads only the
  # region the connection was built with, and every other region's resources
  # report as absent, which renders Not Applicable rather than unexamined.
  #
  # checkov_enumerate does the reading. It flattens a nested id column, tells an
  # unregistered column apart from an account that simply has none of this
  # resource, and hands back anything that stopped it as `problems` rather than
  # as an empty list -- see libraries/_checkov_enumeration.rb.
  problems = []
  found = checkov_scan_regions(scan_regions).flat_map do |region|
    ids, found_problems = checkov_enumerate(
      aws_secretsmanager_secrets(aws_region: region), :arns
    )
    problems.concat(found_problems.map { |p| "#{region}: #{p}" })
    ids.map { |id| [id, region] }
  end

  # The region LIST is upstream of every enumeration above, and its failure
  # is the one that hides best: no regions means no rows, no rows means no
  # problems, and the control renders Not Applicable across the whole account
  # while a denied ec2:DescribeRegions goes unreported. checkov_scan_regions
  # falls back to the connection's own region and records that here, so a
  # partial scan fails loudly instead of passing quietly.
  problems.concat(checkov_region_problems)

  # Blank ids are separated out and asserted on below rather than filtered away,
  # so a wrong `ids` column is a visible failure and not a silent Not Applicable.
  # `id.nil?` before the interpolation on purpose: a NullResponse answers true to
  # nil? but interpolates to "#<NullResponse:0x...>", which is not blank. The
  # survivors are interpolated rather than `.to_s`'d, because to_s on a
  # NullResponse returns nil and the singular then rejects the argument.
  unusable = found.count { |id, _r| id.nil? || "#{id}".strip.empty? }
  found = found.reject { |id, _r| id.nil? || "#{id}".strip.empty? }
               .map { |id, region| ["#{id}", region] }
  in_scope = found.reject { |id, _r| checkov_exempt?(id: id, type: 'aws_secretsmanager_secret', rules: exempt) }

  if unusable.positive? || problems.any?
    describe "aws_secretsmanager_secret enumeration" do
      it 'produced usable identifiers' do
        expect(unusable).to eq(0),
          "#{unusable} row(s) had a blank id — the `ids` column in resource_map.yml "\
          'likely names a field this resource does not expose'
      end

      it 'read the assets it set out to read' do
        expect(problems).to be_empty
      end
    end
  end

  # `unusable.positive? || problems.any?` keeps the control APPLICABLE when the
  # enumeration broke. Without it only_if skips the control, and the broken cases
  # these guards exist to catch are exactly the ones it would suppress — a Not
  # Applicable that means "nobody looked".
  applicable = !in_scope.empty? || unusable.positive? || problems.any?
  impact 0.5
  impact 0.0 unless applicable
  only_if('no aws_secretsmanager_secret in scope') { applicable }

  in_scope.each do |id, region|
    describe aws_secretsmanager_secret(secret_id: id, aws_region: region) do
      its('rotation_enabled') { should eq true }
    end
  end
end
