# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_133 (checkov 3.3.16)
# Applies to:  aws_db_instance
# Read with:   aws_rds_instances -> aws_rds_instance (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV_AWS_133'] || []

control 'CKV_AWS_133' do
  title 'Ensure that RDS instances has backup policy'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_db_instance resources that actually exist, read through the
    stock inspec-aws aws_rds_instance resource.
  DESC

  desc 'rationale', <<~RATIONALE
    A retention period of zero turns automated backups off entirely, so a
    dropped table or a corrupted write has no point to recover from. The
    window is the only thing standing between a mistake and permanent data
    loss, and it cannot be added retroactively.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: backup_retention_period is set to between 1 and 35
    days
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_db_instance:

      resource "aws_db_instance" "app" {
        identifier           = "app-db"
        engine               = "postgres"
        engine_version       = "16.4"
        instance_class       = "db.t4g.medium"
        allocated_storage    = 50
        username             = "app"
        manage_master_user_password = true
        storage_encrypted    = true
        skip_final_snapshot  = false
        final_snapshot_identifier = "app-db-final"

        backup_retention_period = 30            # 1-35; 0 disables backups
        backup_window           = "03:00-04:00"
        copy_tags_to_snapshot   = true
      }

    Out of band — aws_db_instance:

      aws rds modify-db-instance --db-instance-identifier app-db --backup-retention-period 30 --apply-immediately

    Note (aws_db_instance): Raising the retention period from 0 restarts
    automated backups but does not create history: the first recoverable point
    is the backup taken after the change, so there is a gap equal to the time
    the setting was 0.

    Terraform — aws_rds_cluster:

      resource "aws_rds_cluster" "app" {
        cluster_identifier  = "app-aurora"
        engine              = "aurora-postgresql"
        engine_version      = "15.4"
        master_username     = "app"
        manage_master_user_password = true
        storage_encrypted   = true
        skip_final_snapshot = false
        final_snapshot_identifier = "app-aurora-final"

        backup_retention_period      = 30
        preferred_backup_window      = "03:00-04:00"
        copy_tags_to_snapshot        = true
      }

    Out of band — aws_rds_cluster:

      aws rds modify-db-cluster --db-cluster-identifier app-aurora --backup-retention-period 30 --apply-immediately
  FIX

  tag checkov_id:            'CKV_AWS_133'
  tag checkov_category:      'BACKUP_AND_RECOVERY'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'custom'
  tag tf_resources:          %w[aws_db_instance aws_rds_cluster]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance'
  tag nist:                  ['CP-9', 'CP-10']
  tag nist_r4:               ['CP-9', 'CP-10']
  tag cci:                   ['CCI-000535', 'CCI-000553']
  tag ksi:                   ['KSI-RPL-RCY']
  tag severity:              'medium'
  tag severity_source:       'assessed'
  tag nist_source:           'agent-drafted'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  #
  # Every call carries aws_region: a stock resource otherwise reads only the
  # region the connection was built with, and every other region's resources
  # report as absent, which renders Not Applicable rather than unexamined.
  #
  # checkov_enumerate does the reading. It flattens a nested id column, tells an
  # unregistered column apart from an account that simply has none of this
  # resource, and hands back anything that stopped it as `problems` rather than
  # as an empty list -- see libraries/_checkov_enumeration.rb.
  problems = []
  found = checkov_scan_regions(scan_regions).flat_map do |region|
    ids, found_problems = checkov_enumerate(
      aws_rds_instances(aws_region: region), :db_instance_identifiers
    )
    problems.concat(found_problems.map { |p| "#{region}: #{p}" })
    ids.map { |id| [id, region] }
  end

  # Blank ids are separated out and asserted on below rather than filtered away,
  # so a wrong `ids` column is a visible failure and not a silent Not Applicable.
  # `id.nil?` before the interpolation on purpose: a NullResponse answers true to
  # nil? but interpolates to "#<NullResponse:0x...>", which is not blank. The
  # survivors are interpolated rather than `.to_s`'d, because to_s on a
  # NullResponse returns nil and the singular then rejects the argument.
  unusable = found.count { |id, _r| id.nil? || "#{id}".strip.empty? }
  found = found.reject { |id, _r| id.nil? || "#{id}".strip.empty? }
               .map { |id, region| ["#{id}", region] }
  in_scope = found.reject { |id, _r| checkov_exempt?(id: id, type: 'aws_db_instance', rules: exempt) }

  if unusable.positive? || problems.any?
    describe "aws_db_instance enumeration" do
      it 'produced usable identifiers' do
        expect(unusable).to eq(0),
          "#{unusable} row(s) had a blank id — the `ids` column in resource_map.yml "\
          'likely names a field this resource does not expose'
      end

      it 'read the assets it set out to read' do
        expect(problems).to be_empty
      end
    end
  end

  # `unusable.positive? || problems.any?` keeps the control APPLICABLE when the
  # enumeration broke. Without it only_if skips the control, and the broken cases
  # these guards exist to catch are exactly the ones it would suppress — a Not
  # Applicable that means "nobody looked".
  applicable = !in_scope.empty? || unusable.positive? || problems.any?
  impact 0.5
  impact 0.0 unless applicable
  only_if('no aws_db_instance in scope') { applicable }

  in_scope.each do |id, region|
    describe aws_rds_instance(db_instance_identifier: id, aws_region: region) do
      its('backup_retention_period') { should be > 0 }
    end
  end
end
