# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_354 (checkov 3.3.16)
# Applies to:  aws_db_instance
# Read with:   aws_rds_instances -> aws_rds_instance (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

exempt = (input('exempt_assets') || {})['CKV_AWS_354'] || []

control 'CKV_AWS_354' do
  title 'Ensure RDS Performance Insights are encrypted using KMS CMKs'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_db_instance resources that actually exist, read through the
    stock inspec-aws aws_rds_instance resource.
  DESC

  desc 'rationale', <<~RATIONALE
    Performance Insights data includes query text, which can carry the
    values a query filtered on; unencrypted, it is a second copy of the data
    outside the database.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_db_instance: performance_insights_kms_key_id is
    CKV_ANY; aws_rds_cluster_instance: performance_insights_kms_key_id is
    CKV_ANY
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_db_instance:

      resource "aws_db_instance" "example" {
        performance_insights_enabled    = true
        performance_insights_kms_key_id = aws_kms_key.rds.arn
      }

    Out of band — aws_db_instance:

      Set at enable time: aws rds modify-db-instance --db-instance-identifier <id> \
        --enable-performance-insights --performance-insights-kms-key-id <key-arn>
  FIX

  tag checkov_id:            'CKV_AWS_354'
  tag checkov_category:      'ENCRYPTION'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'value'
  tag tf_resources:          %w[aws_db_instance aws_rds_cluster_instance]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#performance-insights-kms-key-id'
  tag nist:                  ['SC-28', 'SC-28 (1)']
  tag nist_r4:               ['SC-28', 'SC-28 (1)']
  tag cci:                   ['CCI-002475']
  tag ksi:                   ['KSI-SVC-CER']
  tag severity:              'medium'
  tag severity_source:       'assessed'
  tag nist_source:           'reviewed'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  ids = aws_rds_instances.db_instance_identifiers
  in_scope = ids.reject { |id| checkov_exempt?(id: id, type: 'aws_db_instance', rules: exempt) }

  applicable = !in_scope.empty?
  impact 0.5
  impact 0.0 unless applicable
  only_if('no aws_db_instance in scope') { applicable }

  in_scope.each do |id|
    describe aws_rds_instance(id) do
      its('performance_insights_kms_key_id') { should satisfy('be set') { |v| !v.nil? && !(v.respond_to?(:empty?) && v.empty?) } }
    end
  end
end
