# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_30 (checkov 3.3.16)
# Applies to:  aws_elasticache_replication_group
# Read with:   aws_elasticache_replication_groups -> aws_elasticache_replication_group (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV_AWS_30'] || []

control 'CKV_AWS_30' do
  title 'Ensure all data stored in the ElastiCache Replication Group is securely encrypted at transit'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_elasticache_replication_group resources that actually exist,
    read through the stock inspec-aws aws_elasticache_replication_group
    resource.
  DESC

  desc 'rationale', <<~RATIONALE
    Without in-transit encryption the cache protocol is plaintext on the
    wire, including the values it returns.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_elasticache_replication_group:
    transit_encryption_enabled is True
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_elasticache_replication_group:

      resource "aws_elasticache_replication_group" "example" {
        transit_encryption_enabled = true
      }

    Out of band — aws_elasticache_replication_group:

      aws elasticache modify-replication-group --replication-group-id <id> \
        --transit-encryption-enabled --transit-encryption-mode preferred --apply-immediately
  FIX

  tag checkov_id:            'CKV_AWS_30'
  tag checkov_category:      'ENCRYPTION'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'value'
  tag tf_resources:          %w[aws_elasticache_replication_group]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_replication_group#transit-encryption-enabled'
  tag nist:                  ['SC-8', 'SC-8 (1)']
  tag nist_r4:               ['SC-8', 'SC-8 (1)']
  tag cci:                   ['CCI-002418']
  tag ksi:                   ['KSI-SVC-CET']
  tag severity:              'high'
  tag severity_source:       'assessed'
  tag nist_source:           'reviewed'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  #
  # Every call carries aws_region: a stock resource otherwise reads only the
  # region the connection was built with, and every other region's resources
  # report as absent, which renders Not Applicable rather than unexamined.
  found = checkov_scan_regions(scan_regions).flat_map do |region|
    aws_elasticache_replication_groups(aws_region: region).ids.to_a.map { |id| [id, region] }
  end

  # A plural resource whose table is built from the API response returns nil for
  # a column that does not exist, rather than raising. Passing that on gives
  # "`[:x]` must be provided" and kills the control. Blank ids are separated out
  # and asserted on below, so a wrong `ids` column is a visible failure rather
  # than a crash or a silent Not Applicable.
  unusable = found.count { |id, _r| "#{id}".strip.empty? }
  found = found.reject { |id, _r| "#{id}".strip.empty? }
  in_scope = found.reject { |id, _r| checkov_exempt?(id: id, type: 'aws_elasticache_replication_group', rules: exempt) }

  if unusable.positive?
    describe "aws_elasticache_replication_group enumeration" do
      it 'produced usable identifiers' do
        expect(unusable).to eq(0),
          "#{unusable} row(s) had a blank id — the `ids` column in resource_map.yml "          'likely names a field this resource does not expose'
      end
    end
  end

  # `unusable.positive?` keeps the control APPLICABLE when every id came back
  # blank. Without it only_if skips the control, and the wrong-column case this
  # guard exists to catch is exactly the case it would suppress — a Not
  # Applicable that means "the enumeration is broken".
  applicable = !in_scope.empty? || unusable.positive?
  impact 0.7
  impact 0.0 unless applicable
  only_if('no aws_elasticache_replication_group in scope') { applicable }

  in_scope.each do |id, region|
    describe aws_elasticache_replication_group(replication_group_id: id, aws_region: region) do
      its('transit_encryption_enabled') { should eq true }
    end
  end
end
