# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_87 (checkov 3.3.16)
# Applies to:  aws_redshift_cluster
# Status:      PLANNED — no deployed-asset reader exists for aws_redshift_cluster yet.
#
# This control is present so the rule is accounted for. It asserts nothing, and
# it carries no NIST/CCI/KSI tags, because a compliance claim it cannot evaluate
# would be worse than an absent one.

control 'CKV_AWS_87' do
  impact 0.0
  title 'Redshift cluster should not be publicly accessible'

  desc <<~DESC
    Catalogued from Checkov 3.3.16, not yet assessed here: no reader
    enumerates aws_redshift_cluster in this profile, so there is nothing to assert against.

    This is a gap, not a pass, and not a Not Applicable. tools/lint_catalog_drift.py
    counts it every run.
  DESC

  desc 'check', <<~CHECK
    Checkov looks for: aws_redshift_cluster: publicly_accessible is False
  CHECK

  desc 'fix', <<~'FIX'
    See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_cluster#publicly-accessible
  FIX

  tag checkov_id:            'CKV_AWS_87'
  tag checkov_category:      'NETWORKING'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'value'
  tag tf_resources:          %w[aws_redshift_cluster]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_cluster#publicly-accessible'
  tag implementation_status: 'planned'

  describe "CKV_AWS_87 — no deployed-asset reader for aws_redshift_cluster" do
    skip 'catalogued from Checkov, not yet implemented in this profile'
  end
end
