# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_81 (checkov 3.3.16)
# Applies to:  aws_msk_cluster
# Read with:   aws_api_assets (declarative spec, tools/api_specs.yml)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV_AWS_81'] || []

control 'CKV_AWS_81' do
  title 'Ensure MSK Cluster encryption in rest and transit is enabled'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_msk_cluster resources that actually exist, enumerated through
    the declarative API spec.
  DESC

  desc 'rationale', <<~RATIONALE
    A client_broker setting of PLAINTEXT or TLS_PLAINTEXT keeps a cleartext
    listener open on every broker, so a producer misconfiguration silently
    sends the topic's payload unencrypted across the VPC. Requiring TLS
    removes the option rather than relying on every client to choose it.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: encryption_info is set and encryption_in_transit does
    not weaken client_broker or in_cluster
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_msk_cluster:

      resource "aws_msk_cluster" "events" {
        cluster_name           = "events"
        kafka_version          = "3.6.0"
        number_of_broker_nodes = 3

        broker_node_group_info {
          instance_type   = "kafka.m5.large"
          client_subnets  = var.private_subnet_ids
          security_groups = [aws_security_group.msk.id]
          storage_info {
            ebs_storage_info { volume_size = 100 }
          }
        }

        encryption_info {
          encryption_at_rest_kms_key_arn = aws_kms_key.msk.arn
          encryption_in_transit {
            client_broker = "TLS"    # not TLS_PLAINTEXT, not PLAINTEXT
            in_cluster    = true
          }
        }
      }

    Out of band — aws_msk_cluster:

      aws kafka update-security --cluster-arn <arn> --current-version <version> --encryption-info '{"EncryptionInTransit":{"ClientBroker":"TLS","InCluster":true}}'

    Note (aws_msk_cluster): UpdateSecurity performs a rolling broker restart.
    Any producer or consumer still connecting on the plaintext port stops
    working the moment it completes, so move the clients first.
  FIX

  tag checkov_id:            'CKV_AWS_81'
  tag checkov_category:      'ENCRYPTION'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'custom'
  tag tf_resources:          %w[aws_msk_cluster]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/msk_cluster'
  tag nist:                  ['SC-8', 'SC-8 (1)']
  tag nist_r4:               ['SC-8', 'SC-8 (1)']
  tag cci:                   ['CCI-002418', 'CCI-002421']
  tag ksi:                   ['KSI-SVC-CET']
  tag severity:              'high'
  tag severity_source:       'assessed'
  tag nist_source:           'agent-drafted'
  tag implementation_status: 'implemented'

  assets = aws_api_assets(type: 'aws_msk_cluster', regions: scan_regions)

  # A field the API did not return is nil, and nil is not a failing value:
  # the asset does not express this setting, so it is out of scope for this
  # check rather than in breach of it.
  in_scope = assets.assets(exempt: exempt)
                   .reject { |a| a[:encryption_in_transit_client_broker].nil? }

  applicable = !in_scope.empty?
  impact 0.7
  impact 0.0 unless applicable
  only_if('no aws_msk_cluster in scope expressing this setting') { applicable }

  in_scope.each do |asset|
    describe "aws_msk_cluster #{asset[:id]} (#{asset[:account_id]}/#{asset[:region]})" do
      subject { asset[:encryption_in_transit_client_broker] }
      it { should eq 'TLS' }
    end
  end
end
