# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_16 (checkov 3.3.16)
# Applies to:  aws_db_instance
# Read with:   aws_rds_instances -> aws_rds_instance (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV_AWS_16'] || []

control 'CKV_AWS_16' do
  title 'Ensure all data stored in the RDS is securely encrypted at rest'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_db_instance resources that actually exist, read through the
    stock inspec-aws aws_rds_instance resource.
  DESC

  desc 'rationale', <<~RATIONALE
    An unencrypted database exposes its data through any snapshot copy or
    storage-layer access, without touching the database itself.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_db_instance: storage_encrypted is True
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_db_instance:

      resource "aws_db_instance" "example" {
        storage_encrypted = true
        kms_key_id        = aws_kms_key.rds.arn
      }

    Out of band — aws_db_instance:

      Encryption cannot be enabled in place: snapshot, copy the snapshot with --kms-key-id, and restore.
  FIX

  tag checkov_id:            'CKV_AWS_16'
  tag checkov_category:      'ENCRYPTION'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'value'
  tag tf_resources:          %w[aws_db_instance]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#storage-encrypted'
  tag nist:                  ['SC-28', 'SC-28 (1)']
  tag nist_r4:               ['SC-28', 'SC-28 (1)']
  tag cci:                   ['CCI-001199', 'CCI-002475']
  tag ksi:                   ['KSI-SVC-CER']
  tag severity:              'high'
  tag severity_source:       'assessed'
  tag nist_source:           'reviewed'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  #
  # Every call carries aws_region: a stock resource otherwise reads only the
  # region the connection was built with, and every other region's resources
  # report as absent, which renders Not Applicable rather than unexamined.
  found = checkov_scan_regions(scan_regions).flat_map do |region|
    aws_rds_instances(aws_region: region).db_instance_identifiers.to_a.map { |id| [id, region] }
  end

  # A plural resource whose table is built from the API response returns nil for
  # a column that does not exist, rather than raising. Passing that on gives
  # "`[:x]` must be provided" and kills the control. Blank ids are separated out
  # and asserted on below, so a wrong `ids` column is a visible failure rather
  # than a crash or a silent Not Applicable.
  unusable = found.count { |id, _r| "#{id}".strip.empty? }
  found = found.reject { |id, _r| "#{id}".strip.empty? }
  in_scope = found.reject { |id, _r| checkov_exempt?(id: id, type: 'aws_db_instance', rules: exempt) }

  if unusable.positive?
    describe "aws_db_instance enumeration" do
      it 'produced usable identifiers' do
        expect(unusable).to eq(0),
          "#{unusable} row(s) had a blank id — the `ids` column in resource_map.yml "          'likely names a field this resource does not expose'
      end
    end
  end

  applicable = !in_scope.empty?
  impact 0.7
  impact 0.0 unless applicable
  only_if('no aws_db_instance in scope') { applicable }

  in_scope.each do |id, region|
    describe aws_rds_instance(db_instance_identifier: id, aws_region: region) do
      its('storage_encrypted') { should eq true }
    end
  end
end
