# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_89 (checkov 3.3.16)
# Applies to:  aws_dms_replication_instance
# Status:      PLANNED — no deployed-asset reader exists for aws_dms_replication_instance yet.
#
# This control is present so the rule is accounted for. It asserts nothing, and
# it carries no NIST/CCI/KSI tags, because a compliance claim it cannot evaluate
# would be worse than an absent one.

control 'CKV_AWS_89' do
  impact 0.0
  title 'DMS replication instance should not be publicly accessible'

  desc <<~DESC
    Catalogued from Checkov 3.3.16, not yet assessed here: no reader
    enumerates aws_dms_replication_instance in this profile, so there is nothing to assert against.

    This is a gap, not a pass, and not a Not Applicable. tools/lint_catalog_drift.py
    counts it every run.
  DESC

  desc 'check', <<~CHECK
    Checkov looks for: aws_dms_replication_instance: publicly_accessible is not True
  CHECK

  desc 'fix', <<~'FIX'
    See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_replication_instance#publicly-accessible
  FIX

  tag checkov_id:            'CKV_AWS_89'
  tag checkov_category:      'NETWORKING'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'negative'
  tag tf_resources:          %w[aws_dms_replication_instance]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_replication_instance#publicly-accessible'
  tag implementation_status: 'planned'

  describe "CKV_AWS_89 — no deployed-asset reader for aws_dms_replication_instance" do
    skip 'catalogued from Checkov, not yet implemented in this profile'
  end
end
