# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_313 (checkov 3.3.16)
# Applies to:  aws_rds_cluster
# Read with:   aws_rds_clusters -> aws_rds_cluster (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV_AWS_313'] || []

control 'CKV_AWS_313' do
  title 'Ensure RDS cluster configured to copy tags to snapshots'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_rds_cluster resources that actually exist, read through the
    stock inspec-aws aws_rds_cluster resource.
  DESC

  desc 'rationale', <<~RATIONALE
    A snapshot that loses its tags loses its owner, its retention class and
    its cost centre at the moment it becomes long-lived data.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_rds_cluster: copy_tags_to_snapshot is True
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_rds_cluster:

      resource "aws_rds_cluster" "example" {
        copy_tags_to_snapshot = true
      }

    Out of band — aws_rds_cluster:

      aws rds modify-db-cluster --db-cluster-identifier <id> --copy-tags-to-snapshot --apply-immediately
  FIX

  tag checkov_id:            'CKV_AWS_313'
  tag checkov_category:      'GENERAL_SECURITY'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'value'
  tag tf_resources:          %w[aws_rds_cluster]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#copy-tags-to-snapshot'
  tag nist:                  ['CM-8', 'AU-12']
  tag nist_r4:               ['CM-8', 'AU-12']
  tag cci:                   ['CCI-000366']
  tag ksi:                   ['KSI-CMT-INV']
  tag severity:              'low'
  tag severity_source:       'assessed'
  tag nist_source:           'reviewed'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  #
  # Every call carries aws_region: a stock resource otherwise reads only the
  # region the connection was built with, and every other region's resources
  # report as absent, which renders Not Applicable rather than unexamined.
  found = checkov_scan_regions(scan_regions).flat_map do |region|
    aws_rds_clusters(aws_region: region).cluster_identifier.to_a.map { |id| [id, region] }
  end

  # A plural resource whose table is built from the API response returns nil for
  # a column that does not exist, rather than raising. Passing that on gives
  # "`[:x]` must be provided" and kills the control. Blank ids are separated out
  # and asserted on below, so a wrong `ids` column is a visible failure rather
  # than a crash or a silent Not Applicable.
  unusable = found.count { |id, _r| "#{id}".strip.empty? }
  found = found.reject { |id, _r| "#{id}".strip.empty? }
  in_scope = found.reject { |id, _r| checkov_exempt?(id: id, type: 'aws_rds_cluster', rules: exempt) }

  if unusable.positive?
    describe "aws_rds_cluster enumeration" do
      it 'produced usable identifiers' do
        expect(unusable).to eq(0),
          "#{unusable} row(s) had a blank id — the `ids` column in resource_map.yml "          'likely names a field this resource does not expose'
      end
    end
  end

  applicable = !in_scope.empty?
  impact 0.3
  impact 0.0 unless applicable
  only_if('no aws_rds_cluster in scope') { applicable }

  in_scope.each do |id, region|
    describe aws_rds_cluster(db_cluster_identifier: id, aws_region: region) do
      its('copy_tags_to_snapshot') { should eq true }
    end
  end
end
