# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_28 (checkov 3.3.16)
# Applies to:  aws_dynamodb_table
# Read with:   aws_dynamodb_tables -> aws_dynamodb_table (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV_AWS_28'] || []

control 'CKV_AWS_28' do
  title 'Ensure DynamoDB point in time recovery (backup) is enabled'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_dynamodb_table resources that actually exist, read through the
    stock inspec-aws aws_dynamodb_table resource.
  DESC

  desc 'rationale', <<~RATIONALE
    Ensure DynamoDB point in time recovery (backup) is enabled. Anchors
    derived from the check's backup and recovery category, not reviewed
    control by control.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_dynamodb_table:
    point_in_time_recovery/[0]/enabled is True or true
  CHECK

  desc 'fix', <<~'FIX'
    See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table#point-in-time-recovery
  FIX

  tag checkov_id:            'CKV_AWS_28'
  tag checkov_category:      'BACKUP_AND_RECOVERY'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'value'
  tag tf_resources:          %w[aws_dynamodb_table]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table#point-in-time-recovery'
  tag nist:                  ['CP-9', 'CP-10']
  tag nist_r4:               ['CP-9', 'CP-10']
  tag cci:                   ['CCI-000535', 'CCI-000553']
  tag ksi:                   ['KSI-RPL-ABO']
  tag severity:              'medium'
  tag severity_source:       'assessed'
  tag nist_source:           'category-derived'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  #
  # Every call carries aws_region: a stock resource otherwise reads only the
  # region the connection was built with, and every other region's resources
  # report as absent, which renders Not Applicable rather than unexamined.
  #
  # checkov_enumerate does the reading. It flattens a nested id column, tells an
  # unregistered column apart from an account that simply has none of this
  # resource, and hands back anything that stopped it as `problems` rather than
  # as an empty list -- see libraries/_checkov_enumeration.rb.
  problems = []
  found = checkov_scan_regions(scan_regions).flat_map do |region|
    ids, found_problems = checkov_enumerate(
      aws_dynamodb_tables(aws_region: region), :table_names
    )
    problems.concat(found_problems.map { |p| "#{region}: #{p}" })
    ids.map { |id| [id, region] }
  end

  # The region LIST is upstream of every enumeration above, and its failure
  # is the one that hides best: no regions means no rows, no rows means no
  # problems, and the control renders Not Applicable across the whole account
  # while a denied ec2:DescribeRegions goes unreported. checkov_scan_regions
  # falls back to the connection's own region and records that here, so a
  # partial scan fails loudly instead of passing quietly.
  problems.concat(checkov_region_problems)

  # Blank ids are separated out and asserted on below rather than filtered away,
  # so a wrong `ids` column is a visible failure and not a silent Not Applicable.
  # `id.nil?` before the interpolation on purpose: a NullResponse answers true to
  # nil? but interpolates to "#<NullResponse:0x...>", which is not blank. The
  # survivors are interpolated rather than `.to_s`'d, because to_s on a
  # NullResponse returns nil and the singular then rejects the argument.
  unusable = found.count { |id, _r| id.nil? || "#{id}".strip.empty? }
  found = found.reject { |id, _r| id.nil? || "#{id}".strip.empty? }
               .map { |id, region| ["#{id}", region] }
  in_scope = found.reject { |id, _r| checkov_exempt?(id: id, type: 'aws_dynamodb_table', rules: exempt) }

  if unusable.positive? || problems.any?
    describe "aws_dynamodb_table enumeration" do
      it 'produced usable identifiers' do
        expect(unusable).to eq(0),
          "#{unusable} row(s) had a blank id — the `ids` column in resource_map.yml "\
          'likely names a field this resource does not expose'
      end

      it 'read the assets it set out to read' do
        expect(problems).to be_empty
      end
    end
  end

  # `unusable.positive? || problems.any?` keeps the control APPLICABLE when the
  # enumeration broke. Without it only_if skips the control, and the broken cases
  # these guards exist to catch are exactly the ones it would suppress — a Not
  # Applicable that means "nobody looked".
  applicable = !in_scope.empty? || unusable.positive? || problems.any?
  impact 0.5
  impact 0.0 unless applicable
  only_if('no aws_dynamodb_table in scope') { applicable }

  in_scope.each do |id, region|
    describe aws_dynamodb_table(table_name: id, aws_region: region) do
      its('point_in_time_recovery') { should eq true }
    end
  end
end
