# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_68 (checkov 3.3.16)
# Applies to:  aws_cloudfront_distribution
# Read with:   aws_cloudfront_distributions -> aws_cloudfront_distribution (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV_AWS_68'] || []

control 'CKV_AWS_68' do
  title 'CloudFront Distribution should have WAF enabled'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_cloudfront_distribution resources that actually exist, read
    through the stock inspec-aws aws_cloudfront_distribution resource.
  DESC

  desc 'rationale', <<~RATIONALE
    CloudFront Distribution should have WAF enabled. Anchors derived from
    the check's application security category, not reviewed control by
    control.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_cloudfront_distribution: web_acl_id is CKV_ANY
  CHECK

  desc 'fix', <<~'FIX'
    See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#web-acl-id
  FIX

  tag checkov_id:            'CKV_AWS_68'
  tag checkov_category:      'APPLICATION_SECURITY'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'value'
  tag tf_resources:          %w[aws_cloudfront_distribution]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#web-acl-id'
  tag nist:                  ['SA-11', 'SI-10']
  tag nist_r4:               ['SA-11', 'SI-10']
  tag cci:                   ['CCI-003173']
  tag ksi:                   ['KSI-SCR-MIT']
  tag severity:              'medium'
  tag severity_source:       'assessed'
  tag nist_source:           'category-derived'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  #
  # Every call carries aws_region: a stock resource otherwise reads only the
  # region the connection was built with, and every other region's resources
  # report as absent, which renders Not Applicable rather than unexamined.
  found = checkov_scan_regions(scan_regions).flat_map do |region|
    aws_cloudfront_distributions(aws_region: region).distribution_ids.to_a.map { |id| [id, region] }
  end

  # A plural resource whose table is built from the API response returns nil for
  # a column that does not exist, rather than raising. Passing that on gives
  # "`[:x]` must be provided" and kills the control. Blank ids are separated out
  # and asserted on below, so a wrong `ids` column is a visible failure rather
  # than a crash or a silent Not Applicable.
  unusable = found.count { |id, _r| "#{id}".strip.empty? }
  found = found.reject { |id, _r| "#{id}".strip.empty? }
  in_scope = found.reject { |id, _r| checkov_exempt?(id: id, type: 'aws_cloudfront_distribution', rules: exempt) }

  if unusable.positive?
    describe "aws_cloudfront_distribution enumeration" do
      it 'produced usable identifiers' do
        expect(unusable).to eq(0),
          "#{unusable} row(s) had a blank id — the `ids` column in resource_map.yml "          'likely names a field this resource does not expose'
      end
    end
  end

  applicable = !in_scope.empty?
  impact 0.5
  impact 0.0 unless applicable
  only_if('no aws_cloudfront_distribution in scope') { applicable }

  in_scope.each do |id, region|
    describe aws_cloudfront_distribution(distribution_id: id, aws_region: region) do
      its('web_acl_id') { should satisfy('be set') { |v| !v.nil? && !(v.respond_to?(:empty?) && v.empty?) } }
    end
  end
end
