# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_89 (checkov 3.3.16)
# Applies to:  aws_dms_replication_instance
# Read with:   aws_api_assets (declarative spec, tools/api_specs.yml)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV_AWS_89'] || []

control 'CKV_AWS_89' do
  title 'DMS replication instance should not be publicly accessible'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_dms_replication_instance resources that actually exist,
    enumerated through the declarative API spec.
  DESC

  desc 'rationale', <<~RATIONALE
    A replication instance reads from a source database and writes to a
    target; publicly reachable, it is a route between both.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_dms_replication_instance: publicly_accessible is
    not True
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_dms_replication_instance:

      resource "aws_dms_replication_instance" "example" {
        publicly_accessible = false
      }

    Out of band — aws_dms_replication_instance:

      aws dms modify-replication-instance --replication-instance-arn <arn> --no-publicly-accessible
  FIX

  tag checkov_id:            'CKV_AWS_89'
  tag checkov_category:      'NETWORKING'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'negative'
  tag tf_resources:          %w[aws_dms_replication_instance]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_replication_instance#publicly-accessible'
  tag nist:                  ['SC-7', 'SC-7 (5)']
  tag nist_r4:               ['SC-7', 'SC-7 (5)']
  tag cci:                   ['CCI-001097', 'CCI-002080']
  tag ksi:                   ['KSI-CNA-NDS']
  tag severity:              'high'
  tag severity_source:       'assessed'
  tag nist_source:           'reviewed'
  tag implementation_status: 'implemented'

  assets = aws_api_assets(type: 'aws_dms_replication_instance', regions: scan_regions)

  # A field the API did not return is nil, and nil is not a failing value: the
  # asset does not express this setting, so it is out of scope for this check
  # rather than in breach of it.
  in_scope = assets.assets(exempt: exempt).reject { |a| a[:publicly_accessible].nil? }

  applicable = !in_scope.empty?
  impact 0.7
  impact 0.0 unless applicable
  only_if('no aws_dms_replication_instance in scope expressing this setting') { applicable }

  in_scope.each do |asset|
    describe "aws_dms_replication_instance #{asset[:id]} (#{asset[:account_id]}/#{asset[:region]})" do
      subject { asset[:publicly_accessible] }
      it { should eq false }
    end
  end
end
