# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_123 (checkov 3.3.16)
# Applies to:  aws_vpc_endpoint_service
# Read with:   aws_vpc_endpoint_services -> aws_vpc_endpoint_service (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

exempt = (input('exempt_assets') || {})['CKV_AWS_123'] || []

control 'CKV_AWS_123' do
  title 'Ensure that VPC Endpoint Service is configured for Manual Acceptance'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_vpc_endpoint_service resources that actually exist, read through
    the stock inspec-aws aws_vpc_endpoint_service resource.
  DESC

  desc 'rationale', <<~RATIONALE
    Ensure that VPC Endpoint Service is configured for Manual Acceptance.
    Anchors derived from the check's networking category, not reviewed
    control by control.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_vpc_endpoint_service: acceptance_required is True
  CHECK

  desc 'fix', <<~'FIX'
    See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_endpoint_service#acceptance-required
  FIX

  tag checkov_id:            'CKV_AWS_123'
  tag checkov_category:      'NETWORKING'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'value'
  tag tf_resources:          %w[aws_vpc_endpoint_service]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_endpoint_service#acceptance-required'
  tag nist:                  ['SC-7', 'SC-7 (5)']
  tag nist_r4:               ['SC-7', 'SC-7 (5)']
  tag cci:                   ['CCI-001097', 'CCI-002080']
  tag ksi:                   ['KSI-CNA-NDS']
  tag severity:              'high'
  tag severity_source:       'assessed'
  tag nist_source:           'category-derived'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  ids = aws_vpc_endpoint_services.base_endpoint_dns_names
  in_scope = ids.reject { |id| checkov_exempt?(id: id, type: 'aws_vpc_endpoint_service', rules: exempt) }

  applicable = !in_scope.empty?
  impact 0.7
  impact 0.0 unless applicable
  only_if('no aws_vpc_endpoint_service in scope') { applicable }

  in_scope.each do |id|
    describe aws_vpc_endpoint_service(service_name: id) do
      its('acceptance_required') { should eq true }
    end
  end
end
