# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_5 (checkov 3.3.16)
# Applies to:  aws_elasticsearch_domain
# Read with:   aws_elasticsearchservice_domains -> aws_elasticsearchservice_domain (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

exempt = (input('exempt_assets') || {})['CKV_AWS_5'] || []

control 'CKV_AWS_5' do
  title 'Ensure all data stored in the Elasticsearch is securely encrypted at rest'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_elasticsearch_domain resources that actually exist, read through
    the stock inspec-aws aws_elasticsearchservice_domain resource.
  DESC

  desc 'rationale', <<~RATIONALE
    A search domain holds a denormalised copy of whatever it indexes, which
    is usually the same records the source database encrypts. Without
    encryption at rest the domain's underlying storage and its automated
    snapshots are readable by anyone who reaches them.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_elasticsearch_domain: encrypt_at_rest/[0]/enabled
    is True; aws_opensearch_domain: encrypt_at_rest/[0]/enabled is True
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_elasticsearch_domain:

      resource "aws_elasticsearch_domain" "search" {
        domain_name           = "search"
        elasticsearch_version = "7.10"

        encrypt_at_rest {
          enabled    = true
          kms_key_id = aws_kms_key.search.arn
        }
      }

    Out of band — aws_elasticsearch_domain:

      aws es update-elasticsearch-domain-config --domain-name <name> --encryption-at-rest-options Enabled=true,KmsKeyId=<key-arn>

    Note (aws_elasticsearch_domain): Encryption at rest cannot be turned on for
    an existing domain in every engine version; where the update is rejected the
    domain must be recreated and reindexed, so treat this as a migration rather
    than a setting change.

    Terraform — aws_opensearch_domain:

      resource "aws_opensearch_domain" "search" {
        domain_name    = "search"
        engine_version = "OpenSearch_2.11"

        encrypt_at_rest {
          enabled    = true
          kms_key_id = aws_kms_key.search.arn
        }
      }

    Out of band — aws_opensearch_domain:

      aws opensearch update-domain-config --domain-name <name> --encryption-at-rest-options Enabled=true,KmsKeyId=<key-arn>
  FIX

  tag checkov_id:            'CKV_AWS_5'
  tag checkov_category:      'ENCRYPTION'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'value'
  tag tf_resources:          %w[aws_elasticsearch_domain aws_opensearch_domain]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain#encrypt-at-rest'
  tag nist:                  ['SC-28', 'SC-28 (1)']
  tag nist_r4:               ['SC-28', 'SC-28 (1)']
  tag cci:                   ['CCI-001199', 'CCI-002475']
  tag ksi:                   ['KSI-SVC-CER']
  tag severity:              'high'
  tag severity_source:       'assessed'
  tag nist_source:           'agent-drafted'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  ids = aws_elasticsearchservice_domains.domain_names
  in_scope = ids.reject { |id| checkov_exempt?(id: id, type: 'aws_elasticsearch_domain', rules: exempt) }

  applicable = !in_scope.empty?
  impact 0.7
  impact 0.0 unless applicable
  only_if('no aws_elasticsearch_domain in scope') { applicable }

  in_scope.each do |id|
    describe aws_elasticsearchservice_domain(domain_name: id) do
      its('encryption_at_rest_options.enabled') { should eq true }
    end
  end
end
