# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_50 (checkov 3.3.16)
# Applies to:  aws_lambda_function
# Read with:   aws_api_assets (declarative spec, tools/api_specs.yml)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV_AWS_50'] || []

control 'CKV_AWS_50' do
  title 'X-Ray tracing is enabled for Lambda'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_lambda_function resources that actually exist, enumerated
    through the declarative API spec.
  DESC

  desc 'rationale', <<~RATIONALE
    Without X-Ray tracing a latency or error question about a function has
    no per-invocation evidence, only aggregate metrics.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_lambda_function: tracing_config/[0]/mode is
    PassThrough or Active
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_lambda_function:

      resource "aws_lambda_function" "example" {
        tracing_config {
          mode = "Active"
        }
      }

    Out of band — aws_lambda_function:

      aws lambda update-function-configuration --function-name <name> --tracing-config Mode=Active
  FIX

  tag checkov_id:            'CKV_AWS_50'
  tag checkov_category:      'LOGGING'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'value'
  tag tf_resources:          %w[aws_lambda_function]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function#tracing-config'
  tag nist:                  ['AU-2', 'AU-12']
  tag nist_r4:               ['AU-2', 'AU-12']
  tag cci:                   ['CCI-000169', 'CCI-000172']
  tag ksi:                   ['KSI-MLA-LOG']
  tag severity:              'low'
  tag severity_source:       'assessed'
  tag nist_source:           'reviewed'
  tag implementation_status: 'implemented'

  assets = aws_api_assets(type: 'aws_lambda_function', regions: scan_regions)

  # A field the API did not return is nil, and nil is not a failing value: the
  # asset does not express this setting, so it is out of scope for this check
  # rather than in breach of it.
  in_scope = assets.assets(exempt: exempt).reject { |a| a[:tracing_mode].nil? }

  applicable = !in_scope.empty?
  impact 0.3
  impact 0.0 unless applicable
  only_if('no aws_lambda_function in scope expressing this setting') { applicable }

  in_scope.each do |asset|
    describe "aws_lambda_function #{asset[:id]} (#{asset[:account_id]}/#{asset[:region]})" do
      subject { asset[:tracing_mode] }
      it { should be_in ['Active', 'PassThrough'] }
    end
  end
end
