# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_346 (checkov 3.3.16)
# Applies to:  aws_networkfirewall_firewall_policy
# Status:      PLANNED — no deployed-asset reader exists for aws_networkfirewall_firewall_policy yet.
#
# This control is present so the rule is accounted for. It asserts nothing, and
# it carries no NIST/CCI/KSI tags, because a compliance claim it cannot evaluate
# would be worse than an absent one.

control 'CKV_AWS_346' do
  impact 0.0
  title 'Ensure Network Firewall Policy defines an encryption configuration that uses a customer managed Key (CMK)'

  desc <<~DESC
    Catalogued from Checkov 3.3.16, not yet assessed here: no reader
    enumerates aws_networkfirewall_firewall_policy in this profile, so there is nothing to assert against.

    This is a gap, not a pass, and not a Not Applicable. tools/lint_catalog_drift.py
    counts it every run.
  DESC

  desc 'check', <<~CHECK
    Checkov looks for: aws_networkfirewall_firewall_policy: encryption_configuration/[0]/key_id is CKV_ANY
  CHECK

  desc 'fix', <<~'FIX'
    See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkfirewall_firewall_policy#encryption-configuration
  FIX

  tag checkov_id:            'CKV_AWS_346'
  tag checkov_category:      'ENCRYPTION'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'value'
  tag tf_resources:          %w[aws_networkfirewall_firewall_policy]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkfirewall_firewall_policy#encryption-configuration'
  tag implementation_status: 'planned'

  describe "CKV_AWS_346 — no deployed-asset reader for aws_networkfirewall_firewall_policy" do
    skip 'catalogued from Checkov, not yet implemented in this profile'
  end
end
