# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_164 (checkov 3.3.16)
# Applies to:  aws_transfer_server
# Read with:   aws_api_assets (declarative spec, tools/api_specs.yml)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV_AWS_164'] || []

control 'CKV_AWS_164' do
  title 'Ensure Transfer Server is not exposed publicly'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_transfer_server resources that actually exist, enumerated
    through the declarative API spec.
  DESC

  desc 'rationale', <<~RATIONALE
    A PUBLIC Transfer endpoint accepts connections from anywhere on the
    internet, and Transfer servers front file stores that usually hold bulk
    data exchanged with partners. A VPC endpoint puts the same service
    behind security groups and route tables that can be reasoned about.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_transfer_server: endpoint_type is VPC or
    VPC_ENDPOINT
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_transfer_server:

      resource "aws_transfer_server" "sftp" {
        identity_provider_type = "SERVICE_MANAGED"
        protocols              = ["SFTP"]
        endpoint_type          = "VPC"
        security_policy_name   = "TransferSecurityPolicy-2024-01"

        endpoint_details {
          vpc_id             = aws_vpc.main.id
          subnet_ids         = aws_subnet.private[*].id
          security_group_ids = [aws_security_group.sftp.id]
        }
      }

    Out of band — aws_transfer_server:

      The endpoint type can be changed, but only while the server is stopped:
      aws transfer stop-server --server-id <id>
      aws transfer update-server --server-id <id> --endpoint-type VPC --endpoint-details VpcId=<vpc>,SubnetIds=<subnets>,SecurityGroupIds=<sgs>
      aws transfer start-server --server-id <id>
      The hostname changes, so partner configurations have to be updated.
  FIX

  tag checkov_id:            'CKV_AWS_164'
  tag checkov_category:      'GENERAL_SECURITY'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'value'
  tag tf_resources:          %w[aws_transfer_server]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/transfer_server#endpoint-type'
  tag nist:                  ['SC-7', 'SC-7 (5)']
  tag nist_r4:               ['SC-7', 'SC-7 (5)']
  tag cci:                   ['CCI-001097', 'CCI-002080']
  tag ksi:                   ['KSI-CNA-NDS']
  tag severity:              'high'
  tag severity_source:       'assessed'
  tag nist_source:           'agent-drafted'
  tag implementation_status: 'implemented'

  assets = aws_api_assets(type: 'aws_transfer_server', regions: scan_regions)

  # A region — or a whole service — that could not be READ is not the same as
  # one with nothing in it. A missing SDK gem, a denied call or an unreachable
  # endpoint all end up here, and without this assertion they render as "no
  # assets" and the control reports Not Applicable: the worst case reported as
  # "does not apply here".
  unreadable = assets.unreadable_regions
  unless unreadable.empty?
    describe "aws_transfer_server enumeration" do
      it 'read every region it attempted' do
        expect(unreadable.map { |r| "#{r[:region]}: #{r[:error]}" }).to be_empty
      end
    end
  end

  # A field the API did not return is nil, and nil is not a failing value:
  # the asset does not express this setting, so it is out of scope for this
  # check rather than in breach of it.
  in_scope = assets.assets(exempt: exempt)
                   .reject { |a| a[:endpoint_type].nil? }

  # `!unreadable.empty?` is load-bearing, and its absence was the bug this line
  # was written to prevent. InSpec's only_if does not merely mark the control
  # skipped: Inspec::Rule.prepare_checks DISCARDS every check and substitutes a
  # single no-op, so the enumeration assertion above never runs. A denied
  # ListX in every region therefore produced zero assets, zero assertions,
  # impact 0.0 and a "skipped" result — which HDF rolls up as Not Applicable.
  # The single most likely real failure of this profile reported as "this rule
  # does not apply here". Same reasoning as `unusable.positive?` in the stock
  # shape.
  applicable = !in_scope.empty? || !unreadable.empty?
  impact 0.7
  impact 0.0 unless applicable
  only_if('no aws_transfer_server in scope expressing this setting') { applicable }

  in_scope.each do |asset|
    describe "aws_transfer_server #{asset[:id]} (#{asset[:account_id]}/#{asset[:region]})" do
      subject { asset[:endpoint_type] }
      it { should be_in ['VPC', 'VPC_ENDPOINT'] }
    end
  end
end
