# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_37 (checkov 3.3.16)
# Applies to:  aws_eks_cluster
# Read with:   aws_eks_clusters -> aws_eks_cluster (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

exempt = (input('exempt_assets') || {})['CKV_AWS_37'] || []

control 'CKV_AWS_37' do
  title 'Ensure Amazon EKS control plane logging is enabled for all log types'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_eks_cluster resources that actually exist, read through the
    stock inspec-aws aws_eks_cluster resource.
  DESC

  desc 'rationale', <<~RATIONALE
    The control plane is where authentication decisions and API
    authorisations are made, and the audit and authenticator logs are the
    only record of them. A cluster with partial logging cannot answer who
    called what after the fact.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: enabled_cluster_log_types contains all of api, audit,
    authenticator, controllerManager and scheduler
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_eks_cluster:

      resource "aws_eks_cluster" "main" {
        name     = "main"
        role_arn = aws_iam_role.cluster.arn
        version  = "1.31"

        enabled_cluster_log_types = [
          "api",
          "audit",
          "authenticator",
          "controllerManager",
          "scheduler",
        ]

        vpc_config {
          subnet_ids = var.private_subnet_ids
        }
      }

    Out of band — aws_eks_cluster:

      aws eks update-cluster-config --name <cluster> --logging '{"clusterLogging":[{"types":["api","audit","authenticator","controllerManager","scheduler"],"enabled":true}]}'
  FIX

  tag checkov_id:            'CKV_AWS_37'
  tag checkov_category:      'KUBERNETES'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'custom'
  tag tf_resources:          %w[aws_eks_cluster]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster'
  tag nist:                  ['AU-2', 'AU-12']
  tag nist_r4:               ['AU-2', 'AU-12']
  tag cci:                   ['CCI-000169', 'CCI-000172']
  tag ksi:                   ['KSI-MLA-LOG']
  tag severity:              'medium'
  tag severity_source:       'assessed'
  tag nist_source:           'agent-drafted'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  ids = aws_eks_clusters.names
  in_scope = ids.reject { |id| checkov_exempt?(id: id, type: 'aws_eks_cluster', rules: exempt) }

  applicable = !in_scope.empty?
  impact 0.5
  impact 0.0 unless applicable
  only_if('no aws_eks_cluster in scope') { applicable }

  in_scope.each do |id|
    describe aws_eks_cluster(cluster_name: id) do
      its('disabled_logging_types') { should satisfy('be unset or empty') { |v| v.nil? || (v.respond_to?(:empty?) && v.empty?) } }
    end
  end
end
