# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_69 (checkov 3.3.16)
# Applies to:  aws_mq_broker
# Read with:   aws_mq_brokers -> aws_mq_broker (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

exempt = (input('exempt_assets') || {})['CKV_AWS_69'] || []

control 'CKV_AWS_69' do
  title 'Ensure MQ Broker is not publicly exposed'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_mq_broker resources that actually exist, read through the stock
    inspec-aws aws_mq_broker resource.
  DESC

  desc 'rationale', <<~RATIONALE
    Ensure MQ Broker is not publicly exposed. Anchors derived from the
    check's networking category, not reviewed control by control.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_mq_broker: publicly_accessible is not True
  CHECK

  desc 'fix', <<~'FIX'
    See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/mq_broker#publicly-accessible
  FIX

  tag checkov_id:            'CKV_AWS_69'
  tag checkov_category:      'NETWORKING'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'negative'
  tag tf_resources:          %w[aws_mq_broker]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/mq_broker#publicly-accessible'
  tag nist:                  ['SC-7', 'SC-7 (5)']
  tag nist_r4:               ['SC-7', 'SC-7 (5)']
  tag cci:                   ['CCI-001097', 'CCI-002080']
  tag ksi:                   ['KSI-CNA-NDS']
  tag severity:              'high'
  tag severity_source:       'assessed'
  tag nist_source:           'category-derived'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  ids = aws_mq_brokers.broker_ids
  in_scope = ids.reject { |id| checkov_exempt?(id: id, type: 'aws_mq_broker', rules: exempt) }

  applicable = !in_scope.empty?
  impact 0.7
  impact 0.0 unless applicable
  only_if('no aws_mq_broker in scope') { applicable }

  in_scope.each do |id|
    describe aws_mq_broker(broker_id: id) do
      its('publicly_accessible') { should eq false }
    end
  end
end
