# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_21 (checkov 3.3.16)
# Applies to:  aws_s3_bucket
# Read with:   aws_s3_buckets -> aws_s3_bucket (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

exempt = (input('exempt_assets') || {})['CKV_AWS_21'] || []

control 'CKV_AWS_21' do
  title 'Ensure all data stored in the S3 bucket have versioning enabled'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_s3_bucket resources that actually exist, read through the stock
    inspec-aws aws_s3_bucket resource.
  DESC

  desc 'rationale', <<~RATIONALE
    Versioning is what makes an accidental or malicious overwrite
    recoverable; without it a delete is final.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: Ensure all data stored in the S3 bucket have
    versioning enabled
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_s3_bucket:

      resource "aws_s3_bucket_versioning" "example" {
        bucket = aws_s3_bucket.example.id

        versioning_configuration {
          status = "Enabled"
        }
      }

    Out of band — aws_s3_bucket:

      aws s3api put-bucket-versioning --bucket <name> \
        --versioning-configuration Status=Enabled
  FIX

  tag checkov_id:            'CKV_AWS_21'
  tag checkov_category:      'BACKUP_AND_RECOVERY'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'graph'
  tag tf_resources:          %w[aws_s3_bucket aws_s3_bucket_versioning]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket'
  tag nist:                  ['CP-9', 'SI-12']
  tag nist_r4:               ['CP-9', 'SI-12']
  tag cci:                   ['CCI-000535', 'CCI-001678']
  tag ksi:                   ['KSI-RPL-RCY']
  tag severity:              'medium'
  tag severity_source:       'assessed'
  tag nist_source:           'reviewed'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  ids = aws_s3_buckets.bucket_names
  in_scope = ids.reject { |id| checkov_exempt?(id: id, type: 'aws_s3_bucket', rules: exempt) }

  applicable = !in_scope.empty?
  impact 0.5
  impact 0.0 unless applicable
  only_if('no aws_s3_bucket in scope') { applicable }

  in_scope.each do |id|
    describe aws_s3_bucket(bucket_name: id) do
      its('has_versioning_enabled?') { should eq true }
    end
  end
end
