# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_322 (checkov 3.3.16)
# Applies to:  aws_elasticache_cluster
# Read with:   aws_elasticache_clusters -> aws_elasticache_cluster (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

exempt = (input('exempt_assets') || {})['CKV_AWS_322'] || []

control 'CKV_AWS_322' do
  title 'Ensure ElastiCache for Redis cache clusters have auto minor version upgrades enabled'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_elasticache_cluster resources that actually exist, read through
    the stock inspec-aws aws_elasticache_cluster resource.
  DESC

  desc 'rationale', <<~RATIONALE
    Ensure ElastiCache for Redis cache clusters have auto minor version
    upgrades enabled. Anchors derived from the check's general security
    category, not reviewed control by control.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_elasticache_cluster: auto_minor_version_upgrade
    is True
  CHECK

  desc 'fix', <<~'FIX'
    See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_cluster#auto-minor-version-upgrade
  FIX

  tag checkov_id:            'CKV_AWS_322'
  tag checkov_category:      'GENERAL_SECURITY'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'value'
  tag tf_resources:          %w[aws_elasticache_cluster]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_cluster#auto-minor-version-upgrade'
  tag nist:                  ['CM-6']
  tag nist_r4:               ['CM-6']
  tag cci:                   ['CCI-000366']
  tag ksi:                   ['KSI-CMT-CFG']
  tag severity:              'medium'
  tag severity_source:       'assessed'
  tag nist_source:           'category-derived'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  ids = aws_elasticache_clusters.ids
  in_scope = ids.reject { |id| checkov_exempt?(id: id, type: 'aws_elasticache_cluster', rules: exempt) }

  applicable = !in_scope.empty?
  impact 0.5
  impact 0.0 unless applicable
  only_if('no aws_elasticache_cluster in scope') { applicable }

  in_scope.each do |id|
    describe aws_elasticache_cluster(elasticache_cluster_identifier: id) do
      its('auto_minor_version_upgrade') { should eq true }
    end
  end
end
