# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_63 (checkov 3.3.16)
# Applies to:  aws_iam_policy
# Read with:   aws_policy_documents — aws_iam_policy → no_wildcard_action
#              predicate: libraries/_policy_document.rb
#              fetch:     tools/policy_specs.yml
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV_AWS_63'] || []

control 'CKV_AWS_63' do
  title 'Ensure no IAM policies documents allow "*" as a statement''s actions'

  desc <<~DESC
    Checkov asserts this against the policy document in the Terraform. This
    profile fetches the policy AWS actually has on each aws_iam_policy and
    evaluates the same question over its statements: no Allow statement
    grants every action.

    This control reads aws_iam_policy. The check also declares
    aws_iam_group_policy, aws_iam_role_policy, aws_iam_user_policy,
    aws_ssoadmin_permission_set_inline_policy, which this mapping does not
    read — those are unassessed here rather than passing.

    Stronger than Checkov: it reads the version IAM is actually serving. A
    policy whose default version was rolled forward in the console after the
    apply has an HCL document that says one thing and a live document that
    says another, and only the live one is enforced.
  DESC

  desc 'rationale', <<~RATIONALE
    An Allow on every action grants every operation in every AWS service the
    account can reach, including the IAM calls that would let the holder
    grant itself anything else. Even scoped to a single resource it defeats
    least privilege, because the set of things it permits grows silently
    every time AWS ships a new API, and nobody re-reviews a policy because a
    service added an action.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_iam_policy and the inline-policy types: no policy
    document has an Allow statement whose Action is the bare '*' or '*:*' (a
    prefixed wildcard such as s3:Get* is not this rule). Checkov flags '*'
    alone and treats a statement with no Effect as an Allow; this also flags
    '*:*' and requires an explicit Allow. Only the customer-managed
    aws_iam_policy documents are read here — iam:ListPolicies is pinned to
    Scope=Local and the four inline-policy types have no enumeration in this
    profile, so they are unassessed rather than passing
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_iam_policy:

      resource "aws_iam_policy" "app_s3" {
        name = "app-s3"

        policy = jsonencode({
          Version = "2012-10-17"
          Statement = [
            {
              Effect   = "Allow"
              Action   = ["s3:GetObject", "s3:PutObject", "s3:DeleteObject"]
              Resource = "${aws_s3_bucket.app.arn}/*"
            },
          ]
        })
      }

    Out of band — aws_iam_policy:

      aws iam create-policy-version --policy-arn <policy-arn> --policy-document file://policy.json --set-as-default

    Note (aws_iam_policy): A managed policy is versioned: create-policy-version
    with --set-as-default is the edit, and the old version stays until you
    delete it (five versions is the limit, so prune with delete-policy-version).
    Enumerate the actions the workload actually calls rather than guessing — IAM
    Access Analyzer's policy generation reads CloudTrail and writes the
    least-privilege document for you (`aws accessanalyzer
    start-policy-generation`). A prefixed wildcard such as s3:Get* does NOT trip
    this control; only the bare '*' and '*:*' do.
  FIX

  tag checkov_id:            'CKV_AWS_63'
  tag checkov_category:      'IAM'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'custom'
  tag tf_resources:          %w[aws_iam_group_policy aws_iam_policy aws_iam_role_policy aws_iam_user_policy aws_ssoadmin_permission_set_inline_policy]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_policy'
  tag policy_source:         'aws_iam_policy'
  tag policy_predicate:      'no_wildcard_action'
  tag nist:                  ['AC-6', 'CM-7']
  tag nist_r4:               ['AC-6', 'CM-7']
  tag cci:                   ['CCI-000225', 'CCI-000381']
  tag ksi:                   ['KSI-IAM-CTL']
  tag severity:              'high'
  tag severity_source:       'assessed'
  tag nist_source:           'agent-drafted'
  tag implementation_status: 'implemented'

  assets = aws_policy_documents(type: 'aws_iam_policy', source: 'aws_iam_policy',
                                predicate: 'no_wildcard_action', regions: scan_regions)

  # A region — or a whole service — that could not be READ is not the same as
  # one with nothing in it. A denied call or an unreachable endpoint ends up
  # here, and without this assertion it renders as "no assets" and the control
  # reports Not Applicable: the worst case reported as "does not apply here".
  unreadable = assets.unreadable_regions
  unless unreadable.empty?
    describe 'aws_iam_policy enumeration' do
      it 'read every region it attempted' do
        expect(unreadable.map { |r| "#{r[:region]}: #{r[:error]}" }).to be_empty
      end
    end
  end

  # An asset whose policy could not be read or parsed has NO VERDICT. It is not
  # in `assets` below, because a nil offender list compared against [] would
  # pass — a denied GetPolicy silently reporting the least-visible estate as the
  # cleanest one. It fails here instead, naming the asset and the reason.
  #
  # An asset with no policy at all is NOT here: that is a real answer and a
  # passing one, recorded on the row as policy_present: false.
  undecidable = assets.undecidable
  unless undecidable.empty?
    describe 'aws_iam_policy policy documents' do
      it 'could all be read and parsed' do
        expect(undecidable).to be_empty
      end
    end
  end

  in_scope = assets.assets(exempt: exempt)

  # Both failure lists keep the control APPLICABLE. only_if suppresses the whole
  # control, including the two assertions above, so a guard that skips when the
  # enumeration broke is no guard at all: it would suppress exactly the case it
  # exists to catch.
  applicable = !in_scope.empty? || !undecidable.empty? || !unreadable.empty?

  # Two statements, not a ternary: InSpec's AST impact collector calls `.value`
  # on the argument node, and a ternary is an IfNode with none — it aborts
  # `check` for the whole profile before a single control runs.
  impact 0.7
  impact 0.0 unless applicable

  only_if('no aws_iam_policy in scope') { applicable }

  in_scope.each do |asset|
    describe "aws_iam_policy #{asset[:id]} (#{asset[:account_id]}/#{asset[:region]})" do
      it 'no Allow statement grants every action' do
        expect(asset[:offenders]).to eq([]),
          "#{asset[:offenders].length} offending statement(s) — " \
          "#{asset[:offenders].join(' | ')}"
      end
    end
  end
end
