# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_142 (checkov 3.3.16)
# Applies to:  aws_redshift_cluster
# Read with:   aws_redshift_clusters -> aws_redshift_cluster (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

exempt = (input('exempt_assets') || {})['CKV_AWS_142'] || []

control 'CKV_AWS_142' do
  title 'Ensure that Redshift cluster is encrypted by KMS'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_redshift_cluster resources that actually exist, read through the
    stock inspec-aws aws_redshift_cluster resource.
  DESC

  desc 'rationale', <<~RATIONALE
    Ensure that Redshift cluster is encrypted by KMS. Anchors derived from
    the check's encryption category, not reviewed control by control.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_redshift_cluster: kms_key_id is CKV_ANY
  CHECK

  desc 'fix', <<~'FIX'
    See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_cluster#kms-key-id
  FIX

  tag checkov_id:            'CKV_AWS_142'
  tag checkov_category:      'ENCRYPTION'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'value'
  tag tf_resources:          %w[aws_redshift_cluster]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_cluster#kms-key-id'
  tag nist:                  ['SC-28', 'SC-28 (1)']
  tag nist_r4:               ['SC-28', 'SC-28 (1)']
  tag cci:                   ['CCI-001199', 'CCI-002475']
  tag ksi:                   ['KSI-SVC-CER']
  tag severity:              'high'
  tag severity_source:       'assessed'
  tag nist_source:           'category-derived'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  ids = aws_redshift_clusters.cluster_identifiers
  in_scope = ids.reject { |id| checkov_exempt?(id: id, type: 'aws_redshift_cluster', rules: exempt) }

  applicable = !in_scope.empty?
  impact 0.7
  impact 0.0 unless applicable
  only_if('no aws_redshift_cluster in scope') { applicable }

  in_scope.each do |id|
    describe aws_redshift_cluster(cluster_identifier: id) do
      its('kms_key_id') { should_not be_empty }
    end
  end
end
