# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_19 (checkov 3.3.16)
# Applies to:  aws_s3_bucket
# Read with:   aws_s3_buckets -> aws_s3_bucket (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV_AWS_19'] || []

control 'CKV_AWS_19' do
  title 'Ensure all data stored in the S3 bucket is securely encrypted at rest'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_s3_bucket resources that actually exist, read through the stock
    inspec-aws aws_s3_bucket resource.
  DESC

  desc 'rationale', <<~RATIONALE
    Default encryption is what makes an object written by any client
    encrypted at rest; without it, encryption depends on every writer
    remembering.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: Ensure all data stored in the S3 bucket is securely
    encrypted at rest
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_s3_bucket:

      resource "aws_s3_bucket_server_side_encryption_configuration" "example" {
        bucket = aws_s3_bucket.example.id

        rule {
          apply_server_side_encryption_by_default {
            sse_algorithm     = "aws:kms"
            kms_master_key_id = aws_kms_key.s3.arn
          }
        }
      }

    Out of band — aws_s3_bucket:

      aws s3api put-bucket-encryption --bucket <name> \
        --server-side-encryption-configuration file://sse.json
  FIX

  tag checkov_id:            'CKV_AWS_19'
  tag checkov_category:      'ENCRYPTION'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'graph'
  tag tf_resources:          %w[aws_s3_bucket aws_s3_bucket_server_side_encryption_configuration]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket'
  tag nist:                  ['SC-28', 'SC-28 (1)']
  tag nist_r4:               ['SC-28', 'SC-28 (1)']
  tag cci:                   ['CCI-001199', 'CCI-002475']
  tag ksi:                   ['KSI-SVC-CER']
  tag severity:              'high'
  tag severity_source:       'assessed'
  tag nist_source:           'reviewed'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  #
  # Every call carries aws_region: a stock resource otherwise reads only the
  # region the connection was built with, and every other region's resources
  # report as absent, which renders Not Applicable rather than unexamined.
  found = checkov_scan_regions(scan_regions).flat_map do |region|
    aws_s3_buckets(aws_region: region).bucket_names.to_a.map { |id| [id, region] }
  end

  # A plural resource whose table is built from the API response returns nil for
  # a column that does not exist, rather than raising. Passing that on gives
  # "`[:x]` must be provided" and kills the control. Blank ids are separated out
  # and asserted on below, so a wrong `ids` column is a visible failure rather
  # than a crash or a silent Not Applicable.
  unusable = found.count { |id, _r| "#{id}".strip.empty? }
  found = found.reject { |id, _r| "#{id}".strip.empty? }
  in_scope = found.reject { |id, _r| checkov_exempt?(id: id, type: 'aws_s3_bucket', rules: exempt) }

  if unusable.positive?
    describe "aws_s3_bucket enumeration" do
      it 'produced usable identifiers' do
        expect(unusable).to eq(0),
          "#{unusable} row(s) had a blank id — the `ids` column in resource_map.yml "          'likely names a field this resource does not expose'
      end
    end
  end

  # `unusable.positive?` keeps the control APPLICABLE when every id came back
  # blank. Without it only_if skips the control, and the wrong-column case this
  # guard exists to catch is exactly the case it would suppress — a Not
  # Applicable that means "the enumeration is broken".
  applicable = !in_scope.empty? || unusable.positive?
  impact 0.7
  impact 0.0 unless applicable
  only_if('no aws_s3_bucket in scope') { applicable }

  in_scope.each do |id, region|
    describe aws_s3_bucket(bucket_name: id, aws_region: region) do
      its('has_default_encryption_enabled?') { should eq true }
    end
  end
end
