# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_134 (checkov 3.3.16)
# Applies to:  aws_elasticache_replication_group
# Read with:   aws_elasticache_replication_groups -> aws_elasticache_replication_group (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

exempt = (input('exempt_assets') || {})['CKV_AWS_134'] || []

control 'CKV_AWS_134' do
  title 'Ensure that Amazon ElastiCache Redis clusters have automatic backup turned on'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_elasticache_replication_group resources that actually exist,
    read through the stock inspec-aws aws_elasticache_replication_group
    resource.
  DESC

  desc 'rationale', <<~RATIONALE
    A retention limit of zero disables backups entirely, so a cache holding
    the only copy of a computed result has no recovery point.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_elasticache_cluster: snapshot_retention_limit is
    not 0
  CHECK

  desc 'fix', <<~'FIX'
    See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_cluster#snapshot-retention-limit
  FIX

  tag checkov_id:            'CKV_AWS_134'
  tag checkov_category:      'BACKUP_AND_RECOVERY'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'negative'
  tag tf_resources:          %w[aws_elasticache_cluster]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs'
  tag nist:                  ['CP-9']
  tag nist_r4:               ['CP-9']
  tag cci:                   ['CCI-000535']
  tag ksi:                   ['KSI-RPL-ABO']
  tag severity:              'medium'
  tag severity_source:       'assessed'
  tag nist_source:           'reviewed'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  ids = aws_elasticache_replication_groups.ids
  in_scope = ids.reject { |id| checkov_exempt?(id: id, type: 'aws_elasticache_replication_group', rules: exempt) }

  applicable = !in_scope.empty?
  impact 0.5
  impact 0.0 unless applicable
  only_if('no aws_elasticache_replication_group in scope') { applicable }

  in_scope.each do |id|
    describe aws_elasticache_replication_group(replication_group_id: id) do
      its('snapshot_retention_limit') { should be > 0 }
    end
  end
end
