# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_153 (checkov 3.3.16)
# Applies to:  aws_autoscaling_group
# Read with:   aws_auto_scaling_groups -> aws_auto_scaling_group (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV_AWS_153'] || []

control 'CKV_AWS_153' do
  title 'Autoscaling groups should supply tags to launch configurations'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_autoscaling_group resources that actually exist, read through
    the stock inspec-aws aws_auto_scaling_group resource.
  DESC

  desc 'rationale', <<~RATIONALE
    Instances launched by an untagged Auto Scaling group appear in the
    account with no owner, environment or data classification, and they
    appear and disappear on their own schedule. Anything that keys off tags
    -- cost attribution, backup selection, patch groups -- silently skips
    them.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: the group declares at least one tag
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_autoscaling_group:

      resource "aws_autoscaling_group" "app" {
        name                = "app"
        min_size            = 2
        max_size            = 6
        desired_capacity    = 2
        vpc_zone_identifier = aws_subnet.private[*].id

        launch_template {
          id      = aws_launch_template.app.id
          version = "$Latest"
        }

        tag {
          key                 = "Owner"
          value               = "platform"
          propagate_at_launch = true
        }

        tag {
          key                 = "Environment"
          value               = "prod"
          propagate_at_launch = true
        }
      }

    Out of band — aws_autoscaling_group:

      aws autoscaling create-or-update-tags --tags ResourceId=app,ResourceType=auto-scaling-group,Key=Owner,Value=platform,PropagateAtLaunch=true
      Instances already running are not retagged; tag them with `aws ec2 create-tags` or let them roll.
  FIX

  tag checkov_id:            'CKV_AWS_153'
  tag checkov_category:      'ENCRYPTION'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'custom'
  tag tf_resources:          %w[aws_autoscaling_group]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group'
  tag nist:                  ['CM-8', 'AU-12']
  tag nist_r4:               ['CM-8', 'AU-12']
  tag cci:                   ['CCI-000366']
  tag ksi:                   ['KSI-CMT-INV']
  tag severity:              'low'
  tag severity_source:       'assessed'
  tag nist_source:           'agent-drafted'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  #
  # Every call carries aws_region: a stock resource otherwise reads only the
  # region the connection was built with, and every other region's resources
  # report as absent, which renders Not Applicable rather than unexamined.
  found = checkov_scan_regions(scan_regions).flat_map do |region|
    aws_auto_scaling_groups(aws_region: region).names.to_a.map { |id| [id, region] }
  end

  # A plural resource whose table is built from the API response returns nil for
  # a column that does not exist, rather than raising. Passing that on gives
  # "`[:x]` must be provided" and kills the control. Blank ids are separated out
  # and asserted on below, so a wrong `ids` column is a visible failure rather
  # than a crash or a silent Not Applicable.
  unusable = found.count { |id, _r| "#{id}".strip.empty? }
  found = found.reject { |id, _r| "#{id}".strip.empty? }
  in_scope = found.reject { |id, _r| checkov_exempt?(id: id, type: 'aws_autoscaling_group', rules: exempt) }

  if unusable.positive?
    describe "aws_autoscaling_group enumeration" do
      it 'produced usable identifiers' do
        expect(unusable).to eq(0),
          "#{unusable} row(s) had a blank id — the `ids` column in resource_map.yml "          'likely names a field this resource does not expose'
      end
    end
  end

  # `unusable.positive?` keeps the control APPLICABLE when every id came back
  # blank. Without it only_if skips the control, and the wrong-column case this
  # guard exists to catch is exactly the case it would suppress — a Not
  # Applicable that means "the enumeration is broken".
  applicable = !in_scope.empty? || unusable.positive?
  impact 0.3
  impact 0.0 unless applicable
  only_if('no aws_autoscaling_group in scope') { applicable }

  in_scope.each do |id, region|
    describe aws_auto_scaling_group(auto_scaling_group_name: id, aws_region: region) do
      its('tags') { should satisfy('be set') { |v| !v.nil? && !(v.respond_to?(:empty?) && v.empty?) } }
    end
  end
end
