# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_305 (checkov 3.3.16)
# Applies to:  aws_cloudfront_distribution
# Read with:   aws_cloudfront_distributions -> aws_cloudfront_distribution (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

exempt = (input('exempt_assets') || {})['CKV_AWS_305'] || []

control 'CKV_AWS_305' do
  title 'Ensure CloudFront distribution has a default root object configured'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_cloudfront_distribution resources that actually exist, read
    through the stock inspec-aws aws_cloudfront_distribution resource.
  DESC

  desc 'rationale', <<~RATIONALE
    Ensure CloudFront distribution has a default root object configured.
    Anchors derived from the check's general security category, not reviewed
    control by control.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_cloudfront_distribution: default_root_object is
    CKV_ANY
  CHECK

  desc 'fix', <<~'FIX'
    See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#default-root-object
  FIX

  tag checkov_id:            'CKV_AWS_305'
  tag checkov_category:      'GENERAL_SECURITY'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'value'
  tag tf_resources:          %w[aws_cloudfront_distribution]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#default-root-object'
  tag nist:                  ['CM-6']
  tag nist_r4:               ['CM-6']
  tag cci:                   ['CCI-000366']
  tag ksi:                   ['KSI-CMT-CFG']
  tag severity:              'medium'
  tag severity_source:       'assessed'
  tag nist_source:           'category-derived'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  ids = aws_cloudfront_distributions.distribution_ids
  in_scope = ids.reject { |id| checkov_exempt?(id: id, type: 'aws_cloudfront_distribution', rules: exempt) }

  applicable = !in_scope.empty?
  impact 0.5
  impact 0.0 unless applicable
  only_if('no aws_cloudfront_distribution in scope') { applicable }

  in_scope.each do |id|
    describe aws_cloudfront_distribution(distribution_id: id) do
      its('default_root_object') { should_not be_empty }
    end
  end
end
