# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_326 (checkov 3.3.16)
# Applies to:  aws_rds_cluster
# Read with:   aws_rds_clusters -> aws_rds_cluster (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

exempt = (input('exempt_assets') || {})['CKV_AWS_326'] || []

control 'CKV_AWS_326' do
  title 'Ensure that RDS Aurora Clusters have backtracking enabled'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_rds_cluster resources that actually exist, read through the
    stock inspec-aws aws_rds_cluster resource.
  DESC

  desc 'rationale', <<~RATIONALE
    Backtrack rewinds a cluster in place after a bad write; without it the
    equivalent recovery is a restore, which is a new endpoint and an outage.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_rds_cluster: backtrack_window is not 0
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_rds_cluster:

      resource "aws_rds_cluster" "example" {
        backtrack_window = 72   # hours
      }

    Out of band — aws_rds_cluster:

      aws rds modify-db-cluster --db-cluster-identifier <id> --backtrack-window 259200 --apply-immediately
  FIX

  tag checkov_id:            'CKV_AWS_326'
  tag checkov_category:      'GENERAL_SECURITY'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'negative'
  tag tf_resources:          %w[aws_rds_cluster]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#backtrack-window'
  tag nist:                  ['CP-10', 'SI-12']
  tag nist_r4:               ['CP-10', 'SI-12']
  tag cci:                   ['CCI-000553']
  tag ksi:                   ['KSI-RPL-RCY']
  tag severity:              'low'
  tag severity_source:       'assessed'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  ids = aws_rds_clusters.cluster_identifier
  in_scope = ids.reject { |id| checkov_exempt?(id: id, type: 'aws_rds_cluster', rules: exempt) }

  applicable = !in_scope.empty?
  impact 0.3
  impact 0.0 unless applicable
  only_if('no aws_rds_cluster in scope') { applicable }

  in_scope.each do |id|
    describe aws_rds_cluster(db_cluster_identifier: id) do
      its('backtrack_window') { should be > 0 }
    end
  end
end
