# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_285 (checkov 3.3.16)
# Applies to:  aws_sfn_state_machine
# Read with:   aws_stepfunctions_state_machines -> aws_stepfunctions_state_machine (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV_AWS_285'] || []

control 'CKV_AWS_285' do
  title 'Ensure State Machine has execution history logging enabled'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_sfn_state_machine resources that actually exist, read through
    the stock inspec-aws aws_stepfunctions_state_machine resource.
  DESC

  desc 'rationale', <<~RATIONALE
    Execution history is retained for ninety days inside Step Functions and
    then gone. Logging with execution data is what puts the input and output
    of each state into a log group that retention policy and alerting can
    reach.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_sfn_state_machine:
    logging_configuration/[0]/include_execution_data is True
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_sfn_state_machine:

      resource "aws_cloudwatch_log_group" "sfn" {
        name              = "/aws/vendedlogs/states/orders"
        retention_in_days = 365
      }

      resource "aws_sfn_state_machine" "orders" {
        name       = "orders"
        role_arn   = aws_iam_role.sfn.arn
        definition = file("${path.module}/orders.asl.json")

        logging_configuration {
          log_destination        = "${aws_cloudwatch_log_group.sfn.arn}:*"
          include_execution_data = true
          level                  = "ALL"
        }
      }

    Out of band — aws_sfn_state_machine:

      aws stepfunctions update-state-machine --state-machine-arn <arn> --logging-configuration level=ALL,includeExecutionData=true,destinations=[{cloudWatchLogsLogGroup={logGroupArn=<log-group-arn>:*}}]

    Note (aws_sfn_state_machine): Execution data includes state input and
    output, so the log group inherits whatever sensitivity the workflow carries
    — set its retention and KMS key accordingly rather than leaving it at the
    defaults.
  FIX

  tag checkov_id:            'CKV_AWS_285'
  tag checkov_category:      'LOGGING'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'value'
  tag tf_resources:          %w[aws_sfn_state_machine]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sfn_state_machine#logging-configuration'
  tag nist:                  ['AU-2', 'AU-3', 'AU-12']
  tag nist_r4:               ['AU-2', 'AU-3', 'AU-12']
  tag cci:                   ['CCI-000130', 'CCI-000169']
  tag ksi:                   ['KSI-MLA-LOG']
  tag severity:              'medium'
  tag severity_source:       'assessed'
  tag nist_source:           'agent-drafted'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  #
  # Every call carries aws_region: a stock resource otherwise reads only the
  # region the connection was built with, and every other region's resources
  # report as absent, which renders Not Applicable rather than unexamined.
  found = checkov_scan_regions(scan_regions).flat_map do |region|
    aws_stepfunctions_state_machines(aws_region: region).state_machine_arns.to_a.map { |id| [id, region] }
  end

  # A plural resource whose table is built from the API response returns nil for
  # a column that does not exist, rather than raising. Passing that on gives
  # "`[:x]` must be provided" and kills the control. Blank ids are separated out
  # and asserted on below, so a wrong `ids` column is a visible failure rather
  # than a crash or a silent Not Applicable.
  unusable = found.count { |id, _r| "#{id}".strip.empty? }
  found = found.reject { |id, _r| "#{id}".strip.empty? }
  in_scope = found.reject { |id, _r| checkov_exempt?(id: id, type: 'aws_sfn_state_machine', rules: exempt) }

  if unusable.positive?
    describe "aws_sfn_state_machine enumeration" do
      it 'produced usable identifiers' do
        expect(unusable).to eq(0),
          "#{unusable} row(s) had a blank id — the `ids` column in resource_map.yml "          'likely names a field this resource does not expose'
      end
    end
  end

  # `unusable.positive?` keeps the control APPLICABLE when every id came back
  # blank. Without it only_if skips the control, and the wrong-column case this
  # guard exists to catch is exactly the case it would suppress — a Not
  # Applicable that means "the enumeration is broken".
  applicable = !in_scope.empty? || unusable.positive?
  impact 0.5
  impact 0.0 unless applicable
  only_if('no aws_sfn_state_machine in scope') { applicable }

  in_scope.each do |id, region|
    describe aws_stepfunctions_state_machine(state_machine_arn: id, aws_region: region) do
      its('logging_configuration.include_execution_data') { should eq true }
    end
  end
end
