# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_333 (checkov 3.3.16)
# Applies to:  aws_ecs_service
# Read with:   aws_ecs_services -> aws_ecs_service (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

exempt = (input('exempt_assets') || {})['CKV_AWS_333'] || []

control 'CKV_AWS_333' do
  title 'Ensure ECS services do not have public IP addresses assigned to them automatically'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_ecs_service resources that actually exist, read through the
    stock inspec-aws aws_ecs_service resource.
  DESC

  desc 'rationale', <<~RATIONALE
    Ensure ECS services do not have public IP addresses assigned to them
    automatically. Anchors derived from the check's logging category, not
    reviewed control by control.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_ecs_service:
    network_configuration/[0]/assign_public_ip is not True
  CHECK

  desc 'fix', <<~'FIX'
    See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_service#network-configuration
  FIX

  tag checkov_id:            'CKV_AWS_333'
  tag checkov_category:      'LOGGING'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'negative'
  tag tf_resources:          %w[aws_ecs_service]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_service#network-configuration'
  tag nist:                  ['AU-2', 'AU-12']
  tag nist_r4:               ['AU-2', 'AU-12']
  tag cci:                   ['CCI-000169', 'CCI-000172']
  tag ksi:                   ['KSI-MLA-LOG']
  tag severity:              'medium'
  tag severity_source:       'assessed'
  tag nist_source:           'category-derived'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  ids = aws_ecs_services.service_names
  in_scope = ids.reject { |id| checkov_exempt?(id: id, type: 'aws_ecs_service', rules: exempt) }

  applicable = !in_scope.empty?
  impact 0.5
  impact 0.0 unless applicable
  only_if('no aws_ecs_service in scope') { applicable }

  in_scope.each do |id|
    describe aws_ecs_service(ecs_service_identifier: id) do
      its('network_configuration') { should eq false }
    end
  end
end
