# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_60 (checkov 3.3.16)
# Applies to:  aws_iam_role
# Status:      PLANNED — no deployed-asset reader exists for aws_iam_role yet.
#
# This control is present so the rule is accounted for. It asserts nothing, and
# it carries no NIST/CCI/KSI tags, because a compliance claim it cannot evaluate
# would be worse than an absent one.

control 'CKV_AWS_60' do
  impact 0.0
  title 'Ensure IAM role allows only specific services or principals to assume it'

  desc <<~DESC
    Catalogued from Checkov 3.3.16, not yet assessed here: no reader
    enumerates aws_iam_role in this profile, so there is nothing to assert against.

    This is a gap, not a pass, and not a Not Applicable. tools/lint_catalog_drift.py
    counts it every run.
  DESC

  desc 'check', <<~CHECK
    Checkov looks for: Ensure IAM role allows only specific services or principals to assume it
  CHECK

  desc 'fix', <<~'FIX'
    See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_role
  FIX

  tag checkov_id:            'CKV_AWS_60'
  tag checkov_category:      'IAM'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'custom'
  tag tf_resources:          %w[aws_iam_role]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_role'
  tag implementation_status: 'planned'

  describe "CKV_AWS_60 — no deployed-asset reader for aws_iam_role" do
    skip 'catalogued from Checkov, not yet implemented in this profile'
  end
end
