# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_304 (checkov 3.3.16)
# Applies to:  aws_secretsmanager_secret_rotation
# Status:      PLANNED — no deployed-asset reader exists for aws_secretsmanager_secret_rotation yet.
#
# This control is present so the rule is accounted for. It asserts nothing, and
# it carries no NIST/CCI/KSI tags, because a compliance claim it cannot evaluate
# would be worse than an absent one.

control 'CKV_AWS_304' do
  impact 0.0
  title 'Ensure Secrets Manager secrets should be rotated within 90 days'

  desc <<~DESC
    Catalogued from Checkov 3.3.16, not yet assessed here: no reader
    enumerates aws_secretsmanager_secret_rotation in this profile, so there is nothing to assert against.

    This is a gap, not a pass, and not a Not Applicable. tools/lint_catalog_drift.py
    counts it every run.
  DESC

  desc 'check', <<~CHECK
    Checkov looks for: Ensure Secrets Manager secrets should be rotated within 90 days
  CHECK

  desc 'fix', <<~'FIX'
    See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/secretsmanager_secret_rotation
  FIX

  tag checkov_id:            'CKV_AWS_304'
  tag checkov_category:      'GENERAL_SECURITY'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'custom'
  tag tf_resources:          %w[aws_secretsmanager_secret_rotation]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/secretsmanager_secret_rotation'
  tag implementation_status: 'planned'

  describe "CKV_AWS_304 — no deployed-asset reader for aws_secretsmanager_secret_rotation" do
    skip 'catalogued from Checkov, not yet implemented in this profile'
  end
end
