# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_51 (checkov 3.3.16)
# Applies to:  aws_ecr_repository
# Read with:   aws_api_assets (declarative spec, tools/api_specs.yml)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV_AWS_51'] || []

control 'CKV_AWS_51' do
  title 'Ensure ECR Image Tags are immutable'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_ecr_repository resources that actually exist, enumerated through
    the declarative API spec.
  DESC

  desc 'rationale', <<~RATIONALE
    A mutable tag means the image running today may not be the image that
    was scanned and approved under that tag.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_ecr_repository: image_tag_mutability is IMMUTABLE
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_ecr_repository:

      resource "aws_ecr_repository" "example" {
        image_tag_mutability = "IMMUTABLE"
      }

    Out of band — aws_ecr_repository:

      aws ecr put-image-tag-mutability --repository-name <name> --image-tag-mutability IMMUTABLE
  FIX

  tag checkov_id:            'CKV_AWS_51'
  tag checkov_category:      'GENERAL_SECURITY'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'value'
  tag tf_resources:          %w[aws_ecr_repository]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecr_repository#image-tag-mutability'
  tag nist:                  ['SR-3', 'SI-7']
  tag nist_r4:               ['SR-3', 'SI-7']
  tag cci:                   ['CCI-005080', 'CCI-002703']
  tag ksi:                   ['KSI-SVC-VRI']
  tag severity:              'medium'
  tag severity_source:       'assessed'
  tag nist_source:           'reviewed'
  tag implementation_status: 'implemented'

  assets = aws_api_assets(type: 'aws_ecr_repository', regions: scan_regions)

  # A region — or a whole service — that could not be READ is not the same as
  # one with nothing in it. A missing SDK gem, a denied call or an unreachable
  # endpoint all end up here, and without this assertion they render as "no
  # assets" and the control reports Not Applicable: the worst case reported as
  # "does not apply here".
  unreadable = assets.unreadable_regions
  unless unreadable.empty?
    describe "aws_ecr_repository enumeration" do
      it 'read every region it attempted' do
        expect(unreadable.map { |r| "#{r[:region]}: #{r[:error]}" }).to be_empty
      end
    end
  end

  # A field the API did not return is nil, and nil is not a failing value:
  # the asset does not express this setting, so it is out of scope for this
  # check rather than in breach of it.
  in_scope = assets.assets(exempt: exempt)
                   .reject { |a| a[:image_tag_mutability].nil? }

  # `|| !unreadable.empty?` is what makes the assertion above reachable. only_if
  # suppresses every describe in the control, including that one, so with
  # `applicable = !in_scope.empty?` alone the case it was written for — the read
  # failed, therefore nothing was enumerated, therefore in_scope is empty —
  # skipped the very test that reports it, and the control rendered Not
  # Applicable with nothing assessed.
  applicable = !in_scope.empty? || !unreadable.empty?
  impact 0.5
  impact 0.0 unless applicable
  only_if('no aws_ecr_repository in scope expressing this setting') { applicable }

  in_scope.each do |asset|
    describe "aws_ecr_repository #{asset[:id]} (#{asset[:account_id]}/#{asset[:region]})" do
      subject { asset[:image_tag_mutability] }
      it { should eq 'IMMUTABLE' }
    end
  end
end
