# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_284 (checkov 3.3.16)
# Applies to:  aws_sfn_state_machine
# Read with:   aws_stepfunctions_state_machines -> aws_stepfunctions_state_machine (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV_AWS_284'] || []

control 'CKV_AWS_284' do
  title 'Ensure State Machine has X-Ray tracing enabled'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_sfn_state_machine resources that actually exist, read through
    the stock inspec-aws aws_stepfunctions_state_machine resource.
  DESC

  desc 'rationale', <<~RATIONALE
    Without tracing, a failed execution shows which state errored but not
    what the downstream call did, so the boundary between the workflow's
    fault and a dependency's fault cannot be established from the record.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_sfn_state_machine:
    tracing_configuration/[0]/enabled is True
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_sfn_state_machine:

      resource "aws_sfn_state_machine" "orders" {
        name       = "orders"
        role_arn   = aws_iam_role.sfn.arn
        definition = file("${path.module}/orders.asl.json")

        tracing_configuration {
          enabled = true
        }
      }

    Out of band — aws_sfn_state_machine:

      aws stepfunctions update-state-machine --state-machine-arn <arn> --tracing-configuration enabled=true

    Note (aws_sfn_state_machine): The state machine's role also needs the X-Ray
    write permissions (xray:PutTraceSegments, xray:PutTelemetryRecords,
    xray:GetSamplingRules, xray:GetSamplingTargets) or no segments are recorded.
  FIX

  tag checkov_id:            'CKV_AWS_284'
  tag checkov_category:      'LOGGING'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'value'
  tag tf_resources:          %w[aws_sfn_state_machine]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sfn_state_machine#tracing-configuration'
  tag nist:                  ['AU-2', 'AU-12']
  tag nist_r4:               ['AU-2', 'AU-12']
  tag cci:                   ['CCI-000169', 'CCI-000172']
  tag ksi:                   ['KSI-MLA-LOG']
  tag severity:              'low'
  tag severity_source:       'assessed'
  tag nist_source:           'agent-drafted'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  #
  # Every call carries aws_region: a stock resource otherwise reads only the
  # region the connection was built with, and every other region's resources
  # report as absent, which renders Not Applicable rather than unexamined.
  #
  # checkov_enumerate does the reading. It flattens a nested id column, tells an
  # unregistered column apart from an account that simply has none of this
  # resource, and hands back anything that stopped it as `problems` rather than
  # as an empty list -- see libraries/_checkov_enumeration.rb.
  problems = []
  found = checkov_scan_regions(scan_regions).flat_map do |region|
    ids, found_problems = checkov_enumerate(
      aws_stepfunctions_state_machines(aws_region: region), :state_machine_arns
    )
    problems.concat(found_problems.map { |p| "#{region}: #{p}" })
    ids.map { |id| [id, region] }
  end

  # Blank ids are separated out and asserted on below rather than filtered away,
  # so a wrong `ids` column is a visible failure and not a silent Not Applicable.
  # `id.nil?` before the interpolation on purpose: a NullResponse answers true to
  # nil? but interpolates to "#<NullResponse:0x...>", which is not blank. The
  # survivors are interpolated rather than `.to_s`'d, because to_s on a
  # NullResponse returns nil and the singular then rejects the argument.
  unusable = found.count { |id, _r| id.nil? || "#{id}".strip.empty? }
  found = found.reject { |id, _r| id.nil? || "#{id}".strip.empty? }
               .map { |id, region| ["#{id}", region] }
  in_scope = found.reject { |id, _r| checkov_exempt?(id: id, type: 'aws_sfn_state_machine', rules: exempt) }

  if unusable.positive? || problems.any?
    describe "aws_sfn_state_machine enumeration" do
      it 'produced usable identifiers' do
        expect(unusable).to eq(0),
          "#{unusable} row(s) had a blank id — the `ids` column in resource_map.yml "\
          'likely names a field this resource does not expose'
      end

      it 'read the assets it set out to read' do
        expect(problems).to be_empty
      end
    end
  end

  # `unusable.positive? || problems.any?` keeps the control APPLICABLE when the
  # enumeration broke. Without it only_if skips the control, and the broken cases
  # these guards exist to catch are exactly the ones it would suppress — a Not
  # Applicable that means "nobody looked".
  applicable = !in_scope.empty? || unusable.positive? || problems.any?
  impact 0.3
  impact 0.0 unless applicable
  only_if('no aws_sfn_state_machine in scope') { applicable }

  in_scope.each do |id, region|
    describe aws_stepfunctions_state_machine(state_machine_arn: id, aws_region: region) do
      its('tracing_configuration.enabled') { should eq true }
    end
  end
end
