# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_378 (checkov 3.3.16)
# Applies to:  aws_lb_target_group
# Read with:   aws_elasticloadbalancingv2_target_groups -> aws_elasticloadbalancingv2_target_group (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV_AWS_378'] || []

control 'CKV_AWS_378' do
  title 'Ensure AWS Load Balancer doesn''t use HTTP protocol'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_lb_target_group resources that actually exist, read through the
    stock inspec-aws aws_elasticloadbalancingv2_target_group resource.
  DESC

  desc 'rationale', <<~RATIONALE
    A target group registered on HTTP carries requests — including the
    session cookies and bearer tokens the load balancer just decrypted — in
    cleartext across the VPC to the target. The perimeter TLS termination
    protects the internet leg only; anything with a foothold on the path
    inside reads the rest.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: Ensure AWS Load Balancer doesn't use HTTP protocol
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_alb_target_group:

      resource "aws_alb_target_group" "example" {
        name     = "example"
        port     = 443
        protocol = "HTTPS"
        vpc_id   = aws_vpc.example.id
      }

    Note (aws_alb_target_group): aws_alb_target_group is an alias of
    aws_lb_target_group; the same fix applies.

    Terraform — aws_lb_target_group:

      resource "aws_lb_target_group" "example" {
        name     = "example"
        port     = 443
        protocol = "HTTPS"
        vpc_id   = aws_vpc.example.id

        health_check {
          protocol = "HTTPS"
          path     = "/healthz"
        }
      }

    Out of band — aws_lb_target_group:

      No in-place fix — a target group's protocol is immutable. Create a new HTTPS target group, register the targets, then update the listener's default action to forward to it.

    Note (aws_lb_target_group): The targets must actually terminate TLS before
    the switch, which usually means a certificate on the instance or task. Where
    the target cannot serve TLS and the segment is accepted risk, exempt the
    target group rather than leaving the finding unexplained.
  FIX

  tag checkov_id:            'CKV_AWS_378'
  tag checkov_category:      'NETWORKING'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'graph'
  tag tf_resources:          %w[aws_alb_listener aws_alb_target_group aws_lb_listener aws_lb_target_group]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_target_group'
  tag nist:                  ['SC-8', 'SC-8 (1)']
  tag nist_r4:               ['SC-8', 'SC-8 (1)']
  tag cci:                   ['CCI-002418', 'CCI-002421']
  tag ksi:                   ['KSI-SVC-CET']
  tag severity:              'medium'
  tag severity_source:       'assessed'
  tag nist_source:           'agent-drafted'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  #
  # Every call carries aws_region: a stock resource otherwise reads only the
  # region the connection was built with, and every other region's resources
  # report as absent, which renders Not Applicable rather than unexamined.
  found = checkov_scan_regions(scan_regions).flat_map do |region|
    aws_elasticloadbalancingv2_target_groups(aws_region: region).target_group_arns.to_a.map { |id| [id, region] }
  end

  # A plural resource whose table is built from the API response returns nil for
  # a column that does not exist, rather than raising. Passing that on gives
  # "`[:x]` must be provided" and kills the control. Blank ids are separated out
  # and asserted on below, so a wrong `ids` column is a visible failure rather
  # than a crash or a silent Not Applicable.
  unusable = found.count { |id, _r| "#{id}".strip.empty? }
  found = found.reject { |id, _r| "#{id}".strip.empty? }
  in_scope = found.reject { |id, _r| checkov_exempt?(id: id, type: 'aws_lb_target_group', rules: exempt) }

  if unusable.positive?
    describe "aws_lb_target_group enumeration" do
      it 'produced usable identifiers' do
        expect(unusable).to eq(0),
          "#{unusable} row(s) had a blank id — the `ids` column in resource_map.yml "          'likely names a field this resource does not expose'
      end
    end
  end

  # `unusable.positive?` keeps the control APPLICABLE when every id came back
  # blank. Without it only_if skips the control, and the wrong-column case this
  # guard exists to catch is exactly the case it would suppress — a Not
  # Applicable that means "the enumeration is broken".
  applicable = !in_scope.empty? || unusable.positive?
  impact 0.5
  impact 0.0 unless applicable
  only_if('no aws_lb_target_group in scope') { applicable }

  in_scope.each do |id, region|
    describe aws_elasticloadbalancingv2_target_group(target_group_arn: id, aws_region: region) do
      its('protocol') { should_not eq 'HTTP' }
    end
  end
end
