# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_130 (checkov 3.3.16)
# Applies to:  aws_subnet
# Status:      PLANNED — no deployed-asset reader exists for aws_subnet yet.
#
# This control is present so the rule is accounted for. It asserts nothing, and
# it carries no NIST/CCI/KSI tags, because a compliance claim it cannot evaluate
# would be worse than an absent one.

control 'CKV_AWS_130' do
  impact 0.0
  title 'Ensure VPC subnets do not assign public IP by default'

  desc <<~DESC
    Catalogued from Checkov 3.3.16, not yet assessed here: no reader
    enumerates aws_subnet in this profile, so there is nothing to assert against.

    This is a gap, not a pass, and not a Not Applicable. tools/lint_catalog_drift.py
    counts it every run.
  DESC

  desc 'check', <<~CHECK
    Checkov looks for: aws_subnet: map_public_ip_on_launch is not True
  CHECK

  desc 'fix', <<~'FIX'
    See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/subnet#map-public-ip-on-launch
  FIX

  tag checkov_id:            'CKV_AWS_130'
  tag checkov_category:      'NETWORKING'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'negative'
  tag tf_resources:          %w[aws_subnet]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/subnet#map-public-ip-on-launch'
  tag implementation_status: 'planned'

  describe "CKV_AWS_130 — no deployed-asset reader for aws_subnet" do
    skip 'catalogued from Checkov, not yet implemented in this profile'
  end
end
