# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_338 (checkov 3.3.16)
# Applies to:  aws_cloudwatch_log_group
# Read with:   aws_api_assets (declarative spec, tools/api_specs.yml)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV_AWS_338'] || []

control 'CKV_AWS_338' do
  title 'Ensure CloudWatch log groups retains logs for at least 1 year'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_cloudwatch_log_group resources that actually exist, enumerated
    through the declarative API spec.
  DESC

  desc 'rationale', <<~RATIONALE
    Intrusions are routinely found months after the fact. A retention window
    shorter than the time it takes to notice means the log lines that would
    explain what happened have already been deleted when the question is
    finally asked.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: retention_in_days is at least 365, or 0 meaning never
    expire
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_cloudwatch_log_group:

      resource "aws_cloudwatch_log_group" "app" {
        name              = "/aws/app/api"
        retention_in_days = 365        # 0 means never expire, also acceptable
        kms_key_id        = aws_kms_key.logs.arn
      }

    Out of band — aws_cloudwatch_log_group:

      aws logs put-retention-policy --log-group-name /aws/app/api --retention-in-days 365

    Note (aws_cloudwatch_log_group): Raising retention does not bring back
    events already aged out; it only governs what is kept from now on.
    CloudWatch Logs accepts a fixed set of values -- 365 and 400 are the ones at
    or just above a year.
  FIX

  tag checkov_id:            'CKV_AWS_338'
  tag checkov_category:      'LOGGING'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'custom'
  tag tf_resources:          %w[aws_cloudwatch_log_group]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_group'
  tag nist:                  ['AU-11', 'SI-12']
  tag nist_r4:               ['AU-11', 'SI-12']
  tag cci:                   ['CCI-000167', 'CCI-001227']
  tag ksi:                   ['KSI-MLA-LOG']
  tag severity:              'medium'
  tag severity_source:       'assessed'
  tag nist_source:           'agent-drafted'
  tag implementation_status: 'implemented'

  assets = aws_api_assets(type: 'aws_cloudwatch_log_group', regions: scan_regions)

  # A region — or a whole service — that could not be READ is not the same as
  # one with nothing in it. A missing SDK gem, a denied call or an unreachable
  # endpoint all end up here, and without this assertion they render as "no
  # assets" and the control reports Not Applicable: the worst case reported as
  # "does not apply here".
  unreadable = assets.unreadable_regions
  unless unreadable.empty?
    describe "aws_cloudwatch_log_group enumeration" do
      it 'read every region it attempted' do
        expect(unreadable.map { |r| "#{r[:region]}: #{r[:error]}" }).to be_empty
      end
    end
  end

  # A field the API did not return is nil, and nil is not a failing value:
  # the asset does not express this setting, so it is out of scope for this
  # check rather than in breach of it.
  in_scope = assets.assets(exempt: exempt)
                   .reject { |a| a[:retention_in_days].nil? }

  # `!unreadable.empty?` keeps the control APPLICABLE when the enumeration could
  # not be read. Without it, the single case the guard above exists for — every
  # region denied, so ZERO rows AND an error — makes `in_scope` empty, only_if
  # skips the whole control, and the guard is skipped along with it: impact 0.0
  # and one skipped result, which HDF rolls up as Not Applicable. A guard that
  # only_if suppresses is not a guard, and this one was suppressed in exactly
  # the state it was written to catch.
  applicable = !in_scope.empty? || !unreadable.empty?
  impact 0.5
  impact 0.0 unless applicable
  only_if('no aws_cloudwatch_log_group in scope expressing this setting') { applicable }

  in_scope.each do |asset|
    describe "aws_cloudwatch_log_group #{asset[:id]} (#{asset[:account_id]}/#{asset[:region]})" do
      subject { asset[:retention_in_days] }
      it { should be > 364 }
    end
  end
end
