# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_28 (checkov 3.3.16)
# Applies to:  aws_dynamodb_table
# Read with:   aws_dynamodb_tables -> aws_dynamodb_table (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV_AWS_28'] || []

control 'CKV_AWS_28' do
  title 'Ensure DynamoDB point in time recovery (backup) is enabled'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_dynamodb_table resources that actually exist, read through the
    stock inspec-aws aws_dynamodb_table resource.
  DESC

  desc 'rationale', <<~RATIONALE
    Ensure DynamoDB point in time recovery (backup) is enabled. Anchors
    derived from the check's backup and recovery category, not reviewed
    control by control.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_dynamodb_table:
    point_in_time_recovery/[0]/enabled is True or true
  CHECK

  desc 'fix', <<~'FIX'
    See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table#point-in-time-recovery
  FIX

  tag checkov_id:            'CKV_AWS_28'
  tag checkov_category:      'BACKUP_AND_RECOVERY'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'value'
  tag tf_resources:          %w[aws_dynamodb_table]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table#point-in-time-recovery'
  tag nist:                  ['CP-9', 'CP-10']
  tag nist_r4:               ['CP-9', 'CP-10']
  tag cci:                   ['CCI-000535', 'CCI-000553']
  tag ksi:                   ['KSI-RPL-ABO']
  tag severity:              'medium'
  tag severity_source:       'assessed'
  tag nist_source:           'category-derived'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  #
  # Every call carries aws_region: a stock resource otherwise reads only the
  # region the connection was built with, and every other region's resources
  # report as absent, which renders Not Applicable rather than unexamined.
  found = checkov_scan_regions(scan_regions).flat_map do |region|
    aws_dynamodb_tables(aws_region: region).table_names.to_a.map { |id| [id, region] }
  end

  # A plural resource whose table is built from the API response returns nil for
  # a column that does not exist, rather than raising. Passing that on gives
  # "`[:x]` must be provided" and kills the control. Blank ids are separated out
  # and asserted on below, so a wrong `ids` column is a visible failure rather
  # than a crash or a silent Not Applicable.
  unusable = found.count { |id, _r| "#{id}".strip.empty? }
  found = found.reject { |id, _r| "#{id}".strip.empty? }
  in_scope = found.reject { |id, _r| checkov_exempt?(id: id, type: 'aws_dynamodb_table', rules: exempt) }

  if unusable.positive?
    describe "aws_dynamodb_table enumeration" do
      it 'produced usable identifiers' do
        expect(unusable).to eq(0),
          "#{unusable} row(s) had a blank id — the `ids` column in resource_map.yml "          'likely names a field this resource does not expose'
      end
    end
  end

  applicable = !in_scope.empty?
  impact 0.5
  impact 0.0 unless applicable
  only_if('no aws_dynamodb_table in scope') { applicable }

  in_scope.each do |id, region|
    describe aws_dynamodb_table(table_name: id, aws_region: region) do
      its('point_in_time_recovery') { should eq true }
    end
  end
end
