# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_130 (checkov 3.3.16)
# Applies to:  aws_subnet
# Read with:   aws_subnets -> aws_subnet (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

exempt = (input('exempt_assets') || {})['CKV_AWS_130'] || []

control 'CKV_AWS_130' do
  title 'Ensure VPC subnets do not assign public IP by default'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_subnet resources that actually exist, read through the stock
    inspec-aws aws_subnet resource.
  DESC

  desc 'rationale', <<~RATIONALE
    Ensure VPC subnets do not assign public IP by default. Anchors derived
    from the check's networking category, not reviewed control by control.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_subnet: map_public_ip_on_launch is not True
  CHECK

  desc 'fix', <<~'FIX'
    See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/subnet#map-public-ip-on-launch
  FIX

  tag checkov_id:            'CKV_AWS_130'
  tag checkov_category:      'NETWORKING'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'negative'
  tag tf_resources:          %w[aws_subnet]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/subnet#map-public-ip-on-launch'
  tag nist:                  ['SC-7', 'SC-7 (5)']
  tag nist_r4:               ['SC-7', 'SC-7 (5)']
  tag cci:                   ['CCI-001097', 'CCI-002080']
  tag ksi:                   ['KSI-CNA-NDS']
  tag severity:              'high'
  tag severity_source:       'assessed'
  tag nist_source:           'category-derived'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  ids = aws_subnets.subnet_ids
  in_scope = ids.reject { |id| checkov_exempt?(id: id, type: 'aws_subnet', rules: exempt) }

  applicable = !in_scope.empty?
  impact 0.7
  impact 0.0 unless applicable
  only_if('no aws_subnet in scope') { applicable }

  in_scope.each do |id|
    describe aws_subnet(subnet_id: id) do
      its('map_public_ip_on_launch') { should eq false }
    end
  end
end
