# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_218 (checkov 3.3.16)
# Applies to:  aws_cloudsearch_domain
# Status:      PLANNED — no deployed-asset reader exists for aws_cloudsearch_domain yet.
#
# This control is present so the rule is accounted for. It asserts nothing, and
# it carries no NIST/CCI/KSI tags, because a compliance claim it cannot evaluate
# would be worse than an absent one.

control 'CKV_AWS_218' do
  impact 0.0
  title 'Ensure that CloudSearch is using latest TLS'

  desc <<~DESC
    Catalogued from Checkov 3.3.16, not yet assessed here: no reader
    enumerates aws_cloudsearch_domain in this profile, so there is nothing to assert against.

    This is a gap, not a pass, and not a Not Applicable. tools/lint_catalog_drift.py
    counts it every run.
  DESC

  desc 'check', <<~CHECK
    Checkov looks for: aws_cloudsearch_domain: endpoint_options/[0]/tls_security_policy is Policy-Min-TLS-1-2-2019-07
  CHECK

  desc 'fix', <<~'FIX'
    See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudsearch_domain#endpoint-options
  FIX

  tag checkov_id:            'CKV_AWS_218'
  tag checkov_category:      'GENERAL_SECURITY'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'value'
  tag tf_resources:          %w[aws_cloudsearch_domain]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudsearch_domain#endpoint-options'
  tag implementation_status: 'planned'

  describe "CKV_AWS_218 — no deployed-asset reader for aws_cloudsearch_domain" do
    skip 'catalogued from Checkov, not yet implemented in this profile'
  end
end
