# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_56 (checkov 3.3.16)
# Applies to:  aws_s3_bucket_public_access_block
# Status:      PLANNED — no deployed-asset reader exists for aws_s3_bucket_public_access_block yet.
#
# This control is present so the rule is accounted for. It asserts nothing, and
# it carries no NIST/CCI/KSI tags, because a compliance claim it cannot evaluate
# would be worse than an absent one.

control 'CKV_AWS_56' do
  impact 0.0
  title 'Ensure S3 bucket has \'restrict_public_buckets\' enabled'

  desc <<~DESC
    Catalogued from Checkov 3.3.16, not yet assessed here: no reader
    enumerates aws_s3_bucket_public_access_block in this profile, so there is nothing to assert against.

    This is a gap, not a pass, and not a Not Applicable. tools/lint_catalog_drift.py
    counts it every run.
  DESC

  desc 'check', <<~CHECK
    Checkov looks for: aws_s3_bucket_public_access_block: restrict_public_buckets is True
  CHECK

  desc 'fix', <<~'FIX'
    See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_public_access_block#restrict-public-buckets
  FIX

  tag checkov_id:            'CKV_AWS_56'
  tag checkov_category:      'GENERAL_SECURITY'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'value'
  tag tf_resources:          %w[aws_s3_bucket_public_access_block]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_public_access_block#restrict-public-buckets'
  tag implementation_status: 'planned'

  describe "CKV_AWS_56 — no deployed-asset reader for aws_s3_bucket_public_access_block" do
    skip 'catalogued from Checkov, not yet implemented in this profile'
  end
end
