# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_234 (checkov 3.3.16)
# Applies to:  aws_acm_certificate
# Status:      PLANNED — no deployed-asset reader exists for aws_acm_certificate yet.
#
# This control is present so the rule is accounted for. It asserts nothing, and
# it carries no NIST/CCI/KSI tags, because a compliance claim it cannot evaluate
# would be worse than an absent one.

control 'CKV_AWS_234' do
  impact 0.0
  title 'Verify logging preference for ACM certificates'

  desc <<~DESC
    Catalogued from Checkov 3.3.16, not yet assessed here: no reader
    enumerates aws_acm_certificate in this profile, so there is nothing to assert against.

    This is a gap, not a pass, and not a Not Applicable. tools/lint_catalog_drift.py
    counts it every run.
  DESC

  desc 'check', <<~CHECK
    Checkov looks for: aws_acm_certificate: options/[0]/certificate_transparency_logging_preference is ENABLED
  CHECK

  desc 'fix', <<~'FIX'
    See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acm_certificate#options
  FIX

  tag checkov_id:            'CKV_AWS_234'
  tag checkov_category:      'LOGGING'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'value'
  tag tf_resources:          %w[aws_acm_certificate]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acm_certificate#options'
  tag implementation_status: 'planned'

  describe "CKV_AWS_234 — no deployed-asset reader for aws_acm_certificate" do
    skip 'catalogued from Checkov, not yet implemented in this profile'
  end
end
