# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_23 (checkov 3.3.16)
# Applies to:  aws_db_security_group, aws_elasticache_security_group, aws_redshift_security_group, aws_security_group, aws_security_group_rule, aws_vpc_security_group_egress_rule, aws_vpc_security_group_ingress_rule
# Status:      PLANNED — no deployed-asset reader exists for aws_db_security_group, aws_elasticache_security_group, aws_redshift_security_group, aws_security_group, aws_security_group_rule, aws_vpc_security_group_egress_rule, aws_vpc_security_group_ingress_rule yet.
#
# This control is present so the rule is accounted for. It asserts nothing, and
# it carries no NIST/CCI/KSI tags, because a compliance claim it cannot evaluate
# would be worse than an absent one.

control 'CKV_AWS_23' do
  impact 0.0
  title 'Ensure every security group and rule has a description'

  desc <<~DESC
    Catalogued from Checkov 3.3.16, not yet assessed here: no reader
    enumerates aws_db_security_group, aws_elasticache_security_group, aws_redshift_security_group, aws_security_group, aws_security_group_rule, aws_vpc_security_group_egress_rule, aws_vpc_security_group_ingress_rule in this profile, so there is nothing to assert against.

    This is a gap, not a pass, and not a Not Applicable. tools/lint_catalog_drift.py
    counts it every run.
  DESC

  desc 'check', <<~CHECK
    Checkov looks for: Ensure every security group and rule has a description
  CHECK

  desc 'fix', <<~'FIX'
    See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_security_group
  FIX

  tag checkov_id:            'CKV_AWS_23'
  tag checkov_category:      'NETWORKING'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'custom'
  tag tf_resources:          %w[aws_db_security_group aws_elasticache_security_group aws_redshift_security_group aws_security_group aws_security_group_rule aws_vpc_security_group_egress_rule aws_vpc_security_group_ingress_rule]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_security_group'
  tag implementation_status: 'planned'

  describe "CKV_AWS_23 — no deployed-asset reader for aws_db_security_group, aws_elasticache_security_group, aws_redshift_security_group, aws_security_group, aws_security_group_rule, aws_vpc_security_group_egress_rule, aws_vpc_security_group_ingress_rule" do
    skip 'catalogued from Checkov, not yet implemented in this profile'
  end
end
