# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_349 (checkov 3.3.16)
# Applies to:  aws_emr_security_configuration
# Read with:   aws_emr_security_configurations -> aws_emr_security_configuration (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV_AWS_349'] || []

control 'CKV_AWS_349' do
  title 'Ensure EMR Cluster security configuration encrypts local disks'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_emr_security_configuration resources that actually exist, read
    through the stock inspec-aws aws_emr_security_configuration resource.
  DESC

  desc 'rationale', <<~RATIONALE
    EMR spills intermediate results to the instance storage attached to each
    node. Those files hold the same data as the source dataset and survive
    until the node is reclaimed, so the local disks need the same treatment
    as the source store.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: the security configuration enables at-rest encryption
    with a local disk encryption configuration
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_emr_security_configuration:

      resource "aws_emr_security_configuration" "app" {
        name = "app-emr-sec"

        configuration = jsonencode({
          EncryptionConfiguration = {
            EnableAtRestEncryption = true
            AtRestEncryptionConfiguration = {
              LocalDiskEncryptionConfiguration = {
                EncryptionKeyProviderType = "AwsKms"
                AwsKmsKey                 = aws_kms_key.emr.arn
                EnableEbsEncryption       = true
              }
              S3EncryptionConfiguration = {
                EncryptionMode = "SSE-KMS"
                AwsKmsKey      = aws_kms_key.emr.arn
              }
            }
            EnableInTransitEncryption = true
            InTransitEncryptionConfiguration = {
              TLSCertificateConfiguration = {
                CertificateProviderType = "PEM"
                S3Object                = "s3://${aws_s3_bucket.emr.id}/certs.zip"
              }
            }
          }
        })
      }

    Out of band — aws_emr_security_configuration:

      There is no in-place fix. An EMR security configuration is immutable:
      create a replacement and point new clusters at it.
      aws emr create-security-configuration --name app-emr-sec-v2 --security-configuration file://sec.json

    Note (aws_emr_security_configuration): A running cluster keeps the
    configuration it launched with. Changing this requires launching a
    replacement cluster against the new configuration.
  FIX

  tag checkov_id:            'CKV_AWS_349'
  tag checkov_category:      'ENCRYPTION'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'custom'
  tag tf_resources:          %w[aws_emr_security_configuration]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/emr_security_configuration'
  tag nist:                  ['SC-28', 'SC-28 (1)']
  tag nist_r4:               ['SC-28', 'SC-28 (1)']
  tag cci:                   ['CCI-001199', 'CCI-002475']
  tag ksi:                   ['KSI-SVC-CER']
  tag severity:              'high'
  tag severity_source:       'assessed'
  tag nist_source:           'agent-drafted'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  #
  # Every call carries aws_region: a stock resource otherwise reads only the
  # region the connection was built with, and every other region's resources
  # report as absent, which renders Not Applicable rather than unexamined.
  found = checkov_scan_regions(scan_regions).flat_map do |region|
    aws_emr_security_configurations(aws_region: region).security_configuration_names.to_a.map { |id| [id, region] }
  end

  # A plural resource whose table is built from the API response returns nil for
  # a column that does not exist, rather than raising. Passing that on gives
  # "`[:x]` must be provided" and kills the control. Blank ids are separated out
  # and asserted on below, so a wrong `ids` column is a visible failure rather
  # than a crash or a silent Not Applicable.
  unusable = found.count { |id, _r| "#{id}".strip.empty? }
  found = found.reject { |id, _r| "#{id}".strip.empty? }
  in_scope = found.reject { |id, _r| checkov_exempt?(id: id, type: 'aws_emr_security_configuration', rules: exempt) }

  if unusable.positive?
    describe "aws_emr_security_configuration enumeration" do
      it 'produced usable identifiers' do
        expect(unusable).to eq(0),
          "#{unusable} row(s) had a blank id — the `ids` column in resource_map.yml "          'likely names a field this resource does not expose'
      end
    end
  end

  applicable = !in_scope.empty?
  impact 0.7
  impact 0.0 unless applicable
  only_if('no aws_emr_security_configuration in scope') { applicable }

  in_scope.each do |id, region|
    describe aws_emr_security_configuration(security_configuration_name: id, aws_region: region) do
      its('local_disk_encryption') { should eq true }
    end
  end
end
