# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_135 (checkov 3.3.16)
# Applies to:  aws_instance
# Answered by: aws_compute_assets#ebs_optimized
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV_AWS_135'] || []
applies_to   = %w[aws_instance]

control 'CKV_AWS_135' do
  title 'Ensure that EC2 is EBS optimized'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the instances that actually exist.
  DESC

  desc 'rationale', <<~RATIONALE
    Dedicated EBS throughput keeps storage traffic off the shared network
    path, so a noisy neighbour cannot starve the instance of disk I/O.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_instance: ebs_optimized is True
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_instance:

      resource "aws_instance" "app" {
        ami           = var.ami_id
        instance_type = "t3.micro"
        ebs_optimized = true
      }

    Out of band — aws_instance:

      aws ec2 stop-instances --instance-ids <id>
      aws ec2 modify-instance-attribute --instance-id <id> --ebs-optimized
      aws ec2 start-instances --instance-ids <id>

    Note (aws_instance): Requires a stop/start. Most current instance types are
    EBS-optimised by default and cannot be set false.
  FIX

  tag checkov_id:       'CKV_AWS_135'
  tag checkov_category: 'GENERAL_SECURITY'
  tag checkov_version:  '3.3.16'
  tag checkov_kind:     'value'
  tag tf_resources:     %w[aws_instance]
  tag tf_argument:      'ebs_optimized'
  tag tf_docs:          'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#ebs-optimized'
  tag nist:             ['SC-5']
  tag nist_r4:          ['SC-5']
  tag cci:              ['CCI-002385']
  tag ksi:              ['KSI-CNA-CAP']
  tag severity:         'low'
  tag severity_source:  'assessed'

  assets = aws_compute_assets(regions: scan_regions)

  # Only the asset types this check declares, only what the boundary has, and
  # only those that express the setting at all — a launch template has no
  # ebs_optimized, and nil must not read as a passing false.
  in_scope = assets.assets_of(applies_to, exempt: exempt)
                   .reject { |a| a[:ebs_optimized].nil? }

  applicable = !in_scope.empty?

  # Two statements, not a ternary: InSpec's AST impact collector calls `.value`
  # on the argument node, and a ternary is an IfNode with none — it aborts
  # `check` for the whole profile before a single control runs.
  impact 0.3
  impact 0.0 unless applicable

  only_if("no #{applies_to.join(', ')} in scope expressing this setting") { applicable }

  in_scope.each do |asset|
    describe "#{asset[:type]} #{asset[:id]} (#{asset[:account_id]}/#{asset[:region]})" do
      subject { asset[:ebs_optimized] }
      it { should be true }
    end
  end
end
