# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_279 (checkov 3.3.16)
# Applies to:  aws_neptune_cluster_snapshot
# Read with:   aws_api_assets (declarative spec, tools/api_specs.yml)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV_AWS_279'] || []

control 'CKV_AWS_279' do
  title 'Ensure Neptune snapshot is securely encrypted'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_neptune_cluster_snapshot resources that actually exist,
    enumerated through the declarative API spec.
  DESC

  desc 'rationale', <<~RATIONALE
    A snapshot is a full copy of the database that persists after the
    cluster is gone and can be shared to another account. An unencrypted
    snapshot moves that data outside the controls applied to the running
    cluster.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_neptune_cluster_snapshot: storage_encrypted is
    True
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_neptune_cluster_snapshot:

      resource "aws_neptune_cluster_snapshot" "graph" {
        db_cluster_identifier          = aws_neptune_cluster.graph.id
        db_cluster_snapshot_identifier = "graph-snapshot"
      }

      # A snapshot inherits the source cluster's encryption, so the fix is on
      # the cluster, not on the snapshot resource.
      resource "aws_neptune_cluster" "graph" {
        cluster_identifier = "graph"
        engine             = "neptune"
        storage_encrypted  = true
        kms_key_arn        = aws_kms_key.neptune.arn
      }

    Out of band — aws_neptune_cluster_snapshot:

      There is no in-place fix -- a snapshot's encryption cannot be changed.
      Copy it into an encrypted one and delete the unencrypted original:
      aws neptune copy-db-cluster-snapshot --source-db-cluster-snapshot-identifier graph-snapshot --target-db-cluster-snapshot-identifier graph-snapshot-enc --kms-key-id <key-arn>
      aws neptune delete-db-cluster-snapshot --db-cluster-snapshot-identifier graph-snapshot
  FIX

  tag checkov_id:            'CKV_AWS_279'
  tag checkov_category:      'ENCRYPTION'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'value'
  tag tf_resources:          %w[aws_neptune_cluster_snapshot]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/neptune_cluster_snapshot#storage-encrypted'
  tag nist:                  ['SC-28', 'SC-28 (1)']
  tag nist_r4:               ['SC-28', 'SC-28 (1)']
  tag cci:                   ['CCI-001199', 'CCI-002475']
  tag ksi:                   ['KSI-SVC-CER']
  tag severity:              'high'
  tag severity_source:       'assessed'
  tag nist_source:           'agent-drafted'
  tag implementation_status: 'implemented'

  assets = aws_api_assets(type: 'aws_neptune_cluster_snapshot', regions: scan_regions)

  # A field the API did not return is nil, and nil is not a failing value:
  # the asset does not express this setting, so it is out of scope for this
  # check rather than in breach of it.
  in_scope = assets.assets(exempt: exempt)
                   .reject { |a| a[:storage_encrypted].nil? }

  applicable = !in_scope.empty?
  impact 0.7
  impact 0.0 unless applicable
  only_if('no aws_neptune_cluster_snapshot in scope expressing this setting') { applicable }

  in_scope.each do |asset|
    describe "aws_neptune_cluster_snapshot #{asset[:id]} (#{asset[:account_id]}/#{asset[:region]})" do
      subject { asset[:storage_encrypted] }
      it { should eq true }
    end
  end
end
