# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_29 (checkov 3.3.16)
# Applies to:  aws_elasticache_replication_group
# Status:      PLANNED — no deployed-asset reader exists for aws_elasticache_replication_group yet.
#
# This control is present so the rule is accounted for. It asserts nothing, and
# it carries no NIST/CCI/KSI tags, because a compliance claim it cannot evaluate
# would be worse than an absent one.

control 'CKV_AWS_29' do
  impact 0.0
  title 'Ensure all data stored in the ElastiCache Replication Group is securely encrypted at rest'

  desc <<~DESC
    Catalogued from Checkov 3.3.16, not yet assessed here: no reader
    enumerates aws_elasticache_replication_group in this profile, so there is nothing to assert against.

    This is a gap, not a pass, and not a Not Applicable. tools/lint_catalog_drift.py
    counts it every run.
  DESC

  desc 'check', <<~CHECK
    Checkov looks for: aws_elasticache_replication_group: at_rest_encryption_enabled is True
  CHECK

  desc 'fix', <<~'FIX'
    See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_replication_group#at-rest-encryption-enabled
  FIX

  tag checkov_id:            'CKV_AWS_29'
  tag checkov_category:      'ENCRYPTION'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'value'
  tag tf_resources:          %w[aws_elasticache_replication_group]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_replication_group#at-rest-encryption-enabled'
  tag implementation_status: 'planned'

  describe "CKV_AWS_29 — no deployed-asset reader for aws_elasticache_replication_group" do
    skip 'catalogued from Checkov, not yet implemented in this profile'
  end
end
