# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_20 (checkov 3.3.16)
# Applies to:  aws_s3_bucket
# Read with:   aws_s3_buckets -> aws_s3_bucket (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV_AWS_20'] || []

control 'CKV_AWS_20' do
  title 'S3 Bucket has an ACL defined which allows public READ access'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_s3_bucket resources that actually exist, read through the stock
    inspec-aws aws_s3_bucket resource.
  DESC

  desc 'rationale', <<~RATIONALE
    A bucket ACL granting public READ exposes every object to the internet,
    and the exposure is invisible from inside the account.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: S3 Bucket has an ACL defined which allows public READ
    access.
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_s3_bucket:

      resource "aws_s3_bucket_public_access_block" "example" {
        bucket                  = aws_s3_bucket.example.id
        block_public_acls       = true
        ignore_public_acls      = true
        block_public_policy     = true
        restrict_public_buckets = true
      }

    Out of band — aws_s3_bucket:

      aws s3api put-public-access-block --bucket <name> \
        --public-access-block-configuration \
        BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true
  FIX

  tag checkov_id:            'CKV_AWS_20'
  tag checkov_category:      'GENERAL_SECURITY'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'graph'
  tag tf_resources:          %w[aws_s3_bucket aws_s3_bucket_acl]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket'
  tag nist:                  ['AC-3', 'SC-7']
  tag nist_r4:               ['AC-3', 'SC-7']
  tag cci:                   ['CCI-000213', 'CCI-001097']
  tag ksi:                   ['KSI-CNA-NDS']
  tag severity:              'high'
  tag severity_source:       'assessed'
  tag nist_source:           'reviewed'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  #
  # Every call carries aws_region: a stock resource otherwise reads only the
  # region the connection was built with, and every other region's resources
  # report as absent, which renders Not Applicable rather than unexamined.
  #
  # checkov_enumerate does the reading. It flattens a nested id column, tells an
  # unregistered column apart from an account that simply has none of this
  # resource, and hands back anything that stopped it as `problems` rather than
  # as an empty list -- see libraries/_checkov_enumeration.rb.
  problems = []
  found = checkov_scan_regions(scan_regions).flat_map do |region|
    ids, found_problems = checkov_enumerate(
      aws_s3_buckets(aws_region: region), :bucket_names
    )
    problems.concat(found_problems.map { |p| "#{region}: #{p}" })
    ids.map { |id| [id, region] }
  end

  # Blank ids are separated out and asserted on below rather than filtered away,
  # so a wrong `ids` column is a visible failure and not a silent Not Applicable.
  # `id.nil?` before the interpolation on purpose: a NullResponse answers true to
  # nil? but interpolates to "#<NullResponse:0x...>", which is not blank. The
  # survivors are interpolated rather than `.to_s`'d, because to_s on a
  # NullResponse returns nil and the singular then rejects the argument.
  unusable = found.count { |id, _r| id.nil? || "#{id}".strip.empty? }
  found = found.reject { |id, _r| id.nil? || "#{id}".strip.empty? }
               .map { |id, region| ["#{id}", region] }
  in_scope = found.reject { |id, _r| checkov_exempt?(id: id, type: 'aws_s3_bucket', rules: exempt) }

  if unusable.positive? || problems.any?
    describe "aws_s3_bucket enumeration" do
      it 'produced usable identifiers' do
        expect(unusable).to eq(0),
          "#{unusable} row(s) had a blank id — the `ids` column in resource_map.yml "\
          'likely names a field this resource does not expose'
      end

      it 'read the assets it set out to read' do
        expect(problems).to be_empty
      end
    end
  end

  # `unusable.positive? || problems.any?` keeps the control APPLICABLE when the
  # enumeration broke. Without it only_if skips the control, and the broken cases
  # these guards exist to catch are exactly the ones it would suppress — a Not
  # Applicable that means "nobody looked".
  applicable = !in_scope.empty? || unusable.positive? || problems.any?
  impact 0.7
  impact 0.0 unless applicable
  only_if('no aws_s3_bucket in scope') { applicable }

  in_scope.each do |id, region|
    describe aws_s3_bucket(bucket_name: id, aws_region: region) do
      its('public?') { should eq false }
    end
  end
end
