# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_118 (checkov 3.3.16)
# Applies to:  aws_db_instance
# Read with:   aws_rds_instances -> aws_rds_instance (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

exempt = (input('exempt_assets') || {})['CKV_AWS_118'] || []

control 'CKV_AWS_118' do
  title 'Ensure that enhanced monitoring is enabled for Amazon RDS instances'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_db_instance resources that actually exist, read through the
    stock inspec-aws aws_rds_instance resource.
  DESC

  desc 'rationale', <<~RATIONALE
    Enhanced monitoring reads the host's own metrics; without it, a database
    starved of CPU or IO looks identical to one that is merely busy. An
    interval of 0 means disabled.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_db_instance: monitoring_interval is 1 or 5 or 10
    or 15 or 30 or 60; aws_rds_cluster_instance: monitoring_interval is 1 or
    5 or 10 or 15 or 30 or 60
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_db_instance:

      resource "aws_db_instance" "example" {
        monitoring_interval = 30
        monitoring_role_arn = aws_iam_role.rds_monitoring.arn
      }

    Out of band — aws_db_instance:

      aws rds modify-db-instance --db-instance-identifier <id> \
        --monitoring-interval 30 --monitoring-role-arn <role-arn> --apply-immediately
  FIX

  tag checkov_id:            'CKV_AWS_118'
  tag checkov_category:      'LOGGING'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'value'
  tag tf_resources:          %w[aws_db_instance aws_rds_cluster_instance]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#monitoring-interval'
  tag nist:                  ['AU-12', 'SI-4']
  tag nist_r4:               ['AU-12', 'SI-4']
  tag cci:                   ['CCI-000172', 'CCI-002664']
  tag ksi:                   ['KSI-MLA-LOG']
  tag severity:              'low'
  tag severity_source:       'assessed'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  ids = aws_rds_instances.db_instance_identifiers
  in_scope = ids.reject { |id| checkov_exempt?(id: id, type: 'aws_db_instance', rules: exempt) }

  applicable = !in_scope.empty?
  impact 0.3
  impact 0.0 unless applicable
  only_if('no aws_db_instance in scope') { applicable }

  in_scope.each do |id|
    describe aws_rds_instance(id) do
      its('monitoring_interval') { should be > 0 }
    end
  end
end
