# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_257 (checkov 3.3.16)
# Applies to:  aws_codecommit_approval_rule_template
# Status:      PLANNED — no deployed-asset reader exists for aws_codecommit_approval_rule_template yet.
#
# This control is present so the rule is accounted for. It asserts nothing, and
# it carries no NIST/CCI/KSI tags, because a compliance claim it cannot evaluate
# would be worse than an absent one.

control 'CKV_AWS_257' do
  impact 0.0
  title 'Ensure CodeCommit branch changes have at least 2 approvals'

  desc <<~DESC
    Catalogued from Checkov 3.3.16, not yet assessed here: no reader
    enumerates aws_codecommit_approval_rule_template in this profile, so there is nothing to assert against.

    This is a gap, not a pass, and not a Not Applicable. tools/lint_catalog_drift.py
    counts it every run.
  DESC

  desc 'check', <<~CHECK
    Checkov looks for: Ensure CodeCommit branch changes have at least 2 approvals
  CHECK

  desc 'fix', <<~'FIX'
    See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codecommit_approval_rule_template
  FIX

  tag checkov_id:            'CKV_AWS_257'
  tag checkov_category:      'GENERAL_SECURITY'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'custom'
  tag tf_resources:          %w[aws_codecommit_approval_rule_template]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codecommit_approval_rule_template'
  tag implementation_status: 'planned'

  describe "CKV_AWS_257 — no deployed-asset reader for aws_codecommit_approval_rule_template" do
    skip 'catalogued from Checkov, not yet implemented in this profile'
  end
end
