# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_99 (checkov 3.3.16)
# Applies to:  aws_glue_security_configuration
# Status:      PLANNED — no deployed-asset reader exists for aws_glue_security_configuration yet.
#
# This control is present so the rule is accounted for. It asserts nothing, and
# it carries no NIST/CCI/KSI tags, because a compliance claim it cannot evaluate
# would be worse than an absent one.

control 'CKV_AWS_99' do
  impact 0.0
  title 'Ensure Glue Security Configuration Encryption is enabled'

  desc <<~DESC
    Catalogued from Checkov 3.3.16, not yet assessed here: no reader
    enumerates aws_glue_security_configuration in this profile, so there is nothing to assert against.

    This is a gap, not a pass, and not a Not Applicable. tools/lint_catalog_drift.py
    counts it every run.
  DESC

  desc 'check', <<~CHECK
    Checkov looks for: Ensure Glue Security Configuration Encryption is enabled
  CHECK

  desc 'fix', <<~'FIX'
    See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glue_security_configuration
  FIX

  tag checkov_id:            'CKV_AWS_99'
  tag checkov_category:      'ENCRYPTION'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'custom'
  tag tf_resources:          %w[aws_glue_security_configuration]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glue_security_configuration'
  tag implementation_status: 'planned'

  describe "CKV_AWS_99 — no deployed-asset reader for aws_glue_security_configuration" do
    skip 'catalogued from Checkov, not yet implemented in this profile'
  end
end
