# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_175 (checkov 3.3.16)
# Applies to:  aws_waf_web_acl
# Read with:   aws_waf_web_acls -> aws_waf_web_acl (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV_AWS_175'] || []

control 'CKV_AWS_175' do
  title 'Ensure WAF has associated rules'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_waf_web_acl resources that actually exist, read through the
    stock inspec-aws aws_waf_web_acl resource.
  DESC

  desc 'rationale', <<~RATIONALE
    A web ACL with no rules inspects nothing. It is attached, it appears in
    the architecture diagram and it shows up as a control in the SSP, and
    every request reaching the protected resource passes through it
    untouched.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: Ensure WAF has associated rules
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_waf_web_acl:

      resource "aws_waf_web_acl" "app" {
        name        = "app"
        metric_name = "app"

        default_action {
          type = "ALLOW"
        }

        rules {
          priority = 1
          rule_id  = aws_waf_rule.sql_injection.id
          type     = "REGULAR"

          action {
            type = "BLOCK"
          }
        }
      }

    Out of band — aws_waf_web_acl:

      aws waf update-web-acl --web-acl-id <id> --change-token "$(aws waf get-change-token --query ChangeToken --output text)" --updates 'Action=INSERT,ActivatedRule={Priority=1,RuleId=<rule-id>,Action={Type=BLOCK},Type=REGULAR}'

    Note (aws_waf_web_acl): This is the WAF Classic form, because WAF Classic is
    the only WAF type this control can enumerate — wafv2's list call requires a
    Scope argument the enumerator cannot supply. WAF Classic is deprecated: a
    new ACL should be an aws_wafv2_web_acl with at least one rule block (an AWS
    managed rule group is the usual starting point), and this control will NOT
    assess it.
  FIX

  tag checkov_id:            'CKV_AWS_175'
  tag checkov_category:      'APPLICATION_SECURITY'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'custom'
  tag tf_resources:          %w[aws_waf_web_acl aws_wafregional_web_acl aws_wafv2_web_acl]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/waf_web_acl'
  tag nist:                  ['SC-7', 'CM-6']
  tag nist_r4:               ['SC-7', 'CM-6']
  tag cci:                   ['CCI-001097', 'CCI-000366']
  tag ksi:                   ['KSI-CNA-NDS']
  tag severity:              'medium'
  tag severity_source:       'assessed'
  tag nist_source:           'agent-drafted'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  #
  # Every call carries aws_region: a stock resource otherwise reads only the
  # region the connection was built with, and every other region's resources
  # report as absent, which renders Not Applicable rather than unexamined.
  # Global service: the same objects come back from any region, so this is
  # enumerated once rather than once per region.
  found = aws_waf_web_acls.web_acl_ids.to_a.map { |id| [id, nil] }

  # A plural resource whose table is built from the API response returns nil for
  # a column that does not exist, rather than raising. Passing that on gives
  # "`[:x]` must be provided" and kills the control. Blank ids are separated out
  # and asserted on below, so a wrong `ids` column is a visible failure rather
  # than a crash or a silent Not Applicable.
  unusable = found.count { |id, _r| "#{id}".strip.empty? }
  found = found.reject { |id, _r| "#{id}".strip.empty? }
  in_scope = found.reject { |id, _r| checkov_exempt?(id: id, type: 'aws_waf_web_acl', rules: exempt) }

  if unusable.positive?
    describe "aws_waf_web_acl enumeration" do
      it 'produced usable identifiers' do
        expect(unusable).to eq(0),
          "#{unusable} row(s) had a blank id — the `ids` column in resource_map.yml "          'likely names a field this resource does not expose'
      end
    end
  end

  # `unusable.positive?` keeps the control APPLICABLE when every id came back
  # blank. Without it only_if skips the control, and the wrong-column case this
  # guard exists to catch is exactly the case it would suppress — a Not
  # Applicable that means "the enumeration is broken".
  applicable = !in_scope.empty? || unusable.positive?
  impact 0.5
  impact 0.0 unless applicable
  only_if('no aws_waf_web_acl in scope') { applicable }

  in_scope.each do |id, region|
    describe aws_waf_web_acl(web_acl_id: id) do
      its('rules_rule_ids') { should satisfy('be set') { |v| !v.nil? && !(v.respond_to?(:empty?) && v.empty?) } }
    end
  end
end
