# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_23 (checkov 3.3.16)
# Applies to:  aws_security_group_rule
# Read with:   aws_api_assets (declarative spec, tools/api_specs.yml)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV_AWS_23'] || []

control 'CKV_AWS_23' do
  title 'Ensure every security group and rule has a description'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_security_group_rule resources that actually exist, enumerated
    through the declarative API spec.
  DESC

  desc 'rationale', <<~RATIONALE
    An undescribed firewall rule cannot be reviewed. Nobody can say whose it
    is, what it was opened for, or whether the reason still holds, so the
    periodic review that is supposed to close stale openings degrades into a
    guess and the rule survives every review it should not have.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: Ensure every security group and rule has a
    description
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_security_group_rule:

      resource "aws_security_group_rule" "app_https" {
        security_group_id        = aws_security_group.app.id
        description              = "HTTPS from the public ALB only"
        type                     = "ingress"
        protocol                 = "tcp"
        from_port                = 443
        to_port                  = 443
        source_security_group_id = aws_security_group.alb.id
      }

    Out of band — aws_security_group_rule:

      aws ec2 modify-security-group-rules --group-id <sg-id> --security-group-rules 'SecurityGroupRuleId=<sgr-id>,SecurityGroupRule={Description="HTTPS from the public ALB only",IpProtocol=tcp,FromPort=443,ToPort=443,ReferencedGroupId=<sg-id>}'

    Note (aws_security_group_rule): modify-security-group-rules REPLACES the
    whole rule, so every field must be resupplied or it is reset. Read the rule
    with describe-security-group-rules first and echo its current values back
    with the description added. The inline ingress/egress blocks on
    aws_security_group also accept a description, so a group written that way is
    fixable in place too — but the inline blocks and the standalone rule
    resources cannot be mixed on one group.

    Terraform — aws_vpc_security_group_ingress_rule:

      resource "aws_vpc_security_group_ingress_rule" "app_https" {
        security_group_id            = aws_security_group.app.id
        description                  = "HTTPS from the public ALB only"
        ip_protocol                  = "tcp"
        from_port                    = 443
        to_port                      = 443
        referenced_security_group_id = aws_security_group.alb.id
      }

    Note (aws_vpc_security_group_ingress_rule): The
    aws_vpc_security_group_ingress_rule / _egress_rule pair is the current form
    and is what a new rule should use; aws_security_group_rule is retained by
    the provider but is no longer the recommended path. Both carry a per-rule
    description, and both land on the same SecurityGroupRule object this control
    reads, so either satisfies it.
  FIX

  tag checkov_id:            'CKV_AWS_23'
  tag checkov_category:      'NETWORKING'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'custom'
  tag tf_resources:          %w[aws_db_security_group aws_elasticache_security_group aws_redshift_security_group aws_security_group aws_security_group_rule aws_vpc_security_group_egress_rule aws_vpc_security_group_ingress_rule]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group_rule'
  tag nist:                  ['CM-6', 'CM-7', 'CM-7 (1)']
  tag nist_r4:               ['CM-6', 'CM-7', 'CM-7 (1)']
  tag cci:                   ['CCI-000366', 'CCI-000381']
  tag ksi:                   ['KSI-CMT-CFG']
  tag severity:              'low'
  tag severity_source:       'assessed'
  tag nist_source:           'agent-drafted'
  tag implementation_status: 'implemented'

  assets = aws_api_assets(type: 'aws_security_group_rule', regions: scan_regions)

  # A region — or a whole service — that could not be READ is not the same as
  # one with nothing in it. A missing SDK gem, a denied call or an unreachable
  # endpoint all end up here, and without this assertion they render as "no
  # assets" and the control reports Not Applicable: the worst case reported as
  # "does not apply here".
  unreadable = assets.unreadable_regions
  unless unreadable.empty?
    describe "aws_security_group_rule enumeration" do
      it 'read every region it attempted' do
        expect(unreadable.map { |r| "#{r[:region]}: #{r[:error]}" }).to be_empty
      end
    end
  end

  # A nil field is the FAILING state for a presence check, so it is
  # deliberately not filtered out here.
  in_scope = assets.assets(exempt: exempt)

  # `|| !unreadable.empty?` is what makes the assertion above reachable. only_if
  # suppresses every describe in the control, including that one, so with
  # `applicable = !in_scope.empty?` alone the case it was written for — the read
  # failed, therefore nothing was enumerated, therefore in_scope is empty —
  # skipped the very test that reports it, and the control rendered Not
  # Applicable with nothing assessed.
  applicable = !in_scope.empty? || !unreadable.empty?
  impact 0.3
  impact 0.0 unless applicable
  only_if('no aws_security_group_rule in scope expressing this setting') { applicable }

  in_scope.each do |asset|
    describe "aws_security_group_rule #{asset[:id]} (#{asset[:account_id]}/#{asset[:region]})" do
      subject { asset[:description] }
      it { should satisfy('be set') { |v| !v.nil? && !(v.respond_to?(:empty?) && v.empty?) } }
    end
  end
end
