# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_266 (checkov 3.3.16)
# Applies to:  aws_db_snapshot_copy
# Read with:   aws_rds_snapshots -> aws_rds_snapshot (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV_AWS_266'] || []

control 'CKV_AWS_266' do
  title 'Ensure DB Snapshot copy uses CMK'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_db_snapshot_copy resources that actually exist, read through the
    stock inspec-aws aws_rds_snapshot resource.
  DESC

  desc 'rationale', <<~RATIONALE
    A snapshot copy is a second, independently retained image of the
    database. Encrypting it under a managed key keeps the ability to revoke
    access to the copy without deleting it, which is the only lever
    available once a snapshot has been shared or moved to another region.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_db_snapshot_copy: kms_key_id is CKV_ANY
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_db_snapshot_copy:

      resource "aws_db_snapshot_copy" "app" {
        source_db_snapshot_identifier = aws_db_snapshot.app.db_snapshot_arn
        target_db_snapshot_identifier = "app-db-2026-08-30-copy"
        kms_key_id                    = aws_kms_key.rds.arn
      }

    Out of band — aws_db_snapshot_copy:

      aws rds copy-db-snapshot --source-db-snapshot-identifier app-db-2026-08-30 --target-db-snapshot-identifier app-db-2026-08-30-copy --kms-key-id <key-arn>

    Note (aws_db_snapshot_copy): An existing unencrypted snapshot cannot be
    encrypted in place. Copy it with --kms-key-id and delete the unencrypted
    original.
  FIX

  tag checkov_id:            'CKV_AWS_266'
  tag checkov_category:      'ENCRYPTION'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'value'
  tag tf_resources:          %w[aws_db_snapshot_copy]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_snapshot_copy#kms-key-id'
  tag nist:                  ['SC-28', 'SC-28 (1)', 'SC-12']
  tag nist_r4:               ['SC-28', 'SC-28 (1)', 'SC-12']
  tag cci:                   ['CCI-001199', 'CCI-002475']
  tag ksi:                   ['KSI-SVC-CER', 'KSI-SVC-KMG']
  tag severity:              'high'
  tag severity_source:       'assessed'
  tag nist_source:           'agent-drafted'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  #
  # Every call carries aws_region: a stock resource otherwise reads only the
  # region the connection was built with, and every other region's resources
  # report as absent, which renders Not Applicable rather than unexamined.
  #
  # checkov_enumerate does the reading. It flattens a nested id column, tells an
  # unregistered column apart from an account that simply has none of this
  # resource, and hands back anything that stopped it as `problems` rather than
  # as an empty list -- see libraries/_checkov_enumeration.rb.
  problems = []
  found = checkov_scan_regions(scan_regions).flat_map do |region|
    ids, found_problems = checkov_enumerate(
      aws_rds_snapshots(aws_region: region), :db_snapshot_identifiers
    )
    problems.concat(found_problems.map { |p| "#{region}: #{p}" })
    ids.map { |id| [id, region] }
  end

  # Blank ids are separated out and asserted on below rather than filtered away,
  # so a wrong `ids` column is a visible failure and not a silent Not Applicable.
  # `id.nil?` before the interpolation on purpose: a NullResponse answers true to
  # nil? but interpolates to "#<NullResponse:0x...>", which is not blank. The
  # survivors are interpolated rather than `.to_s`'d, because to_s on a
  # NullResponse returns nil and the singular then rejects the argument.
  unusable = found.count { |id, _r| id.nil? || "#{id}".strip.empty? }
  found = found.reject { |id, _r| id.nil? || "#{id}".strip.empty? }
               .map { |id, region| ["#{id}", region] }
  in_scope = found.reject { |id, _r| checkov_exempt?(id: id, type: 'aws_db_snapshot_copy', rules: exempt) }

  if unusable.positive? || problems.any?
    describe "aws_db_snapshot_copy enumeration" do
      it 'produced usable identifiers' do
        expect(unusable).to eq(0),
          "#{unusable} row(s) had a blank id — the `ids` column in resource_map.yml "\
          'likely names a field this resource does not expose'
      end

      it 'read the assets it set out to read' do
        expect(problems).to be_empty
      end
    end
  end

  # `unusable.positive? || problems.any?` keeps the control APPLICABLE when the
  # enumeration broke. Without it only_if skips the control, and the broken cases
  # these guards exist to catch are exactly the ones it would suppress — a Not
  # Applicable that means "nobody looked".
  applicable = !in_scope.empty? || unusable.positive? || problems.any?
  impact 0.7
  impact 0.0 unless applicable
  only_if('no aws_db_snapshot_copy in scope') { applicable }

  in_scope.each do |id, region|
    describe aws_rds_snapshot(db_snapshot_identifier: id, aws_region: region) do
      its('kms_key_id') { should satisfy('be set') { |v| !v.nil? && !(v.respond_to?(:empty?) && v.empty?) } }
    end
  end
end
