# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_157 (checkov 3.3.16)
# Applies to:  aws_db_instance
# Read with:   aws_rds_instances -> aws_rds_instance (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

exempt = (input('exempt_assets') || {})['CKV_AWS_157'] || []

control 'CKV_AWS_157' do
  title 'Ensure that RDS instances have Multi-AZ enabled'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_db_instance resources that actually exist, read through the
    stock inspec-aws aws_rds_instance resource.
  DESC

  desc 'rationale', <<~RATIONALE
    Without Multi-AZ, a single availability-zone failure takes the database
    down with no automatic failover.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_db_instance: multi_az is True
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_db_instance:

      resource "aws_db_instance" "example" {
        multi_az = true
      }

    Out of band — aws_db_instance:

      aws rds modify-db-instance --db-instance-identifier <id> --multi-az --apply-immediately
  FIX

  tag checkov_id:            'CKV_AWS_157'
  tag checkov_category:      'BACKUP_AND_RECOVERY'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'value'
  tag tf_resources:          %w[aws_db_instance]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#multi-az'
  tag nist:                  ['CP-10', 'SC-5']
  tag nist_r4:               ['CP-10', 'SC-5']
  tag cci:                   ['CCI-000553', 'CCI-002385']
  tag ksi:                   ['KSI-RPL-RCY']
  tag severity:              'medium'
  tag severity_source:       'assessed'
  tag nist_source:           'reviewed'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  ids = aws_rds_instances.db_instance_identifiers
  in_scope = ids.reject { |id| checkov_exempt?(id: id, type: 'aws_db_instance', rules: exempt) }

  applicable = !in_scope.empty?
  impact 0.5
  impact 0.0 unless applicable
  only_if('no aws_db_instance in scope') { applicable }

  in_scope.each do |id|
    describe aws_rds_instance(id) do
      its('multi_az') { should eq true }
    end
  end
end
