# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_69 (checkov 3.3.16)
# Applies to:  aws_mq_broker
# Status:      PLANNED — no deployed-asset reader exists for aws_mq_broker yet.
#
# This control is present so the rule is accounted for. It asserts nothing, and
# it carries no NIST/CCI/KSI tags, because a compliance claim it cannot evaluate
# would be worse than an absent one.

control 'CKV_AWS_69' do
  impact 0.0
  title 'Ensure MQ Broker is not publicly exposed'

  desc <<~DESC
    Catalogued from Checkov 3.3.16, not yet assessed here: no reader
    enumerates aws_mq_broker in this profile, so there is nothing to assert against.

    This is a gap, not a pass, and not a Not Applicable. tools/lint_catalog_drift.py
    counts it every run.
  DESC

  desc 'check', <<~CHECK
    Checkov looks for: aws_mq_broker: publicly_accessible is not True
  CHECK

  desc 'fix', <<~'FIX'
    See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/mq_broker#publicly-accessible
  FIX

  tag checkov_id:            'CKV_AWS_69'
  tag checkov_category:      'NETWORKING'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'negative'
  tag tf_resources:          %w[aws_mq_broker]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/mq_broker#publicly-accessible'
  tag implementation_status: 'planned'

  describe "CKV_AWS_69 — no deployed-asset reader for aws_mq_broker" do
    skip 'catalogued from Checkov, not yet implemented in this profile'
  end
end
