# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_58 (checkov 3.3.16)
# Applies to:  aws_eks_cluster
# Read with:   aws_eks_clusters -> aws_eks_cluster (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV_AWS_58'] || []

control 'CKV_AWS_58' do
  title 'Ensure EKS Cluster has Secrets Encryption Enabled'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_eks_cluster resources that actually exist, read through the
    stock inspec-aws aws_eks_cluster resource.
  DESC

  desc 'rationale', <<~RATIONALE
    Without envelope encryption a Kubernetes Secret is stored in etcd as
    base64, which is an encoding and not a protection. Anyone who can read
    the cluster's backing store, or restore it from a backup, reads every
    credential in it.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_eks_cluster: encryption_config/[0]/resources is
    ['secrets']
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_eks_cluster:

      resource "aws_eks_cluster" "main" {
        name     = "main"
        role_arn = aws_iam_role.cluster.arn
        version  = "1.31"

        encryption_config {
          resources = ["secrets"]

          provider {
            key_arn = aws_kms_key.eks.arn
          }
        }

        vpc_config {
          subnet_ids = var.private_subnet_ids
        }
      }

    Out of band — aws_eks_cluster:

      aws eks associate-encryption-config --cluster-name <cluster> --encryption-config '[{"resources":["secrets"],"provider":{"keyArn":"<key-arn>"}}]'

    Note (aws_eks_cluster): Association is one-way and cannot be undone or
    repointed at another key, and existing Secrets are only re-encrypted when
    they are next written — run a rewrite of every Secret after associating.
  FIX

  tag checkov_id:            'CKV_AWS_58'
  tag checkov_category:      'KUBERNETES'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'value'
  tag tf_resources:          %w[aws_eks_cluster]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#encryption-config'
  tag nist:                  ['SC-28', 'SC-28 (1)']
  tag nist_r4:               ['SC-28', 'SC-28 (1)']
  tag cci:                   ['CCI-001199', 'CCI-002475']
  tag ksi:                   ['KSI-SVC-CER']
  tag severity:              'high'
  tag severity_source:       'assessed'
  tag nist_source:           'agent-drafted'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  #
  # Every call carries aws_region: a stock resource otherwise reads only the
  # region the connection was built with, and every other region's resources
  # report as absent, which renders Not Applicable rather than unexamined.
  #
  # checkov_enumerate does the reading. It flattens a nested id column, tells an
  # unregistered column apart from an account that simply has none of this
  # resource, and hands back anything that stopped it as `problems` rather than
  # as an empty list -- see libraries/_checkov_enumeration.rb.
  problems = []
  found = checkov_scan_regions(scan_regions).flat_map do |region|
    ids, found_problems = checkov_enumerate(
      aws_eks_clusters(aws_region: region), :names, exclude: { statuses: ['CREATING', 'DELETING'] }
    )
    problems.concat(found_problems.map { |p| "#{region}: #{p}" })
    ids.map { |id| [id, region] }
  end

  # Blank ids are separated out and asserted on below rather than filtered away,
  # so a wrong `ids` column is a visible failure and not a silent Not Applicable.
  # `id.nil?` before the interpolation on purpose: a NullResponse answers true to
  # nil? but interpolates to "#<NullResponse:0x...>", which is not blank. The
  # survivors are interpolated rather than `.to_s`'d, because to_s on a
  # NullResponse returns nil and the singular then rejects the argument.
  unusable = found.count { |id, _r| id.nil? || "#{id}".strip.empty? }
  found = found.reject { |id, _r| id.nil? || "#{id}".strip.empty? }
               .map { |id, region| ["#{id}", region] }
  in_scope = found.reject { |id, _r| checkov_exempt?(id: id, type: 'aws_eks_cluster', rules: exempt) }

  if unusable.positive? || problems.any?
    describe "aws_eks_cluster enumeration" do
      it 'produced usable identifiers' do
        expect(unusable).to eq(0),
          "#{unusable} row(s) had a blank id — the `ids` column in resource_map.yml "\
          'likely names a field this resource does not expose'
      end

      it 'read the assets it set out to read' do
        expect(problems).to be_empty
      end
    end
  end

  # `unusable.positive? || problems.any?` keeps the control APPLICABLE when the
  # enumeration broke. Without it only_if skips the control, and the broken cases
  # these guards exist to catch are exactly the ones it would suppress — a Not
  # Applicable that means "nobody looked".
  applicable = !in_scope.empty? || unusable.positive? || problems.any?
  impact 0.7
  impact 0.0 unless applicable
  only_if('no aws_eks_cluster in scope') { applicable }

  in_scope.each do |id, region|
    describe aws_eks_cluster(cluster_name: id, aws_region: region) do
      its('encryption_config') { should satisfy('be set') { |v| !v.nil? && !(v.respond_to?(:empty?) && v.empty?) } }
    end
  end
end
