# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_293 (checkov 3.3.16)
# Applies to:  aws_db_instance
# Read with:   aws_rds_instances -> aws_rds_instance (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

exempt = (input('exempt_assets') || {})['CKV_AWS_293'] || []

control 'CKV_AWS_293' do
  title 'Ensure that AWS database instances have deletion protection enabled'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_db_instance resources that actually exist, read through the
    stock inspec-aws aws_rds_instance resource.
  DESC

  desc 'rationale', <<~RATIONALE
    Deletion protection is the difference between a mistyped identifier
    costing an argument and costing the database.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_db_instance: deletion_protection is True
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_db_instance:

      resource "aws_db_instance" "example" {
        deletion_protection = true
      }

    Out of band — aws_db_instance:

      aws rds modify-db-instance --db-instance-identifier <id> --deletion-protection --apply-immediately
  FIX

  tag checkov_id:            'CKV_AWS_293'
  tag checkov_category:      'GENERAL_SECURITY'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'value'
  tag tf_resources:          %w[aws_db_instance]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#deletion-protection'
  tag nist:                  ['CP-9', 'SI-12']
  tag nist_r4:               ['CP-9', 'SI-12']
  tag cci:                   ['CCI-000535', 'CCI-001678']
  tag ksi:                   ['KSI-RPL-ABO']
  tag severity:              'low'
  tag severity_source:       'assessed'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  ids = aws_rds_instances.db_instance_identifiers
  in_scope = ids.reject { |id| checkov_exempt?(id: id, type: 'aws_db_instance', rules: exempt) }

  applicable = !in_scope.empty?
  impact 0.3
  impact 0.0 unless applicable
  only_if('no aws_db_instance in scope') { applicable }

  in_scope.each do |id|
    describe aws_rds_instance(id) do
      its('deletion_protection') { should eq true }
    end
  end
end
