# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_337 (checkov 3.3.16)
# Applies to:  aws_ssm_parameter
# Read with:   aws_ssm_parameters -> aws_ssm_parameter (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

exempt = (input('exempt_assets') || {})['CKV_AWS_337'] || []

control 'CKV_AWS_337' do
  title 'Ensure SSM parameters are using KMS CMK'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_ssm_parameter resources that actually exist, read through the
    stock inspec-aws aws_ssm_parameter resource.
  DESC

  desc 'rationale', <<~RATIONALE
    Ensure SSM parameters are using KMS CMK. Anchors derived from the
    check's encryption category, not reviewed control by control.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_ssm_parameter: key_id is CKV_ANY
  CHECK

  desc 'fix', <<~'FIX'
    See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_parameter#key-id
  FIX

  tag checkov_id:            'CKV_AWS_337'
  tag checkov_category:      'ENCRYPTION'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'value'
  tag tf_resources:          %w[aws_ssm_parameter]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_parameter#key-id'
  tag nist:                  ['SC-28', 'SC-28 (1)']
  tag nist_r4:               ['SC-28', 'SC-28 (1)']
  tag cci:                   ['CCI-001199', 'CCI-002475']
  tag ksi:                   ['KSI-SVC-CER']
  tag severity:              'high'
  tag severity_source:       'assessed'
  tag nist_source:           'category-derived'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  ids = aws_ssm_parameters.names
  in_scope = ids.reject { |id| checkov_exempt?(id: id, type: 'aws_ssm_parameter', rules: exempt) }

  applicable = !in_scope.empty?
  impact 0.7
  impact 0.0 unless applicable
  only_if('no aws_ssm_parameter in scope') { applicable }

  in_scope.each do |id|
    describe aws_ssm_parameter(name: id) do
      its('key_id') { should_not be_empty }
    end
  end
end
