# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_173 (checkov 3.3.16)
# Applies to:  aws_lambda_function
# Read with:   aws_api_assets (declarative spec, tools/api_specs.yml)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV_AWS_173'] || []

control 'CKV_AWS_173' do
  title 'Check encryption settings for Lambda environmental variable'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_lambda_function resources that actually exist, enumerated
    through the declarative API spec.
  DESC

  desc 'rationale', <<~RATIONALE
    Environment variables hold configuration that is frequently credentials;
    with the default key they are encrypted with a key the account cannot
    rotate or revoke.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: Check encryption settings for Lambda environmental
    variable
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_lambda_function:

      resource "aws_lambda_function" "example" {
        kms_key_arn = aws_kms_key.lambda.arn
      }

    Out of band — aws_lambda_function:

      aws lambda update-function-configuration --function-name <name> --kms-key-arn <key-arn>
  FIX

  tag checkov_id:            'CKV_AWS_173'
  tag checkov_category:      'ENCRYPTION'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'custom'
  tag tf_resources:          %w[aws_lambda_function]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function'
  tag nist:                  ['SC-28', 'SC-28 (1)']
  tag nist_r4:               ['SC-28', 'SC-28 (1)']
  tag cci:                   ['CCI-001199', 'CCI-002475']
  tag ksi:                   ['KSI-SVC-CER']
  tag severity:              'medium'
  tag severity_source:       'assessed'
  tag nist_source:           'reviewed'
  tag implementation_status: 'implemented'

  assets = aws_api_assets(type: 'aws_lambda_function', regions: scan_regions)

  # A region — or a whole service — that could not be READ is not the same as
  # one with nothing in it. A missing SDK gem, a denied call or an unreachable
  # endpoint all end up here, and without this assertion they render as "no
  # assets" and the control reports Not Applicable: the worst case reported as
  # "does not apply here".
  unreadable = assets.unreadable_regions
  unless unreadable.empty?
    describe "aws_lambda_function enumeration" do
      it 'read every region it attempted' do
        expect(unreadable.map { |r| "#{r[:region]}: #{r[:error]}" }).to be_empty
      end
    end
  end

  # A nil field is the FAILING state for a presence check, so it is
  # deliberately not filtered out here.
  in_scope = assets.assets(exempt: exempt)

  # `|| !unreadable.empty?` is what makes the assertion above reachable. only_if
  # suppresses every describe in the control, including that one, so with
  # `applicable = !in_scope.empty?` alone the case it was written for — the read
  # failed, therefore nothing was enumerated, therefore in_scope is empty —
  # skipped the very test that reports it, and the control rendered Not
  # Applicable with nothing assessed.
  applicable = !in_scope.empty? || !unreadable.empty?
  impact 0.5
  impact 0.0 unless applicable
  only_if('no aws_lambda_function in scope expressing this setting') { applicable }

  in_scope.each do |asset|
    describe "aws_lambda_function #{asset[:id]} (#{asset[:account_id]}/#{asset[:region]})" do
      subject { asset[:kms_key_arn] }
      it { should satisfy('be set') { |v| !v.nil? && !(v.respond_to?(:empty?) && v.empty?) } }
    end
  end
end
