# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_136 (checkov 3.3.16)
# Applies to:  aws_ecr_repository
# Read with:   aws_api_assets (declarative spec, tools/api_specs.yml)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV_AWS_136'] || []

control 'CKV_AWS_136' do
  title 'Ensure that ECR repositories are encrypted using KMS'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_ecr_repository resources that actually exist, enumerated through
    the declarative API spec.
  DESC

  desc 'rationale', <<~RATIONALE
    The default AES256 encryption uses a key the account does not control;
    KMS makes the key auditable and revocable.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_ecr_repository:
    encryption_configuration/[0]/encryption_type is KMS
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_ecr_repository:

      resource "aws_ecr_repository" "example" {
        encryption_configuration {
          encryption_type = "KMS"
          kms_key         = aws_kms_key.ecr.arn
        }
      }

    Out of band — aws_ecr_repository:

      Set at creation; encryption configuration cannot be changed on an existing repository.
  FIX

  tag checkov_id:            'CKV_AWS_136'
  tag checkov_category:      'ENCRYPTION'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'value'
  tag tf_resources:          %w[aws_ecr_repository]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecr_repository#encryption-configuration'
  tag nist:                  ['SC-28', 'SC-28 (1)']
  tag nist_r4:               ['SC-28', 'SC-28 (1)']
  tag cci:                   ['CCI-001199', 'CCI-002475']
  tag ksi:                   ['KSI-SVC-CER']
  tag severity:              'medium'
  tag severity_source:       'assessed'
  tag nist_source:           'reviewed'
  tag implementation_status: 'implemented'

  assets = aws_api_assets(type: 'aws_ecr_repository', regions: scan_regions)

  # A region — or a whole service — that could not be READ is not the same as
  # one with nothing in it. A missing SDK gem, a denied call or an unreachable
  # endpoint all end up here, and without this assertion they render as "no
  # assets" and the control reports Not Applicable: the worst case reported as
  # "does not apply here".
  unreadable = assets.unreadable_regions
  unless unreadable.empty?
    describe "aws_ecr_repository enumeration" do
      it 'read every region it attempted' do
        expect(unreadable.map { |r| "#{r[:region]}: #{r[:error]}" }).to be_empty
      end
    end
  end

  # A blank id means the spec's `id` column names a member this response does
  # not carry. tools/lint_resource_map.py cannot see that statically, and the
  # damage is silent: every describe is titled with a blank where the identity
  # belongs, and `exempt_assets` entries keyed by id stop matching. Asserted,
  # not filtered — filtering renders Not Applicable, which is the same silence.
  enumerated = assets.assets(exempt: exempt)
  unusable = enumerated.count { |a| "#{a[:id]}".strip.empty? }
  if unusable.positive?
    describe "aws_ecr_repository enumeration" do
      it 'produced usable identifiers' do
        expect(unusable).to eq(0),
          "#{unusable} row(s) had a blank id — the `id` for aws_ecr_repository in "\
          'tools/api_specs.yml likely names a member this API does not return'
      end
    end
  end

  # A field the API did not return is nil, and nil is not a failing value:
  # the asset does not express this setting, so it is out of scope for this
  # check rather than in breach of it.
  in_scope = enumerated
                        .reject { |a| a[:encryption_type].nil? }

  # `applicable` is a CLAIM that this rule does not apply to this boundary, and
  # only an enumeration that succeeded can earn it. An unreadable region or a
  # blank id column keeps the control applicable so the assertions above are
  # reported; without that, only_if skips the whole control — the two guards
  # included — and the worst case, "every region denied", renders as Not
  # Applicable. The stock template already carries the `unusable` half of this.
  applicable = !in_scope.empty? || !unreadable.empty? || unusable.positive?
  impact 0.5
  impact 0.0 unless applicable
  only_if('no aws_ecr_repository in scope expressing this setting') { applicable }

  in_scope.each do |asset|
    describe "aws_ecr_repository #{asset[:id]} (#{asset[:account_id]}/#{asset[:region]})" do
      subject { asset[:encryption_type] }
      it { should eq 'KMS' }
    end
  end
end
