# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_278 (checkov 3.3.16)
# Applies to:  aws_memorydb_snapshot
# Read with:   aws_api_assets (declarative spec, tools/api_specs.yml)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV_AWS_278'] || []

control 'CKV_AWS_278' do
  title 'Ensure MemoryDB snapshot is encrypted by KMS using a customer managed Key (CMK)'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_memorydb_snapshot resources that actually exist, enumerated
    through the declarative API spec.
  DESC

  desc 'rationale', <<~RATIONALE
    A snapshot outlives the cluster it came from and holds the same data.
    Under an AWS-owned key the account cannot audit who used the key, cannot
    revoke it, and cannot prove the snapshot became unreadable when it was
    retired.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_memorydb_snapshot: kms_key_arn is CKV_ANY
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_memorydb_snapshot:

      resource "aws_memorydb_snapshot" "nightly" {
        cluster_name = aws_memorydb_cluster.cache.name
        name         = "cache-nightly"
        kms_key_arn  = aws_kms_key.memorydb.arn
      }

    Out of band — aws_memorydb_snapshot:

      aws memorydb copy-snapshot --source-snapshot-name <name> --target-snapshot-name <name>-cmk --kms-key-id <key-arn>

    Note (aws_memorydb_snapshot): A snapshot's key cannot be changed in place.
    The fix is to copy it under the customer-managed key and delete the
    original; for scheduled snapshots, set kms_key_arn on the cluster so future
    ones inherit it.
  FIX

  tag checkov_id:            'CKV_AWS_278'
  tag checkov_category:      'ENCRYPTION'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'value'
  tag tf_resources:          %w[aws_memorydb_snapshot]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/memorydb_snapshot#kms-key-arn'
  tag nist:                  ['SC-28', 'SC-28 (1)']
  tag nist_r4:               ['SC-28', 'SC-28 (1)']
  tag cci:                   ['CCI-001199', 'CCI-002475']
  tag ksi:                   ['KSI-SVC-KMG']
  tag severity:              'medium'
  tag severity_source:       'assessed'
  tag nist_source:           'agent-drafted'
  tag implementation_status: 'implemented'

  assets = aws_api_assets(type: 'aws_memorydb_snapshot', regions: scan_regions)

  # A nil field is the FAILING state for a presence check, so it is
  # deliberately not filtered out here.
  in_scope = assets.assets(exempt: exempt)

  applicable = !in_scope.empty?
  impact 0.5
  impact 0.0 unless applicable
  only_if('no aws_memorydb_snapshot in scope expressing this setting') { applicable }

  in_scope.each do |asset|
    describe "aws_memorydb_snapshot #{asset[:id]} (#{asset[:account_id]}/#{asset[:region]})" do
      subject { asset[:kms_key_arn] }
      it { should satisfy('be set') { |v| !v.nil? && !(v.respond_to?(:empty?) && v.empty?) } }
    end
  end
end
