# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_17 (checkov 3.3.16)
# Applies to:  aws_db_instance
# Read with:   aws_rds_instances -> aws_rds_instance (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

exempt = (input('exempt_assets') || {})['CKV_AWS_17'] || []

control 'CKV_AWS_17' do
  title 'Ensure all data stored in RDS is not publicly accessible'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_db_instance resources that actually exist, read through the
    stock inspec-aws aws_rds_instance resource.
  DESC

  desc 'rationale', <<~RATIONALE
    A publicly accessible instance is reachable from the internet, so its
    exposure is bounded only by credentials and the security group.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: aws_db_instance: publicly_accessible is not True;
    aws_rds_cluster_instance: publicly_accessible is not True
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_db_instance:

      resource "aws_db_instance" "example" {
        publicly_accessible = false
      }

    Out of band — aws_db_instance:

      aws rds modify-db-instance --db-instance-identifier <id> --no-publicly-accessible --apply-immediately
  FIX

  tag checkov_id:            'CKV_AWS_17'
  tag checkov_category:      'NETWORKING'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'negative'
  tag tf_resources:          %w[aws_db_instance aws_rds_cluster_instance]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#publicly-accessible'
  tag nist:                  ['SC-7', 'SC-7 (5)']
  tag nist_r4:               ['SC-7', 'SC-7 (5)']
  tag cci:                   ['CCI-001097', 'CCI-002080']
  tag ksi:                   ['KSI-CNA-NDS']
  tag severity:              'high'
  tag severity_source:       'assessed'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  ids = aws_rds_instances.db_instance_identifiers
  in_scope = ids.reject { |id| checkov_exempt?(id: id, type: 'aws_db_instance', rules: exempt) }

  applicable = !in_scope.empty?
  impact 0.7
  impact 0.0 unless applicable
  only_if('no aws_db_instance in scope') { applicable }

  in_scope.each do |id|
    describe aws_rds_instance(id) do
      its('publicly_accessible') { should eq false }
    end
  end
end
