# Generated by tools/render_controls.py — edit the data files, not this file.
#
# Rule:        CKV_AWS_6 (checkov 3.3.16)
# Applies to:  aws_elasticsearch_domain
# Read with:   aws_elasticsearchservice_domains -> aws_elasticsearchservice_domain (stock inspec-aws, no custom reader)
#
# The rule id is the identity: file name, control id and `tag checkov_id` all
# carry it, and tools/lint_catalog_drift.py asserts the three agree.

scan_regions = input('scan_regions')
exempt       = (input('exempt_assets') || {})['CKV_AWS_6'] || []

control 'CKV_AWS_6' do
  title 'Ensure all Elasticsearch has node-to-node encryption enabled'

  desc <<~DESC
    Checkov asserts this against Terraform. This profile asserts it against
    the aws_elasticsearch_domain resources that actually exist, read through
    the stock inspec-aws aws_elasticsearchservice_domain resource.
  DESC

  desc 'rationale', <<~RATIONALE
    Shard replication and query fan-out cross the network in the clear
    unless node-to-node encryption is on, so a domain that terminates TLS at
    its endpoint can still be read off the wire between its own nodes. Note
    this is asserted on every domain: Checkov exempts single-instance
    domains, where the traffic is real as soon as the domain is scaled out.
  RATIONALE

  desc 'check', <<~CHECK
    Checkov looks for: node-to-node encryption is enabled on any domain with
    more than one instance
  CHECK

  desc 'fix', <<~'FIX'
    Terraform — aws_elasticsearch_domain:

      resource "aws_elasticsearch_domain" "search" {
        domain_name           = "search"
        elasticsearch_version = "7.10"

        node_to_node_encryption {
          enabled = true
        }
      }

    Out of band — aws_elasticsearch_domain:

      aws es update-elasticsearch-domain-config --domain-name <name> --node-to-node-encryption-options Enabled=true

    Note (aws_elasticsearch_domain): Enabling node-to-node encryption on a
    running domain triggers a blue/green deployment; on older engine versions it
    is only settable at creation.

    Terraform — aws_opensearch_domain:

      resource "aws_opensearch_domain" "search" {
        domain_name    = "search"
        engine_version = "OpenSearch_2.11"

        node_to_node_encryption {
          enabled = true
        }
      }

    Out of band — aws_opensearch_domain:

      aws opensearch update-domain-config --domain-name <name> --node-to-node-encryption-options Enabled=true
  FIX

  tag checkov_id:            'CKV_AWS_6'
  tag checkov_category:      'ENCRYPTION'
  tag checkov_version:       '3.3.16'
  tag checkov_kind:          'custom'
  tag tf_resources:          %w[aws_elasticsearch_domain aws_opensearch_domain]
  tag tf_docs:               'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain'
  tag nist:                  ['SC-8', 'SC-8 (1)']
  tag nist_r4:               ['SC-8', 'SC-8 (1)']
  tag cci:                   ['CCI-002418', 'CCI-002421']
  tag ksi:                   ['KSI-SVC-CET']
  tag severity:              'high'
  tag severity_source:       'assessed'
  tag nist_source:           'agent-drafted'
  tag implementation_status: 'implemented'

  # Enumerated at control scope, then each asset asserted on its own. The
  # resource is an ARGUMENT to `describe`, which evaluates on the control --
  # calling it inside the block would defer it into the example.
  #
  # Every call carries aws_region: a stock resource otherwise reads only the
  # region the connection was built with, and every other region's resources
  # report as absent, which renders Not Applicable rather than unexamined.
  #
  # checkov_enumerate does the reading. It flattens a nested id column, tells an
  # unregistered column apart from an account that simply has none of this
  # resource, and hands back anything that stopped it as `problems` rather than
  # as an empty list -- see libraries/_checkov_enumeration.rb.
  problems = []
  found = checkov_scan_regions(scan_regions).flat_map do |region|
    ids, found_problems = checkov_enumerate(
      aws_elasticsearchservice_domains(aws_region: region), :domain_names
    )
    problems.concat(found_problems.map { |p| "#{region}: #{p}" })
    ids.map { |id| [id, region] }
  end

  # Blank ids are separated out and asserted on below rather than filtered away,
  # so a wrong `ids` column is a visible failure and not a silent Not Applicable.
  # `id.nil?` before the interpolation on purpose: a NullResponse answers true to
  # nil? but interpolates to "#<NullResponse:0x...>", which is not blank. The
  # survivors are interpolated rather than `.to_s`'d, because to_s on a
  # NullResponse returns nil and the singular then rejects the argument.
  unusable = found.count { |id, _r| id.nil? || "#{id}".strip.empty? }
  found = found.reject { |id, _r| id.nil? || "#{id}".strip.empty? }
               .map { |id, region| ["#{id}", region] }
  in_scope = found.reject { |id, _r| checkov_exempt?(id: id, type: 'aws_elasticsearch_domain', rules: exempt) }

  if unusable.positive? || problems.any?
    describe "aws_elasticsearch_domain enumeration" do
      it 'produced usable identifiers' do
        expect(unusable).to eq(0),
          "#{unusable} row(s) had a blank id — the `ids` column in resource_map.yml "\
          'likely names a field this resource does not expose'
      end

      it 'read the assets it set out to read' do
        expect(problems).to be_empty
      end
    end
  end

  # `unusable.positive? || problems.any?` keeps the control APPLICABLE when the
  # enumeration broke. Without it only_if skips the control, and the broken cases
  # these guards exist to catch are exactly the ones it would suppress — a Not
  # Applicable that means "nobody looked".
  applicable = !in_scope.empty? || unusable.positive? || problems.any?
  impact 0.7
  impact 0.0 unless applicable
  only_if('no aws_elasticsearch_domain in scope') { applicable }

  in_scope.each do |id, region|
    describe aws_elasticsearchservice_domain(domain_name: id, aws_region: region) do
      its('node_to_node_encryption_options.enabled') { should eq true }
    end
  end
end
